// packages/react/src/Components/PasswordField/PasswordField.tsx
// ** External Imports
import { Fragment } from "react";

// ** Core Imports
import { cn } from "@bridge-ui/core";

// ** Local Imports
import { FormField } from "@/Components/FormField";
import { Icon } from "@/Components/Icon";
import { usePasswordField } from "@/Components/PasswordField/hooks/usePasswordField";
import type { PasswordFieldProps } from "@/Components/PasswordField/passwordField.types";
import { mergePartBind, resolveFieldAdornmentIconSize } from "@/Utils";

function PasswordField(props: PasswordFieldProps) {
  const { formField, inputBind, isVisible, mergedClasses, toggleVisibility } =
    usePasswordField(props);

  const toggleProps = props.customProps?.toggle;
  const toggleIconProps = props.customProps?.toggleIcon;

  return (
    <FormField
      field={{
        ...formField,
        slots: {
          ...props.slots,
          end: (
            <Fragment>
              <button
                {...mergePartBind(
                  toggleProps,
                  {
                    type: "button",
                    disabled: props.disabled,
                    onClick: toggleVisibility,
                    "aria-label": isVisible ? "Hide password" : "Show password",
                  },
                  cn({
                    "bridge-end-adornment bridge-field-adornment-button inline-flex h-full items-center justify-center px-2.5": true,
                    [mergedClasses.toggle ?? ""]: true,
                  }),
                )}
              >
                <Icon
                  icon={isVisible ? "eyeOff" : "eye"}
                  size={resolveFieldAdornmentIconSize(props.size)}
                  {...toggleIconProps}
                />
              </button>
            </Fragment>
          ),
        },
      }}
    >
      <input {...inputBind} />
    </FormField>
  );
}

export default PasswordField;

// packages/vue/src/Components/PasswordField/PasswordField.vue
<script setup lang="ts">
// ** External Imports
import { Eye, EyeOff } from "@lucide/vue";
import { computed } from "vue";

// ** Core Imports
import { cn } from "@bridge-ui/core";

// ** Local Imports
import { FormField } from "@/Components/FormField";
import { Icon } from "@/Components/Icon";
import { usePasswordField } from "@/Components/PasswordField/composables/usePasswordField";
import type {
  PasswordFieldEmits,
  PasswordFieldOwnProps,
  PasswordFieldSlots,
} from "@/Components/PasswordField/passwordField.types";
import { resolveFieldAdornmentIconSize } from "@/Utils";

defineSlots<PasswordFieldSlots>();

defineOptions({ inheritAttrs: false });

const emit = defineEmits<PasswordFieldEmits>();

const model = defineModel<null | string | undefined>();

const props = withDefaults(defineProps<PasswordFieldOwnProps>(), {
  visible: null,
});

const { formField, inputBind, isVisible, mergedClasses, toggleVisibility } =
  usePasswordField(props, {
    onVisibilityChange: (next) => emit("visibility-change", next),
  });

const toggleIconSize = computed(() => {
  return resolveFieldAdornmentIconSize(props.size);
});
</script>

<template>
  <FormField :field="formField">
    <input v-model="model" v-bind="inputBind" />

    <template #end>
      <button
        type="button"
        :disabled="props.disabled"
        v-on:click="toggleVisibility"
        :aria-label="isVisible ? 'Hide password' : 'Show password'"
        :class="
          cn({
            'bridge-end-adornment bridge-field-adornment-button inline-flex h-full items-center justify-center px-2.5': true,
            [mergedClasses.toggle ?? '']: true,
          })
        "
      >
        <Icon :size="toggleIconSize" :icon="isVisible ? EyeOff : Eye" />
      </button>
    </template>
  </FormField>
</template>
