// packages/vue/src/Components/AccordionItem/AccordionItem.vue
<script setup lang="ts">
// ** Local Imports
import type {
  AccordionItemOwnProps,
  AccordionItemSlots,
} from "@/Components/AccordionItem/accordionItem.types";
import { useAccordionItem } from "@/Components/AccordionItem/composables/useAccordionItem";
import { Icon } from "@/Components/Icon";
import { hasNamedSlot, isPropPresent } from "@/Utils";

defineSlots<AccordionItemSlots>();

defineOptions({ inheritAttrs: false });

const props = defineProps<AccordionItemOwnProps>();

const {
  slots,
  merged,
  rootBind,
  titleBind,
  panelBind,
  triggerBind,
  collapseBind,
  indicatorBind,
  panelInnerBind,
} = useAccordionItem(props);
</script>

<template>
  <div v-bind="rootBind">
    <button v-bind="triggerBind">
      <span v-bind="titleBind">
        <slot name="title" v-if="hasNamedSlot(slots, 'title')" />

        <template v-else-if="isPropPresent(merged.title)">
          {{ merged.title }}
        </template>
      </span>

      <slot name="indicator" v-if="hasNamedSlot(slots, 'indicator')" />

      <Icon v-else icon="chevronDown" v-bind="indicatorBind" />
    </button>

    <div v-bind="collapseBind">
      <div v-bind="panelInnerBind">
        <div v-bind="panelBind">
          <slot />
        </div>
      </div>
    </div>
  </div>
</template>

// packages/react/src/Components/AccordionItem/AccordionItem.tsx
// ** Local Imports
import type { AccordionItemProps } from "@/Components/AccordionItem/accordionItem.types";
import { useAccordionItem } from "@/Components/AccordionItem/hooks/useAccordionItem";
import { Icon } from "@/Components/Icon";
import { hasNamedSlot } from "@/Utils";

function AccordionItem(props: AccordionItemProps) {
  const {
    slots,
    merged,
    children,
    rootBind,
    titleBind,
    panelBind,
    triggerBind,
    collapseBind,
    indicatorBind,
    panelInnerBind,
  } = useAccordionItem(props);

  return (
    <div {...rootBind}>
      <button {...triggerBind}>
        <span {...titleBind}>
          {hasNamedSlot(slots, "title") ? slots?.title : merged.title}
        </span>

        {hasNamedSlot(slots, "indicator") ? (
          slots?.indicator
        ) : (
          <Icon icon="chevronDown" {...indicatorBind} />
        )}
      </button>

      <div {...collapseBind}>
        <div {...panelInnerBind}>
          <div {...panelBind}>{children}</div>
        </div>
      </div>
    </div>
  );
}

export default AccordionItem;
