// packages/vue/src/Components/TextField/EndAdornment.vue
<script setup lang="ts">
// ** Core Imports
import { cn } from "@bridge-ui/core";

const props = defineProps<{
  /**
   * Extra classes merged onto the inner wrapper (e.g. Button radius).
   */
  class?: string;
}>();

// prettier-ignore
const buttonChildClass = "[&_button]:h-full [&_button]:min-h-0 [&_button]:rounded-e-none [&_button]:rounded-s-none";
</script>

<template>
  <div :class="cn('flex items-center', buttonChildClass, props.class)">
    <slot />
  </div>
</template>

// packages/react/src/Components/TextField/EndAdornment.tsx
// ** Core Imports
import { cn } from "@bridge-ui/core";
import type { HTMLAttributes, ReactNode } from "react";

// prettier-ignore
const buttonChildClass = "[&_button]:h-full [&_button]:min-h-0 [&_button]:rounded-e-none [&_button]:rounded-s-none";

export type EndAdornmentProps = HTMLAttributes<HTMLDivElement>;

function EndAdornment({ className, children, ...props }: EndAdornmentProps) {
  return (
    <div
      {...props}
      className={cn("flex items-center", buttonChildClass, className)}
    >
      {children as ReactNode}
    </div>
  );
}

export default EndAdornment;
