// packages/vue/src/Components/ListItem/ListItem.vue
<script setup lang="ts">
// ** External Imports
import { computed, useSlots } from "vue";

// ** Local Imports
import Icon from "@/Components/Icon/Icon.vue";
import {
  resolveListItemPrimary,
  useListItem,
} from "@/Components/ListItem/composables/useListItem";
import type {
  ListItemOwnProps,
  ListItemSlots,
} from "@/Components/ListItem/listItem.types";
import { hasNamedSlot, resolveNamedSlot, resolveSlotOrProp } from "@/Utils";

defineSlots<ListItemSlots>();

const slots = useSlots();

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<ListItemOwnProps>(), {
  as: "li",
  role: "button",
  divider: false,
  align: "center",
  disabled: false,
  selected: false,
  interactive: false,
});

const {
  merged,
  hasEnd,
  endBind,
  rootBind,
  rowClass,
  hasStart,
  startBind,
  hasPrimary,
  contentBind,
  primaryBind,
  hasSecondary,
  secondaryBind,
  interactiveBind,
  selectedIconBind,
  resolvedSelectedIcon,
} = useListItem(props, { role: "button", align: "center" }, slots);

const rootTag = computed(() => {
  return merged.value.as ?? "li";
});

const primaryContent = computed(() => {
  return resolveListItemPrimary(slots, props.primary);
});

const secondaryContent = computed(() => {
  return resolveSlotOrProp(slots, "secondary", props.secondary);
});

const hasEndSlot = computed(() => {
  return hasNamedSlot(slots, "end");
});
</script>

<template>
  <component :is="rootTag" v-bind="rootBind">
    <div v-if="interactiveBind" v-bind="interactiveBind">
      <div :class="rowClass">
        <div v-if="hasStart" v-bind="startBind">
          <component :is="resolveNamedSlot(slots, 'start')" />
        </div>

        <div v-bind="contentBind">
          <span v-if="hasPrimary" v-bind="primaryBind">
            <component :is="primaryContent" />
          </span>

          <span v-if="hasSecondary" v-bind="secondaryBind">
            <component :is="secondaryContent" />
          </span>
        </div>

        <div v-if="hasEnd" v-bind="endBind">
          <component v-if="hasEndSlot" :is="resolveNamedSlot(slots, 'end')" />

          <Icon
            v-bind="selectedIconBind"
            :icon="resolvedSelectedIcon"
            v-else-if="resolvedSelectedIcon"
          />
        </div>
      </div>
    </div>

    <div v-else :class="rowClass">
      <div v-if="hasStart" v-bind="startBind">
        <component :is="resolveNamedSlot(slots, 'start')" />
      </div>

      <div v-bind="contentBind">
        <span v-if="hasPrimary" v-bind="primaryBind">
          <component :is="primaryContent" />
        </span>

        <span v-if="hasSecondary" v-bind="secondaryBind">
          <component :is="secondaryContent" />
        </span>
      </div>

      <div v-if="hasEnd" v-bind="endBind">
        <component v-if="hasEndSlot" :is="resolveNamedSlot(slots, 'end')" />

        <Icon
          v-bind="selectedIconBind"
          :icon="resolvedSelectedIcon"
          v-else-if="resolvedSelectedIcon"
        />
      </div>
    </div>
  </component>
</template>

// packages/react/src/Components/ListItem/ListItem.tsx
// ** External Imports
import { createElement } from "react";

// ** Local Imports
import { Icon } from "@/Components/Icon";
import { useListItem } from "@/Components/ListItem/hooks/useListItem";
import type { ListItemProps } from "@/Components/ListItem/listItem.types";

function ListItemRow({
  slots,
  hasEnd,
  endBind,
  hasStart,
  startBind,
  hasPrimary,
  contentBind,
  primaryBind,
  hasSecondary,
  rowClassName,
  secondaryBind,
  primaryContent,
  secondaryContent,
  selectedIconBind,
  resolvedSelectedIcon,
}: ReturnType<typeof useListItem>) {
  return (
    <div className={rowClassName}>
      {hasStart ? <div {...startBind}>{slots?.start}</div> : null}

      <div {...contentBind}>
        {hasPrimary ? <span {...primaryBind}>{primaryContent}</span> : null}

        {hasSecondary ? (
          <span {...secondaryBind}>{secondaryContent}</span>
        ) : null}
      </div>

      {hasEnd ? (
        <div {...endBind}>
          {slots?.end}

          {!slots?.end && resolvedSelectedIcon != null ? (
            <Icon icon={resolvedSelectedIcon} {...selectedIconBind} />
          ) : null}
        </div>
      ) : null}
    </div>
  );
}

function ListItem(props: ListItemProps) {
  const listItemState = useListItem(props, {
    role: "button",
    align: "center",
  });

  const row = <ListItemRow {...listItemState} />;

  return createElement(
    listItemState.merged.as ?? "li",
    listItemState.rootBind,
    listItemState.interactiveBind ? (
      <div {...listItemState.interactiveBind}>{row}</div>
    ) : (
      row
    ),
  );
}

export default ListItem;
