// packages/vue/src/Components/Listbox/Listbox.vue
<script setup lang="ts">
// ** External Imports
import { isNil } from "es-toolkit/compat";
import { computed, provide, ref, useSlots, watch } from "vue";

// ** Core Imports
import {
  entriesFromListboxOptions,
  flattenListboxOptions,
  mapListboxEntriesToRows,
  upsertListboxOption,
  type ListboxOption,
  type ListboxValue,
} from "@bridge-ui/core/Domain";
import { cn } from "@bridge-ui/core/Utils";

// ** Local Imports
import { useResolveMessage } from "@/Adapters/I18n";
import { ActionFooter } from "@/Components/ActionFooter";
import { FieldOverlay } from "@/Components/FieldOverlay";
import { List } from "@/Components/List";
import { useListbox } from "@/Components/Listbox/composables/useListbox";
import type {
  ListboxEmits,
  ListboxOwnProps,
  ListboxSlots,
} from "@/Components/Listbox/listbox.types";
import {
  LISTBOX_INJECTION_KEY,
  type ListboxContextValue,
} from "@/Components/Listbox/listboxInjectionKey";
import { ListItem } from "@/Components/ListItem";
import { ListSection } from "@/Components/ListSection";
import { Progress } from "@/Components/Progress";
import { hasNamedSlot, mergeNestedComponentProps } from "@/Utils";

defineSlots<ListboxSlots>();

const slots = useSlots();

const emit = defineEmits<ListboxEmits>();

const open = defineModel<boolean>({ default: false });

watch(open, (show) => {
  emit("show-change", show);
});

const props = withDefaults(defineProps<ListboxOwnProps>(), {
  size: "md",
  loading: false,
  multiple: false,
  overlay: "auto",
  showCheckmark: true,
  highlightedIndex: -1,
  showFooter: undefined,
  hideEmptyMessage: false,
  disableAutoFocus: false,
  placement: "bottom-start",
});

const resolveMessage = useResolveMessage();

const emptyMessage = computed(() => {
  return props.emptyMessage ?? resolveMessage("No options");
});

const loadingMessage = computed(() => {
  return props.loadingMessage ?? resolveMessage("Loading...");
});

const {
  merged,
  checkClass,
  scrollBind,
  footerBind,
  showFooter,
  messageBind,
  surfaceBind,
  sizeClasses,
  mergedClasses,
  applyButtonProps,
  optionHoverClass,
  cancelButtonProps,
  optionSelectedClass,
  optionHighlightedClass,
} = useListbox(props, {
  size: "md",
  color: "primary",
});

const resolvedOptions = computed(() => {
  return props.options ?? [];
});

const resolvedEntries = computed(() => {
  if (props.entries) {
    return props.entries;
  }

  return entriesFromListboxOptions(resolvedOptions.value);
});

const flatOptions = computed(() => {
  return flattenListboxOptions(resolvedEntries.value);
});

const hasComposedChildren = computed(() => {
  return hasNamedSlot(slots, "default");
});

const showEmptyState = computed(() => {
  return (
    !props.loading &&
    !hasComposedChildren.value &&
    flatOptions.value.length === 0 &&
    props.hideEmptyMessage !== true
  );
});

const resolvedCheckClass = computed(() => {
  return cn(checkClass.value, mergedClasses.value.check);
});

const registeredOptions = ref<ListboxOption[]>([]);

function resolveSelected(value: ListboxValue) {
  return props.isSelected?.(value) ?? false;
}

function handleSelect(option: ListboxOption) {
  if (option.disabled) {
    return;
  }

  emit("select", option);
}

function registerOption(option: ListboxOption) {
  const next = upsertListboxOption(registeredOptions.value, option);

  if (next !== registeredOptions.value) {
    registeredOptions.value = next;
  }

  return () => {
    registeredOptions.value = registeredOptions.value.filter(
      (entry) => String(entry.value) !== String(option.value),
    );
  };
}

function getOptionIndex(value: ListboxValue) {
  const source = hasComposedChildren.value
    ? registeredOptions.value
    : flatOptions.value;

  return source.findIndex((option) => String(option.value) === String(value));
}

watch(
  registeredOptions,
  (options) => {
    if (!hasComposedChildren.value) {
      return;
    }

    emit("registered-options-change", options);
  },
  { deep: true },
);

const listboxContext = computed((): ListboxContextValue => {
  return {
    getOptionIndex,
    registerOption,
    onSelect: handleSelect,
    listboxId: props.listboxId,
    isSelected: resolveSelected,
    sizeClasses: sizeClasses.value,
    showCheckmark: props.showCheckmark,
    checkClass: resolvedCheckClass.value,
    highlightedIndex: props.highlightedIndex,
    optionHoverClass: optionHoverClass.value,
    optionSelectedClass: optionSelectedClass.value,
    optionHighlightedClass: optionHighlightedClass.value,
    mergedClasses: {
      optionHover: mergedClasses.value.optionHover,
      optionSelected: mergedClasses.value.optionSelected,
      optionHighlighted: mergedClasses.value.optionHighlighted,
    },
  };
});

provide(LISTBOX_INJECTION_KEY, listboxContext);

const mappedRows = computed(() => {
  return mapListboxEntriesToRows(resolvedEntries.value, resolveSelected);
});

const menuProps = computed(() => {
  return merged.value.customProps?.menu;
});

const modalProps = computed(() => {
  return merged.value.customProps?.modal;
});

const drawerProps = computed(() => {
  return merged.value.customProps?.drawer;
});

const listProps = computed(() => {
  return merged.value.customProps?.list;
});

const listItemProps = computed(() => {
  return merged.value.customProps?.listItem;
});

const progressProps = computed(() => {
  return merged.value.customProps?.progress;
});

const listSectionProps = computed(() => {
  return merged.value.customProps?.listSection;
});

const overlayCustomProps = computed(() => {
  return {
    modal: modalProps.value,
    drawer: drawerProps.value,
    menu: {
      anchorEl: props.anchorEl,
      placement: props.placement,
      disableAutoFocus: props.disableAutoFocus,
      ...(!isNil(props.rounded) ? { rounded: props.rounded } : {}),
      ...(!isNil(merged.value.matchWidth)
        ? { matchWidth: merged.value.matchWidth }
        : {}),
      ...menuProps.value,
    },
  };
});

const progressBind = computed(() => {
  return {
    size: "xs" as const,
    "aria-hidden": true,
    color: merged.value.color,
    ...mergeNestedComponentProps(progressProps.value, {
      class: "shrink-0",
      classes: { bar: mergedClasses.value.loading },
    }),
  };
});

const listBind = computed(() => {
  return {
    role: "listbox",
    id: props.listboxId,
    "aria-labelledby": props.labelledBy,
    "aria-multiselectable": props.multiple || undefined,
    ...mergeNestedComponentProps(listProps.value),
  };
});

function handleApply() {
  emit("apply");

  open.value = false;
}

function handleCancel() {
  emit("cancel");

  open.value = false;
}
</script>

<template>
  <FieldOverlay
    v-model="open"
    :overlay="overlay"
    :custom-props="overlayCustomProps"
  >
    <div :class="surfaceBind">
      <slot name="beforeOptions" v-if="hasNamedSlot(slots, 'beforeOptions')" />

      <template v-if="loading">
        <Progress v-bind="progressBind" />

        <div v-bind="messageBind">
          <slot name="loading" v-if="hasNamedSlot(slots, 'loading')" />

          <span v-else>{{ loadingMessage }}</span>
        </div>
      </template>

      <div v-else v-bind="scrollBind">
        <List v-bind="listBind">
          <slot v-if="hasComposedChildren" />

          <template v-else :key="row.key" v-for="row in mappedRows">
            <ListSection
              :title="row.title"
              :sticky="row.sticky"
              v-bind="listSectionProps"
              v-if="row.kind === 'section'"
            />

            <ListItem
              v-else
              interactive
              :value="row.option.value"
              :disabled="row.option.disabled"
              :secondary="row.option.description"
              :primary="
                hasNamedSlot(slots, 'option') ? undefined : row.option.label
              "
              v-bind="listItemProps"
            >
              <template #default v-if="hasNamedSlot(slots, 'option')">
                <slot
                  name="option"
                  :option="row.option"
                  :selected="row.selected"
                />
              </template>
            </ListItem>
          </template>
        </List>
      </div>

      <div
        v-bind="messageBind"
        v-if="showEmptyState && !hasNamedSlot(slots, 'empty')"
      >
        {{ emptyMessage }}
      </div>

      <slot
        name="empty"
        v-else-if="showEmptyState && hasNamedSlot(slots, 'empty')"
      />

      <slot name="afterOptions" v-if="hasNamedSlot(slots, 'afterOptions')" />

      <div v-if="showFooter" v-bind="footerBind">
        <slot name="footer" :apply="handleApply" :cancel="handleCancel">
          <ActionFooter
            v-on:apply="handleApply"
            v-on:cancel="handleCancel"
            :custom-props="{
              applyButton: applyButtonProps,
              cancelButton: cancelButtonProps,
            }"
          />
        </slot>
      </div>
    </div>
  </FieldOverlay>
</template>

// packages/react/src/Components/Listbox/Listbox.tsx
// ** External Imports
import { isNil } from "es-toolkit/compat";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

// ** Core Imports
import {
  entriesFromListboxOptions,
  flattenListboxOptions,
  mapListboxEntriesToRows,
  upsertListboxOption,
  type ListboxOption,
  type ListboxValue,
} from "@bridge-ui/core/Domain";
import { cn } from "@bridge-ui/core/Utils";

// ** Local Imports
import { useResolveMessage } from "@/Adapters/I18n";
import { ActionFooter } from "@/Components/ActionFooter";
import { FieldOverlay } from "@/Components/FieldOverlay";
import { List } from "@/Components/List";
import { useListbox } from "@/Components/Listbox/hooks/useListbox";
import type { ListboxProps } from "@/Components/Listbox/listbox.types";
import {
  ListboxContext,
  type ListboxContextValue,
} from "@/Components/Listbox/ListboxContext";
import { ListItem } from "@/Components/ListItem";
import { ListSection } from "@/Components/ListSection";
import { Progress } from "@/Components/Progress";
import { mergeNestedComponentProps } from "@/Utils";

const listboxLibDefaults = {
  size: "md",
  color: "primary",
} as const;

function Listbox({
  slots,
  options,
  entries,
  rounded,
  overlay,
  onApply,
  children,
  onCancel,
  onSelect,
  anchorEl,
  listboxId,
  labelledBy,
  show = false,
  onShowChange,
  loading = false,
  multiple = false,
  showCheckmark = true,
  highlightedIndex = -1,
  hideEmptyMessage = false,
  disableAutoFocus = false,
  onRegisteredOptionsChange,
  placement = "bottom-start",
  isSelected: isSelectedProp,
  emptyMessage: emptyMessageProp,
  loadingMessage: loadingMessageProp,
  ...ownProps
}: ListboxProps) {
  const resolveMessage = useResolveMessage();
  const emptyMessage = emptyMessageProp ?? resolveMessage("No options");
  const loadingMessage = loadingMessageProp ?? resolveMessage("Loading...");

  const resolvedOptions = useMemo(() => {
    return options ?? [];
  }, [options]);

  const {
    merged,
    checkClass,
    scrollBind,
    footerBind,
    showFooter,
    messageBind,
    surfaceBind,
    sizeClasses,
    mergedClasses,
    applyButtonProps,
    optionHoverClass,
    cancelButtonProps,
    optionSelectedClass,
    optionHighlightedClass,
  } = useListbox(
    {
      ...ownProps,
      rounded,
      loading,
      multiple,
      anchorEl,
      listboxId,
      placement,
      labelledBy,
      emptyMessage,
      showCheckmark,
      highlightedIndex,
      hideEmptyMessage,
      disableAutoFocus,
      options: resolvedOptions,
      isSelected: isSelectedProp,
    },
    listboxLibDefaults,
    { overlay },
  );

  const resolvedEntries = useMemo(() => {
    if (entries) {
      return entries;
    }

    return entriesFromListboxOptions(resolvedOptions);
  }, [entries, resolvedOptions]);

  const flatOptions = useMemo(() => {
    return flattenListboxOptions(resolvedEntries);
  }, [resolvedEntries]);

  const hasComposedChildren = !isNil(children);

  const showEmptyState =
    !loading &&
    !hasComposedChildren &&
    flatOptions.length === 0 &&
    hideEmptyMessage !== true;

  const resolvedCheckClass = cn(checkClass, mergedClasses.check);

  const registeredOptionsRef = useRef<ListboxOption[]>([]);
  const [registeredOptions, setRegisteredOptions] = useState<ListboxOption[]>(
    [],
  );
  const flatOptionsRef = useRef(flatOptions);
  const hasComposedChildrenRef = useRef(hasComposedChildren);

  useEffect(() => {
    flatOptionsRef.current = flatOptions;
  }, [flatOptions]);

  useEffect(() => {
    hasComposedChildrenRef.current = hasComposedChildren;
  }, [hasComposedChildren]);

  const resolveSelected = useCallback(
    (value: ListboxValue) => {
      return isSelectedProp?.(value) ?? false;
    },
    [isSelectedProp],
  );

  const mappedRows = useMemo(() => {
    return mapListboxEntriesToRows(resolvedEntries, resolveSelected);
  }, [resolveSelected, resolvedEntries]);

  const handleSelect = useCallback(
    (option: ListboxOption) => {
      if (option.disabled) {
        return;
      }

      onSelect?.(option);
    },
    [onSelect],
  );

  const handleApply = useCallback(() => {
    onApply?.();

    onShowChange?.(false);
  }, [onApply, onShowChange]);

  const handleCancel = useCallback(() => {
    onCancel?.();

    onShowChange?.(false);
  }, [onCancel, onShowChange]);

  const registerOption = useCallback((option: ListboxOption) => {
    const next = upsertListboxOption(registeredOptionsRef.current, option);

    if (next !== registeredOptionsRef.current) {
      registeredOptionsRef.current = next;
      setRegisteredOptions(next);
    }

    return () => {
      registeredOptionsRef.current = registeredOptionsRef.current.filter(
        (entry) => String(entry.value) !== String(option.value),
      );
      setRegisteredOptions([...registeredOptionsRef.current]);
    };
  }, []);

  const getOptionIndex = useCallback((value: ListboxValue) => {
    const source = hasComposedChildrenRef.current
      ? registeredOptionsRef.current
      : flatOptionsRef.current;

    return source.findIndex((option) => String(option.value) === String(value));
  }, []);

  useEffect(() => {
    if (!hasComposedChildren) {
      return;
    }

    onRegisteredOptionsChange?.(registeredOptions);
  }, [registeredOptions, hasComposedChildren, onRegisteredOptionsChange]);

  const listboxContext = useMemo((): ListboxContextValue => {
    return {
      listboxId,
      sizeClasses,
      showCheckmark,
      getOptionIndex,
      registerOption,
      highlightedIndex,
      optionHoverClass,
      optionSelectedClass,
      onSelect: handleSelect,
      optionHighlightedClass,
      isSelected: resolveSelected,
      checkClass: resolvedCheckClass,
      mergedClasses: {
        optionHover: mergedClasses.optionHover,
        optionSelected: mergedClasses.optionSelected,
        optionHighlighted: mergedClasses.optionHighlighted,
      },
    };
  }, [
    listboxId,
    sizeClasses,
    handleSelect,
    showCheckmark,
    getOptionIndex,
    registerOption,
    resolveSelected,
    highlightedIndex,
    optionHoverClass,
    resolvedCheckClass,
    optionSelectedClass,
    optionHighlightedClass,
    mergedClasses.optionHover,
    mergedClasses.optionSelected,
    mergedClasses.optionHighlighted,
  ]);

  const menuProps = merged.customProps?.menu;
  const listProps = merged.customProps?.list;
  const modalProps = merged.customProps?.modal;
  const drawerProps = merged.customProps?.drawer;
  const listItemProps = merged.customProps?.listItem;
  const progressProps = merged.customProps?.progress;
  const listSectionProps = merged.customProps?.listSection;

  return (
    <FieldOverlay
      show={show}
      overlay={overlay}
      onShowChange={onShowChange}
      customProps={{
        modal: modalProps,
        drawer: drawerProps,
        menu: {
          anchorEl,
          placement,
          disableAutoFocus,
          ...(!isNil(rounded) ? { rounded } : {}),
          ...(!isNil(merged.matchWidth)
            ? { matchWidth: merged.matchWidth }
            : {}),
          ...menuProps,
        },
      }}
    >
      <div className={surfaceBind}>
        {slots?.beforeOptions}

        {loading ? (
          <>
            <Progress
              size="xs"
              aria-hidden
              color={merged.color}
              {...mergeNestedComponentProps(progressProps, {
                className: "shrink-0",
                classes: { bar: mergedClasses.loading },
              })}
            />

            <div {...messageBind}>{slots?.loading ?? loadingMessage}</div>
          </>
        ) : (
          <div {...scrollBind}>
            <ListboxContext.Provider value={listboxContext}>
              <List
                role="listbox"
                id={listboxId}
                aria-labelledby={labelledBy}
                aria-multiselectable={multiple || undefined}
                {...mergeNestedComponentProps(listProps)}
              >
                {hasComposedChildren
                  ? children
                  : mappedRows.map((row) => {
                      if (row.kind === "section") {
                        return (
                          <ListSection
                            key={row.key}
                            title={row.title}
                            sticky={row.sticky}
                            {...listSectionProps}
                          />
                        );
                      }

                      const { option, selected } = row;

                      return (
                        <ListItem
                          interactive
                          key={row.key}
                          value={option.value}
                          disabled={option.disabled}
                          secondary={option.description}
                          primary={slots?.option ? undefined : option.label}
                          {...listItemProps}
                        >
                          {slots?.option?.({ option, selected })}
                        </ListItem>
                      );
                    })}
              </List>
            </ListboxContext.Provider>
          </div>
        )}

        {showEmptyState && !slots?.empty ? (
          <div {...messageBind}>{emptyMessage}</div>
        ) : null}

        {showEmptyState && slots?.empty ? slots.empty : null}

        {slots?.afterOptions}

        {showFooter ? (
          <div {...footerBind}>
            {slots?.footer ? (
              slots.footer({ apply: handleApply, cancel: handleCancel })
            ) : (
              <ActionFooter
                color={merged.color}
                onApply={handleApply}
                onCancel={handleCancel}
                customProps={{
                  applyButton: applyButtonProps,
                  cancelButton: cancelButtonProps,
                }}
              />
            )}
          </div>
        ) : null}
      </div>
    </FieldOverlay>
  );
}

export default Listbox;
