// packages/vue/src/Components/CalendarMonth/CalendarMonth.vue
<script setup lang="ts">
// ** Local Imports
import type {
  CalendarMonthEmits,
  CalendarMonthOwnProps,
} from "@/Components/CalendarMonth/calendarMonth.types";
import { useCalendarMonth } from "@/Components/CalendarMonth/composables/useCalendarMonth";

defineOptions({ inheritAttrs: false });

const emit = defineEmits<CalendarMonthEmits>();

const props = defineProps<CalendarMonthOwnProps>();

const { months, rootBind, gridBind, getMonthBind } = useCalendarMonth(
  props,
  { rounded: "md", color: "primary" },
  emit,
);
</script>

<template>
  <div v-bind="rootBind">
    <div v-bind="gridBind">
      <button
        :key="cell.month"
        v-for="cell in months"
        v-bind="getMonthBind(cell)"
      >
        {{ cell.label }}
      </button>
    </div>
  </div>
</template>

// packages/react/src/Components/CalendarMonth/CalendarMonth.tsx
// ** Local Imports
import type { CalendarMonthProps } from "@/Components/CalendarMonth/calendarMonth.types";
import { useCalendarMonth } from "@/Components/CalendarMonth/hooks/useCalendarMonth";

function CalendarMonth(props: CalendarMonthProps) {
  const { months, rootBind, gridBind, getMonthBind } = useCalendarMonth(props, {
    rounded: "md",
    color: "primary",
  });

  return (
    <div {...rootBind}>
      <div {...gridBind}>
        {months.map((cell) => (
          <button key={cell.month} {...getMonthBind(cell)}>
            {cell.label}
          </button>
        ))}
      </div>
    </div>
  );
}

export default CalendarMonth;
