// packages/vue/src/Components/List/List.vue
<script setup lang="ts">
// ** External Imports
import { computed, useSlots } from "vue";

// ** Local Imports
import { useList } from "@/Components/List/composables/useList";
import type { ListOwnProps } from "@/Components/List/list.types";
import { resolveNamedSlot } from "@/Utils";

const slots = useSlots();

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<ListOwnProps>(), {
  as: "ul",
  dense: false,
  nested: false,
  padding: "normal",
});

const { merged, rootBind } = useList(props, {
  padding: "normal",
});

const rootTag = computed(() => {
  return merged.value.as ?? "ul";
});
</script>

<template>
  <component :is="rootTag" v-bind="rootBind">
    <component :is="resolveNamedSlot(slots, 'default')" />
  </component>
</template>

// packages/react/src/Components/List/List.tsx
// ** External Imports
import { createElement } from "react";

// ** Local Imports
import { ListContext } from "@/Components/List/ListContext";
import { useList } from "@/Components/List/hooks/useList";
import type { ListProps } from "@/Components/List/list.types";

function List(props: ListProps) {
  const { merged, children, rootBind, contextValue } = useList(props, {
    padding: "normal",
  });

  return (
    <ListContext.Provider value={contextValue}>
      {createElement(merged.as ?? "ul", rootBind, children)}
    </ListContext.Provider>
  );
}

export default List;
