// packages/vue/src/Components/CalendarDate/CalendarDate.vue
<script setup lang="ts">
// ** Local Imports
import type {
  CalendarDateEmits,
  CalendarDateOwnProps,
} from "@/Components/CalendarDate/calendarDate.types";
import { useCalendarDate } from "@/Components/CalendarDate/composables/useCalendarDate";

defineOptions({ inheritAttrs: false });

const props = defineProps<CalendarDateOwnProps>();

const emit = defineEmits<CalendarDateEmits>();

const {
  days,
  rootBind,
  gridBind,
  weekdays,
  getDayBind,
  hideWeekdays,
  getWeekdayBind,
} = useCalendarDate(props, { startOfWeek: 0, color: "primary" }, emit);

function adapterDayKey(date: Date) {
  return `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`;
}
</script>

<template>
  <div v-bind="rootBind">
    <div role="row" v-if="!hideWeekdays" class="grid grid-cols-7 gap-1">
      <span
        :key="`${label}-${index}`"
        v-bind="getWeekdayBind(label)"
        v-for="(label, index) in weekdays"
      >
        {{ label }}
      </span>
    </div>

    <div v-bind="gridBind">
      <button
        v-for="cell in days"
        :key="`${adapterDayKey(cell.date)}-${cell.label}`"
        v-bind="getDayBind(cell)"
      >
        {{ cell.label }}
      </button>
    </div>
  </div>
</template>

// packages/react/src/Components/CalendarDate/CalendarDate.tsx
// ** Local Imports
import type { CalendarDateProps } from "@/Components/CalendarDate/calendarDate.types";
import { useCalendarDate } from "@/Components/CalendarDate/hooks/useCalendarDate";

function adapterDayKey(date: Date) {
  return `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`;
}

function CalendarDate(props: CalendarDateProps) {
  const {
    days,
    rootBind,
    gridBind,
    weekdays,
    getDayBind,
    hideWeekdays,
    getWeekdayBind,
  } = useCalendarDate(props, {
    startOfWeek: 0,
    color: "primary",
  });

  return (
    <div {...rootBind}>
      {!hideWeekdays && (
        <div role="row" className="grid grid-cols-7 gap-1">
          {weekdays.map((label, index) => (
            <span key={`${label}-${index}`} {...getWeekdayBind(label)}>
              {label}
            </span>
          ))}
        </div>
      )}

      <div {...gridBind}>
        {days.map((cell) => (
          <button
            key={`${adapterDayKey(cell.date)}-${cell.label}`}
            {...getDayBind(cell)}
          >
            {cell.label}
          </button>
        ))}
      </div>
    </div>
  );
}

export default CalendarDate;
