// packages/vue/src/Components/Spinner/Spinner.vue
<script setup lang="ts">
// ** Local Imports
import { useSpinner } from "@/Components/Spinner/composables/useSpinner";
import type { SpinnerOwnProps } from "@/Components/Spinner/spinner.types";

defineOptions({ inheritAttrs: false });

const props = defineProps<SpinnerOwnProps>();

const { svgBind, rootBind, trackBind, circleBind, enableTrack } = useSpinner(
  props,
  {
    size: "md",
    thickness: 3.6,
    color: "primary",
    enableTrack: false,
    disableShrink: false,
    variant: "indeterminate",
  },
);
</script>

<template>
  <span v-bind="rootBind">
    <svg v-bind="svgBind">
      <circle v-bind="trackBind" v-if="enableTrack && trackBind" />
      <circle v-bind="circleBind" />
    </svg>
  </span>
</template>

// packages/react/src/Components/Spinner/Spinner.tsx
// ** Local Imports
import { useSpinner } from "@/Components/Spinner/hooks/useSpinner";
import type { SpinnerProps } from "@/Components/Spinner/spinner.types";

function Spinner(props: SpinnerProps) {
  const { svgBind, rootBind, trackBind, circleBind, enableTrack } = useSpinner(
    props,
    {
      size: "md",
      thickness: 3.6,
      color: "primary",
      enableTrack: false,
      disableShrink: false,
      variant: "indeterminate",
    },
  );

  return (
    <span {...rootBind}>
      <svg {...svgBind}>
        {enableTrack && trackBind ? <circle {...trackBind} /> : null}
        <circle {...circleBind} />
      </svg>
    </span>
  );
}

export default Spinner;
