// packages/react/src/Components/Pagination/Pagination.tsx
// ** Local Imports
import { Icon } from "@/Components/Icon";
import { usePagination } from "@/Components/Pagination/hooks/usePagination";
import type { PaginationProps } from "@/Components/Pagination/pagination.types";

const paginationLibDefaults = {
  size: "md",
  rounded: "md",
  color: "dark",
  defaultPage: 1,
  disabled: false,
  siblingCount: 1,
  variant: "ghost",
  mode: "numbered",
  boundaryCount: 1,
  hideNextButton: false,
  hidePrevButton: false,
} as const;

function Pagination(props: PaginationProps) {
  const {
    slots,
    entries,
    showPrev,
    showNext,
    rootBind,
    listBind,
    prevBind,
    nextBind,
    prevLabel,
    nextLabel,
    getItemBind,
    prevIconBind,
    nextIconBind,
    getEllipsisBind,
  } = usePagination(props, paginationLibDefaults);

  return (
    <nav {...rootBind}>
      <ul {...listBind}>
        {showPrev ? (
          <li className="contents">
            <button {...prevBind}>
              {slots?.prev ?? (
                <>
                  <Icon icon="chevronLeft" {...prevIconBind} />
                  {prevLabel}
                </>
              )}
            </button>
          </li>
        ) : null}

        {entries.map((entry, index) => {
          if (entry.type === "ellipsis") {
            return (
              <li key={`ellipsis-${index}`} {...getEllipsisBind(index)}>
                {slots?.ellipsis ?? "…"}
              </li>
            );
          }

          return (
            <li className="contents" key={`page-${index}`}>
              <button {...getItemBind(entry.page)}>{entry.page}</button>
            </li>
          );
        })}

        {showNext ? (
          <li className="contents">
            <button {...nextBind}>
              {slots?.next ?? (
                <>
                  {nextLabel}
                  <Icon icon="chevronRight" {...nextIconBind} />
                </>
              )}
            </button>
          </li>
        ) : null}
      </ul>
    </nav>
  );
}

export default Pagination;

// packages/vue/src/Components/Pagination/Pagination.vue
<script setup lang="ts">
// ** Local Imports
import { Icon } from "@/Components/Icon";
import { usePagination } from "@/Components/Pagination/composables/usePagination";
import type {
  PaginationEmits,
  PaginationOwnProps,
  PaginationSlots,
} from "@/Components/Pagination/pagination.types";

defineSlots<PaginationSlots>();

const emit = defineEmits<PaginationEmits>();

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<PaginationOwnProps>(), {
  disabled: false,
  hideNextButton: false,
  hidePrevButton: false,
});

const model = defineModel<number>({ default: 1 });

const {
  entries,
  showPrev,
  showNext,
  rootBind,
  listBind,
  prevBind,
  nextBind,
  prevLabel,
  nextLabel,
  getItemBind,
  prevIconBind,
  nextIconBind,
  getEllipsisBind,
} = usePagination(
  props,
  {
    size: "md",
    rounded: "md",
    color: "dark",
    disabled: false,
    siblingCount: 1,
    variant: "ghost",
    mode: "numbered",
    boundaryCount: 1,
    hideNextButton: false,
    hidePrevButton: false,
  },
  model,
  emit,
);
</script>

<template>
  <nav v-bind="rootBind">
    <ul v-bind="listBind">
      <li v-if="showPrev" class="contents">
        <button v-bind="prevBind">
          <slot name="prev">
            <Icon icon="chevronLeft" v-bind="prevIconBind" />
            {{ prevLabel }}
          </slot>
        </button>
      </li>

      <template
        :key="`${entry.type}-${index}`"
        v-for="(entry, index) in entries"
      >
        <li v-bind="getEllipsisBind(index)" v-if="entry.type === 'ellipsis'">
          <slot name="ellipsis">…</slot>
        </li>

        <li v-else class="contents">
          <button v-bind="getItemBind(entry.page)">
            {{ entry.page }}
          </button>
        </li>
      </template>

      <li v-if="showNext" class="contents">
        <button v-bind="nextBind">
          <slot name="next">
            {{ nextLabel }}
            <Icon icon="chevronRight" v-bind="nextIconBind" />
          </slot>
        </button>
      </li>
    </ul>
  </nav>
</template>
