// packages/react/src/Components/BreadcrumbItem/BreadcrumbItem.tsx
// ** External Imports
import { createElement, Fragment } from "react";

// ** Local Imports
import type { BreadcrumbItemProps } from "@/Components/BreadcrumbItem/breadcrumbItem.types";
import { useBreadcrumbItem } from "@/Components/BreadcrumbItem/hooks/useBreadcrumbItem";
import { Icon } from "@/Components/Icon";
import { hasNamedSlot } from "@/Utils";

function BreadcrumbItem(props: BreadcrumbItemProps) {
  const {
    slots,
    merged,
    crumbAs,
    children,
    rootBind,
    linkBind,
    labelBind,
    endIconBind,
    startIconBind,
    separatorBind,
    separatorIcon,
    separatorContent,
  } = useBreadcrumbItem(props);

  return (
    <li {...rootBind}>
      {separatorContent != null ? (
        <span aria-hidden="true" data-slot="separator">
          {separatorContent}
        </span>
      ) : (
        <Icon icon={separatorIcon} {...separatorBind} />
      )}

      {createElement(
        crumbAs,
        linkBind,
        <Fragment>
          {hasNamedSlot(slots, "start") ? (
            slots?.start
          ) : (
            <Fragment>
              {merged.startIcon ? (
                <Icon icon={merged.startIcon} {...startIconBind} />
              ) : null}
            </Fragment>
          )}

          {merged.iconOnly && children != null ? (
            <span {...labelBind}>{children}</span>
          ) : (
            children
          )}

          {hasNamedSlot(slots, "end") ? (
            slots?.end
          ) : (
            <Fragment>
              {merged.endIcon ? (
                <Icon icon={merged.endIcon} {...endIconBind} />
              ) : null}
            </Fragment>
          )}
        </Fragment>,
      )}
    </li>
  );
}

export default BreadcrumbItem;

// packages/vue/src/Components/BreadcrumbItem/BreadcrumbItem.vue
<script setup lang="ts">
// ** Local Imports
import type {
  BreadcrumbItemOwnProps,
  BreadcrumbItemSlots,
} from "@/Components/BreadcrumbItem/breadcrumbItem.types";
import { useBreadcrumbItem } from "@/Components/BreadcrumbItem/composables/useBreadcrumbItem";
import { Icon } from "@/Components/Icon";
import { hasNamedSlot } from "@/Utils";

defineSlots<BreadcrumbItemSlots>();

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<BreadcrumbItemOwnProps>(), {
  current: false,
  disabled: false,
  iconOnly: false,
});

const {
  slots,
  merged,
  crumbAs,
  rootBind,
  linkBind,
  labelBind,
  endIconBind,
  startIconBind,
  separatorBind,
  separatorIcon,
  separatorContent,
} = useBreadcrumbItem(props);
</script>

<template>
  <li v-bind="rootBind">
    <span aria-hidden="true" data-slot="separator" v-if="separatorContent">
      <component :is="separatorContent" />
    </span>

    <Icon v-else :icon="separatorIcon" v-bind="separatorBind" />

    <component :is="crumbAs" v-bind="linkBind">
      <slot name="start" v-if="hasNamedSlot(slots, 'start')" />

      <Icon
        :icon="merged.startIcon"
        v-bind="startIconBind"
        v-else-if="merged.startIcon"
      />

      <span v-bind="labelBind" v-if="merged.iconOnly">
        <slot />
      </span>

      <slot v-else />

      <slot name="end" v-if="hasNamedSlot(slots, 'end')" />

      <Icon
        :icon="merged.endIcon"
        v-bind="endIconBind"
        v-else-if="merged.endIcon"
      />
    </component>
  </li>
</template>
