// packages/vue/src/Components/Select/Select.vue
<script setup lang="ts">
// ** External Imports
import { X } from "@lucide/vue";
import { provide, ref, useTemplateRef } from "vue";

// ** Local Imports
import { FormField } from "@/Components/FormField";
import { Icon } from "@/Components/Icon";
import { Listbox } from "@/Components/Listbox";
import { useSelect } from "@/Components/Select/composables/useSelect";
import type {
  SelectEmits,
  SelectOption,
  SelectOwnProps,
  SelectSlots,
  SelectValue,
} from "@/Components/Select/select.types";
import { SELECT_OPTION_KEY } from "@/Components/Select/selectInjectionKey";
import { hasNamedSlot, resolveNamedSlot } from "@/Utils";

defineSlots<SelectSlots>();

defineOptions({ inheritAttrs: false });

const model = defineModel<null | SelectValue | SelectValue[]>();

const props = withDefaults(defineProps<SelectOwnProps>(), {
  clearable: true,
  searchable: false,
  withErrorIcon: true,
  minItemsForSearch: 11,
  emptyMessage: "No options",
});

const emit = defineEmits<SelectEmits>();

const triggerRef = useTemplateRef<HTMLInputElement | HTMLTextAreaElement>(
  "trigger",
);

const declarativeOptions = ref<SelectOption[]>([]);

provide(SELECT_OPTION_KEY, {
  unregister(value) {
    declarativeOptions.value = declarativeOptions.value.filter(
      (item) => String(item.value) !== String(value),
    );
  },
  register(option) {
    if (
      declarativeOptions.value.some(
        (item) => String(item.value) === String(option.value),
      )
    ) {
      return;
    }

    declarativeOptions.value = [...declarativeOptions.value, option];
  },
});

const {
  open,
  slots,
  hasValue,
  multiple,
  listboxId,
  formField,
  isLoading,
  clearable,
  clearBind,
  isSelected,
  clearValue,
  removeChip,
  triggerBind,
  selectOption,
  containerRef,
  emptyMessage,
  clearIconSize,
  visibleOptions,
  selectedOptions,
  highlightedIndex,
  hideEmptyMessage,
} = useSelect(props, model, triggerRef, emit, declarativeOptions);
</script>

<template>
  <FormField :field="formField">
    <div
      v-if="multiple"
      class="flex min-w-0 flex-1 flex-wrap items-center gap-1"
    >
      <span
        :key="String(option.value)"
        v-for="option in selectedOptions"
        class="inline-flex max-w-full items-center gap-1 rounded-md bg-gray-100 px-2 py-0.5 text-sm text-gray-800 dark:bg-gray-700 dark:text-gray-100"
      >
        <slot name="chip" :option="option">
          <span class="truncate">{{ option.label }}</span>
        </slot>

        <span
          v-bind="clearBind"
          :aria-label="`Remove ${option.label}`"
          v-on:click="removeChip(option, $event)"
          v-on:keydown.enter.prevent="removeChip(option, $event)"
          v-on:keydown.space.prevent="removeChip(option, $event)"
        >
          <Icon :icon="X" :size="clearIconSize" />
        </span>
      </span>

      <textarea ref="trigger" v-bind="triggerBind" />
    </div>

    <div v-else class="flex min-w-0 flex-1 items-center gap-1">
      <input ref="trigger" class="min-w-0 flex-1" v-bind="triggerBind" />

      <span
        v-bind="clearBind"
        v-on:click="clearValue"
        aria-label="Clear selection"
        v-on:keydown.enter.prevent="clearValue"
        v-on:keydown.space.prevent="clearValue"
        v-if="clearable && hasValue && !formField.isDisabled.value"
      >
        <Icon :icon="X" :size="clearIconSize" />
      </span>
    </div>
  </FormField>

  <Listbox
    v-model="open"
    :loading="isLoading"
    :multiple="multiple"
    :listbox-id="listboxId"
    :anchor-el="containerRef"
    :options="visibleOptions"
    :is-selected="isSelected"
    v-on:select="selectOption"
    :disable-auto-focus="true"
    :empty-message="emptyMessage"
    :max-height="props.maxHeight"
    :color="formField.merged.value.color"
    :highlighted-index="highlightedIndex"
    :hide-empty-message="hideEmptyMessage"
    :labelled-by="formField.controlId.value"
    :invalidated="formField.invalidated.value"
    :disable-max-height="props.disableMaxHeight"
  >
    <template #beforeOptions v-if="hasNamedSlot(slots, 'beforeOptions')">
      <component :is="resolveNamedSlot(slots, 'beforeOptions')" />
    </template>

    <template #loading v-if="hasNamedSlot(slots, 'loading')">
      <component :is="resolveNamedSlot(slots, 'loading')" />
    </template>

    <template #option="slotProps" v-if="hasNamedSlot(slots, 'option')">
      <slot name="option" v-bind="slotProps" />
    </template>

    <template #empty v-if="hasNamedSlot(slots, 'empty')">
      <component :is="resolveNamedSlot(slots, 'empty')" />
    </template>

    <template #afterOptions v-if="hasNamedSlot(slots, 'afterOptions')">
      <component :is="resolveNamedSlot(slots, 'afterOptions')" />
    </template>
  </Listbox>

  <slot />
</template>

// packages/react/src/Components/Select/Select.tsx
// ** External Imports
import { X } from "lucide-react";
import type { InputHTMLAttributes, TextareaHTMLAttributes } from "react";
import { useRef } from "react";

// ** Local Imports
import { FormField } from "@/Components/FormField";
import { Icon } from "@/Components/Icon";
import { Listbox } from "@/Components/Listbox";
import { useSelect } from "@/Components/Select/hooks/useSelect";
import type { SelectProps } from "@/Components/Select/select.types";

function Select(props: SelectProps) {
  const triggerRef = useRef<HTMLInputElement | HTMLTextAreaElement | null>(
    null,
  );

  const { maxHeight, disableMaxHeight, ...selectProps } = props;

  const setTriggerRef = (
    element: HTMLInputElement | HTMLTextAreaElement | null,
  ) => {
    triggerRef.current = element;
  };

  const {
    open,
    slots,
    hasValue,
    multiple,
    listboxId,
    formField,
    isLoading,
    clearable,
    clearBind,
    isSelected,
    clearValue,
    removeChip,
    triggerBind,
    selectOption,
    containerRef,
    emptyMessage,
    clearIconSize,
    visibleOptions,
    selectedOptions,
    highlightedIndex,
    hideEmptyMessage,
    handleOpenChange,
  } = useSelect(selectProps, triggerRef);

  return (
    <>
      <FormField field={formField}>
        {multiple ? (
          <div className="flex min-w-0 flex-1 flex-wrap items-center gap-1">
            {selectedOptions.map((option) => (
              <span
                key={String(option.value)}
                className="inline-flex max-w-full items-center gap-1 rounded-md bg-gray-100 px-2 py-0.5 text-sm text-gray-800 dark:bg-gray-700 dark:text-gray-100"
              >
                {slots?.chip ? (
                  slots.chip({ option })
                ) : (
                  <span className="truncate">{option.label}</span>
                )}

                <span
                  {...clearBind}
                  aria-label={`Remove ${option.label}`}
                  onClick={(event) => removeChip(option, event)}
                  onKeyDown={(event) => {
                    if (event.key === "Enter" || event.key === " ") {
                      event.preventDefault();
                      removeChip(option, event);
                    }
                  }}
                >
                  <Icon icon={X} size={clearIconSize} />
                </span>
              </span>
            ))}

            <textarea
              ref={setTriggerRef}
              {...(triggerBind as TextareaHTMLAttributes<HTMLTextAreaElement>)}
            />
          </div>
        ) : (
          <div className="flex min-w-0 flex-1 items-center gap-1">
            <input
              ref={setTriggerRef}
              {...(triggerBind as InputHTMLAttributes<HTMLInputElement>)}
            />

            {clearable && hasValue && !formField.isDisabled ? (
              <span
                {...clearBind}
                aria-label="Clear selection"
                onClick={() => clearValue()}
                onKeyDown={(event) => {
                  if (event.key === "Enter" || event.key === " ") {
                    event.preventDefault();
                    clearValue();
                  }
                }}
              >
                <Icon icon={X} size={clearIconSize} />
              </span>
            ) : null}
          </div>
        )}
      </FormField>

      <Listbox
        show={open}
        disableAutoFocus
        loading={isLoading}
        multiple={multiple}
        listboxId={listboxId}
        maxHeight={maxHeight}
        anchorEl={containerRef}
        onSelect={selectOption}
        isSelected={isSelected}
        options={visibleOptions}
        emptyMessage={emptyMessage}
        color={formField.merged.color}
        onShowChange={handleOpenChange}
        labelledBy={formField.controlId}
        invalidated={formField.invalidated}
        disableMaxHeight={disableMaxHeight}
        highlightedIndex={highlightedIndex}
        hideEmptyMessage={hideEmptyMessage}
        slots={{
          empty: slots?.empty,
          option: slots?.option,
          loading: slots?.loading,
          afterOptions: slots?.afterOptions,
          beforeOptions: slots?.beforeOptions,
        }}
      />
    </>
  );
}

export default Select;
