// packages/react/src/Components/ChartBar/ChartBar.tsx
// ** Local Imports
import type { ChartBarProps } from "@/Components/ChartBar/chartBar.types";
import { useChartBar } from "@/Components/ChartBar/hooks/useChartBar";
import { ChartFrame } from "@/Utils/Charts";

function ChartBar(props: ChartBarProps) {
  const { frame, context } = useChartBar(props, {
    radius: 4,
    size: "md",
    height: 280,
    labels: false,
    animation: true,
    orientation: "vertical",
  });

  return (
    <ChartFrame frame={frame} context={context}>
      {props.children}
    </ChartFrame>
  );
}

export default ChartBar;

// packages/vue/src/Components/ChartBar/ChartBar.vue
<script setup lang="ts">
// ** Local Imports
import type { ChartBarOwnProps } from "@/Components/ChartBar/chartBar.types";
import { useChartBar } from "@/Components/ChartBar/composables/useChartBar";
import { ChartFrame, type ChartSlots } from "@/Utils/Charts";

defineSlots<ChartSlots>();

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<ChartBarOwnProps>(), {
  loading: false,
  labels: undefined,
  animation: undefined,
});

const { frame } = useChartBar(props, {
  radius: 4,
  size: "md",
  height: 280,
  labels: false,
  animation: true,
  orientation: "vertical",
});
</script>

<template>
  <ChartFrame :frame="frame">
    <slot />
    <template #empty v-if="$slots.empty"><slot name="empty" /></template>
    <template #loading v-if="$slots.loading"><slot name="loading" /></template>
  </ChartFrame>
</template>
