// packages/vue/src/Components/DataTable/DataTableSelection.vue
<script setup lang="ts">
// ** External Imports
import { computed } from "vue";

// ** Local Imports
import { useResolveMessage } from "@/Adapters/I18n";
import { Checkbox } from "@/Components/Checkbox";
import type { CheckboxProps } from "@/Components/Checkbox/checkbox.types";
import type { DataTableCustomProps } from "@/Components/DataTable/dataTable.types";
import { Radio } from "@/Components/Radio";

defineOptions({ inheritAttrs: false, name: "DataTableSelection" });

const props = defineProps<{
  checkboxProps?: DataTableCustomProps["checkbox"];
  checked: boolean;
  indeterminate?: boolean;
  kind: "row" | "page";
  multiple?: boolean;
  name?: string;
  radioProps?: DataTableCustomProps["radio"];
  size: CheckboxProps["size"];
  value?: string;
}>();

const emit = defineEmits<{
  change: [checked: boolean];
}>();

const resolveMessage = useResolveMessage();

const ariaLabel = computed(() => {
  if (props.kind === "page") {
    return resolveMessage("Select all rows");
  }

  return resolveMessage("Select row");
});
</script>

<template>
  <Checkbox
    :size="size"
    hide-error-message
    :model-value="checked"
    :aria-label="ariaLabel"
    :indeterminate="indeterminate"
    v-bind="checkboxProps"
    v-if="kind === 'page' || multiple"
    v-on:update:model-value="(checked) => emit('change', Boolean(checked))"
  />

  <Radio
    v-else
    :size="size"
    :name="name"
    :value="value"
    hide-error-message
    :aria-label="ariaLabel"
    v-bind="radioProps"
    :model-value="checked ? value : ''"
    v-on:update:model-value="() => emit('change', true)"
  />
</template>

// packages/react/src/Components/DataTable/DataTableSelection.tsx
// ** Local Imports
import { useResolveMessage } from "@/Adapters/I18n";
import { Checkbox } from "@/Components/Checkbox";
import type { CheckboxProps } from "@/Components/Checkbox/checkbox.types";
import type { DataTableCustomProps } from "@/Components/DataTable/dataTable.types";
import { Radio } from "@/Components/Radio";
import { derived } from "@/Utils";

/**
 * Internal row / page selection control. Not part of the public API.
 */
export function DataTableSelection({
  kind,
  name,
  size,
  value,
  checked,
  multiple,
  onChange,
  radioProps,
  checkboxProps,
  indeterminate,
}: {
  checkboxProps?: DataTableCustomProps["checkbox"];
  checked: boolean;
  indeterminate?: boolean;
  kind: "row" | "page";
  multiple?: boolean;
  name?: string;
  onChange: (checked: boolean) => void;
  radioProps?: DataTableCustomProps["radio"];
  size: CheckboxProps["size"];
  value?: string;
}) {
  const resolveMessage = useResolveMessage();

  const ariaLabel = derived(() => {
    if (kind === "page") {
      return resolveMessage("Select all rows");
    }

    return resolveMessage("Select row");
  });

  if (kind === "page" || multiple) {
    return (
      <Checkbox
        size={size}
        hideErrorMessage
        checked={checked}
        aria-label={ariaLabel}
        indeterminate={indeterminate}
        {...checkboxProps}
        onChange={(event) => {
          onChange(event.currentTarget.checked);
        }}
      />
    );
  }

  return (
    <Radio
      size={size}
      name={name}
      value={value}
      hideErrorMessage
      checked={checked}
      aria-label={ariaLabel}
      {...radioProps}
      onChange={() => {
        onChange(true);
      }}
    />
  );
}
