// packages/react/src/Components/Sidebar/SidebarTrigger.tsx
// ** Local Imports
import { Button } from "@/Components/Button";
import { useSidebarTrigger } from "@/Components/Sidebar/hooks/useSidebarTrigger";
import type { SidebarTriggerProps } from "@/Components/Sidebar/sidebar.types";

function SidebarTrigger(props: SidebarTriggerProps) {
  const { side, panelId, children, expanded, handleClick, rootInheritedAttrs } =
    useSidebarTrigger(props);

  return (
    <Button
      {...rootInheritedAttrs}
      color="dark"
      type="button"
      density="mini"
      variant="light"
      onClick={handleClick}
      aria-expanded={expanded}
      aria-controls={panelId || undefined}
      icon={children ? undefined : "chevronLeft"}
      aria-label={props["aria-label"] ?? "Toggle sidebar"}
      classes={{
        icon: side === "right" ? "rotate-180 rtl:rotate-0" : "rtl:rotate-180",
      }}
    >
      {children}
    </Button>
  );
}

export default SidebarTrigger;

// packages/vue/src/Components/Sidebar/SidebarTrigger.vue
<script setup lang="ts">
// ** External Imports
import { useSlots } from "vue";

// ** Local Imports
import { Button } from "@/Components/Button";
import { useSidebarTrigger } from "@/Components/Sidebar/composables/useSidebarTrigger";
import type {
  SidebarTriggerOwnProps,
  SidebarTriggerSlots,
} from "@/Components/Sidebar/sidebar.types";

defineSlots<SidebarTriggerSlots>();

defineOptions({ inheritAttrs: false });

defineProps<SidebarTriggerOwnProps>();

const slots = useSlots();

const {
  attrs,
  panelId,
  expanded,
  iconClass,
  ariaLabel,
  handleClick,
  hasDefaultSlot,
} = useSidebarTrigger(slots);
</script>

<template>
  <Button
    v-bind="attrs"
    color="dark"
    type="button"
    density="mini"
    variant="light"
    :aria-label="ariaLabel"
    v-on:click="handleClick"
    :aria-expanded="expanded"
    :classes="{ icon: iconClass }"
    :aria-controls="panelId || undefined"
    :icon="hasDefaultSlot ? undefined : 'chevronLeft'"
  >
    <slot v-if="hasDefaultSlot" />
  </Button>
</template>
