// packages/react/src/Components/FileUpload/FileUploadItem.tsx
// ** External Imports
import { isNil } from "es-toolkit/compat";

// ** Core Imports
import { cn } from "@bridge-ui/core/Utils";

// ** Local Imports
import { Button } from "@/Components/Button";
import { useFileUploadItemContext } from "@/Components/FileUpload/FileUploadContext";
import type { FileUploadItemProps } from "@/Components/FileUpload/fileUpload.types";
import { Icon } from "@/Components/Icon";

function FileUploadItem({
  slots,
  index,
  value,
  remove,
  isImage,
  className,
  metaLabel,
  previewUrl,
  sizeLabel: _sizeLabel,
  ...props
}: FileUploadItemProps) {
  const context = useFileUploadItemContext();
  const itemBind = context.getItemBind(index);
  const start = slots?.start;
  const end = slots?.end;

  return (
    <li {...itemBind} {...props} className={cn(itemBind.className, className)}>
      {isNil(start) ? null : (
        <div className="flex shrink-0 items-center">{start}</div>
      )}

      <div {...context.mediaBind}>
        {isImage && previewUrl ? (
          <img alt="" src={previewUrl} />
        ) : (
          <Icon icon="download" />
        )}
      </div>

      <div {...context.contentBind}>
        <p {...context.titleBind}>{value.name}</p>

        <p {...context.descriptionBind}>{metaLabel}</p>
      </div>

      <div {...context.actionsBind}>
        {isNil(end) ? (
          <Button
            size="sm"
            icon="clear"
            type="button"
            variant="flat"
            density="mini"
            onClick={remove}
            color={context.color}
            rounded={context.rounded}
            disabled={context.disabled}
            aria-label={`Remove ${value.name}`}
          />
        ) : (
          end
        )}
      </div>
    </li>
  );
}

export default FileUploadItem;

// packages/vue/src/Components/FileUpload/FileUploadItem.vue
<script setup lang="ts">
// ** External Imports
import { computed, inject, useSlots } from "vue";

// ** Local Imports
import { Button } from "@/Components/Button";
import type {
  FileUploadItemSlotProps,
  FileUploadItemSlots,
} from "@/Components/FileUpload/fileUpload.types";
import { FILE_UPLOAD_KEY } from "@/Components/FileUpload/fileUploadInjectionKey";
import { Icon } from "@/Components/Icon";
import { hasNamedSlot } from "@/Utils";

defineOptions({ inheritAttrs: false });

defineSlots<FileUploadItemSlots>();

const props = defineProps<FileUploadItemSlotProps>();

const slots = useSlots();

const context = inject(FILE_UPLOAD_KEY);

if (!context) {
  throw new Error("FileUploadItem must be used within FileUpload");
}

const itemBind = computed(() => {
  return context.value.getItemBind(props.index);
});
</script>

<template>
  <li v-bind="itemBind">
    <div class="flex shrink-0 items-center" v-if="hasNamedSlot(slots, 'start')">
      <slot name="start" v-bind="props" />
    </div>

    <div v-bind="context.mediaBind">
      <img alt="" :src="previewUrl" v-if="isImage && previewUrl" />

      <Icon v-else icon="download" />
    </div>

    <div v-bind="context.contentBind">
      <p v-bind="context.titleBind">{{ value.name }}</p>

      <p v-bind="context.descriptionBind">{{ metaLabel }}</p>
    </div>

    <div v-bind="context.actionsBind">
      <slot name="end" v-bind="props" v-if="hasNamedSlot(slots, 'end')" />

      <Button
        v-else
        size="sm"
        icon="clear"
        type="button"
        variant="flat"
        density="mini"
        v-on:click="remove"
        :color="context.color"
        :rounded="context.rounded"
        :disabled="context.disabled"
        :aria-label="`Remove ${value.name}`"
      />
    </div>
  </li>
</template>
