// packages/react/src/Components/Toggle/Toggle.tsx
// ** Local Imports
import { Switcher } from "@/Components/Switcher";
import { useToggle } from "@/Components/Toggle/hooks/useToggle";
import type { ToggleProps } from "@/Components/Toggle/toggle.types";

function Toggle(props: ToggleProps) {
  const { switcher, fieldBind, inputBind, thumbBind, trackBind } = useToggle(
    props,
    {
      size: "md",
      rounded: "full",
      color: "primary",
    },
  );

  return (
    <Switcher field={switcher}>
      <label htmlFor={switcher.controlId} {...fieldBind}>
        <input {...inputBind} />

        <span {...trackBind} />

        <span {...thumbBind} />
      </label>
    </Switcher>
  );
}

export default Toggle;

// packages/vue/src/Components/Toggle/Toggle.vue
<script setup lang="ts">
// ** External Imports
import { computed, useAttrs } from "vue";

// ** Local Imports
import { Switcher } from "@/Components/Switcher";
import { useToggle } from "@/Components/Toggle/composables/useToggle";
import type {
  ToggleOwnProps,
  ToggleSlots,
} from "@/Components/Toggle/toggle.types";

const attrs = useAttrs();

defineSlots<ToggleSlots>();

defineOptions({ inheritAttrs: false });

const props = defineProps<ToggleOwnProps>();

const model = defineModel<boolean>({ default: false });

const checked = computed(() => {
  return model.value;
});

const { switcher, fieldBind, inputBind, thumbBind, trackBind } = useToggle(
  () => ({ ...attrs, ...props }),
  {
    size: "sm",
    rounded: "full",
    color: "primary",
  },
  checked,
);

function onChange(event: Event) {
  const target = event.target as HTMLInputElement;

  model.value = target.checked;
}
</script>

<template>
  <Switcher :field="switcher">
    <label v-bind="fieldBind">
      <input v-bind="inputBind" :checked="model" v-on:change="onChange" />

      <span v-bind="trackBind" />

      <span v-bind="thumbBind" />
    </label>
  </Switcher>
</template>
