// packages/vue/src/Components/BaseField/BaseField.vue
<script setup lang="ts">
// ** External Imports
import { computed } from "vue";

// ** Local Imports
import BaseFieldLabel from "@/Components/BaseField/BaseFieldLabel.vue";
import type { UseBaseFieldReturn } from "@/Components/BaseField/composables/useBaseField";
import {
  hasNamedSlot,
  hasSlotOrProp,
  resolveNamedSlot,
  resolveSlotOrProp,
} from "@/Utils";

defineOptions({ inheritAttrs: false });

const props = defineProps<{
  field: UseBaseFieldReturn;
}>();

const api = computed((): UseBaseFieldReturn => {
  return props.field;
});

const showHeader = computed(() => {
  return (
    hasSlotOrProp(api.value.slots, "label", api.value.merged.value.label) ||
    hasSlotOrProp(api.value.slots, "corner", api.value.merged.value.corner)
  );
});
</script>

<template>
  <div
    v-bind="api.rootBind.value"
    :data-invalid="api.invalidated.value || undefined"
    :aria-disabled="api.isDisabled.value || undefined"
    :aria-readonly="api.isReadonly.value || undefined"
  >
    <div v-if="showHeader" v-bind="api.headerBind.value">
      <BaseFieldLabel :api="api" />

      <span
        v-bind="api.cornerBind.value"
        v-if="hasSlotOrProp(api.slots, 'corner', api.merged.value.corner)"
      >
        <component
          :is="resolveSlotOrProp(api.slots, 'corner', api.merged.value.corner)"
        />
      </span>
    </div>

    <div v-bind="api.groupBind.value">
      <div
        v-bind="api.startSlotBind.value"
        v-if="hasNamedSlot(api.slots, 'start')"
      >
        <component :is="resolveNamedSlot(api.slots, 'start')" />
      </div>

      <slot />

      <div v-bind="api.endSlotBind.value" v-if="hasNamedSlot(api.slots, 'end')">
        <component :is="resolveNamedSlot(api.slots, 'end')" />
      </div>
    </div>

    <p
      v-bind="api.descriptionBind.value"
      :id="`${api.controlId.value}-description`"
      v-if="
        !api.invalidated.value &&
        hasSlotOrProp(api.slots, 'description', api.merged.value.description)
      "
    >
      <component
        :is="
          resolveSlotOrProp(
            api.slots,
            'description',
            api.merged.value.description,
          )
        "
      />
    </p>

    <p
      v-bind="api.errorBind.value"
      :id="`${api.controlId.value}-error`"
      v-if="!api.merged.value.hideErrorMessage"
      :aria-hidden="api.showErrorMessageContent.value ? undefined : true"
    >
      <component
        v-if="api.showErrorMessageContent.value"
        :is="
          resolveSlotOrProp(
            api.slots,
            'errorMessage',
            api.merged.value.errorMessage,
          )
        "
      />
    </p>
  </div>
</template>

// packages/react/src/Components/BaseField/BaseField.tsx
// ** External Imports
import type { ReactNode } from "react";

// ** Local Imports
import BaseFieldLabel from "@/Components/BaseField/BaseFieldLabel";
import type { UseBaseFieldReturn } from "@/Components/BaseField/hooks/useBaseField";
import { hasNamedSlot, hasSlotOrProp } from "@/Utils";

type BaseFieldComponentProps = {
  children?: ReactNode;
  field: UseBaseFieldReturn;
};

function BaseField({ field, children }: BaseFieldComponentProps) {
  const {
    slots,
    merged,
    rootBind,
    errorBind,
    groupBind,
    controlId,
    headerBind,
    cornerBind,
    endSlotBind,
    invalidated,
    startSlotBind,
    descriptionBind,
    showErrorMessageContent,
  } = field;

  const showHeader =
    hasSlotOrProp(slots, "label", merged.label) ||
    hasSlotOrProp(slots, "corner", merged.corner);

  return (
    <div
      {...rootBind}
      data-invalid={invalidated || undefined}
      aria-disabled={merged.disabled || undefined}
      aria-readonly={merged.readonly || undefined}
    >
      {showHeader && (
        <div {...headerBind}>
          <BaseFieldLabel field={field} />

          {hasSlotOrProp(slots, "corner", merged.corner) && (
            <span {...cornerBind}>
              {hasNamedSlot(slots, "corner") ? slots?.corner : merged.corner}
            </span>
          )}
        </div>
      )}

      <div {...groupBind}>
        {hasNamedSlot(slots, "start") && (
          <div {...startSlotBind}>{slots?.start}</div>
        )}

        {children}

        {hasNamedSlot(slots, "end") && <div {...endSlotBind}>{slots?.end}</div>}
      </div>

      {!invalidated &&
        hasSlotOrProp(slots, "description", merged.description) && (
          <p {...descriptionBind} id={`${controlId}-description`}>
            {hasNamedSlot(slots, "description")
              ? slots?.description
              : merged.description}
          </p>
        )}

      {!merged.hideErrorMessage && (
        <p
          {...errorBind}
          id={`${controlId}-error`}
          aria-hidden={showErrorMessageContent ? undefined : true}
        >
          {showErrorMessageContent &&
            (hasNamedSlot(slots, "errorMessage")
              ? slots?.errorMessage
              : merged.errorMessage)}
        </p>
      )}
    </div>
  );
}

export default BaseField;
