// packages/vue/src/Components/BaseField/BaseFieldCorner.vue
<script setup lang="ts">
// ** External Imports
import { useSlots } from "vue";

// ** Local Imports
import type { UseBaseFieldReturn } from "@/Components/BaseField/composables/useBaseField";
import { Label } from "@/Components/Label";
import { hasNamedSlot, hasSlotOrProp } from "@/Utils";

defineProps<{
  api: UseBaseFieldReturn;
}>();

const slots = useSlots();
</script>

<template>
  <Label
    v-bind="api.fieldCornerProps.value"
    v-if="hasSlotOrProp(slots, 'corner', api.merged.value.corner)"
  >
    <slot name="corner" v-if="hasNamedSlot(slots, 'corner')" />

    <template v-else>{{ api.merged.value.corner }}</template>
  </Label>
</template>

// packages/react/src/Components/BaseField/BaseFieldCorner.tsx
// ** Local Imports
import type { UseBaseFieldReturn } from "@/Components/BaseField/hooks/useBaseField";
import { Label } from "@/Components/Label";
import { hasNamedSlot, hasSlotOrProp } from "@/Utils";

type BaseFieldCornerProps = {
  field: UseBaseFieldReturn;
};

/**
 * Renders the BaseField corner via `Label` for the string prop and named slots.
 */
function BaseFieldCorner({ field }: BaseFieldCornerProps) {
  if (!hasSlotOrProp(field.slots, "corner", field.merged.corner)) {
    return null;
  }

  const content = hasNamedSlot(field.slots, "corner")
    ? field.slots?.corner
    : field.merged.corner;

  return <Label {...field.fieldCornerProps}>{content}</Label>;
}

export default BaseFieldCorner;
