// packages/vue/src/Components/BaseField/BaseFieldLabel.vue
<script setup lang="ts">
// ** Local Imports
import type { UseBaseFieldReturn } from "@/Components/BaseField/composables/useBaseField";
import { Label } from "@/Components/Label";
import {
  hasNamedSlot,
  hasSlotOrProp,
  isPropPresent,
  SlotOrProp,
} from "@/Utils";

defineProps<{
  api: UseBaseFieldReturn;
}>();
</script>

<template>
  <Label
    v-bind="api.fieldLabelProps.value"
    v-if="hasSlotOrProp(api.slots, 'label', api.merged.value.label)"
  >
    <SlotOrProp
      name="label"
      :slots="api.slots"
      v-if="hasNamedSlot(api.slots, 'label')"
    />

    <template v-else-if="isPropPresent(api.merged.value.label)">
      {{ api.merged.value.label }}
    </template>
  </Label>
</template>

// packages/react/src/Components/BaseField/BaseFieldLabel.tsx
// ** Local Imports
import type { UseBaseFieldReturn } from "@/Components/BaseField/hooks/useBaseField";
import { Label } from "@/Components/Label";
import {
  hasNamedSlot,
  hasSlotOrProp,
  isPropPresent,
  resolveSlotOrProp,
} from "@/Utils";

type BaseFieldLabelProps = {
  field: UseBaseFieldReturn;
};

/**
 * Renders the BaseField label via `Label` for the string prop and named slots.
 */
function BaseFieldLabel({ field }: BaseFieldLabelProps) {
  if (!hasSlotOrProp(field.slots, "label", field.merged.label)) {
    return null;
  }

  const content = hasNamedSlot(field.slots, "label")
    ? resolveSlotOrProp({
        name: "label",
        slots: field.slots,
        fallback: field.merged.label,
      })
    : isPropPresent(field.merged.label)
      ? field.merged.label
      : null;

  if (content === null) {
    return null;
  }

  return <Label {...field.fieldLabelProps}>{content}</Label>;
}

export default BaseFieldLabel;
