// packages/react/src/Actions/BridgeUIHosts.tsx
// ** Local Imports
import type { BridgeUIHostsProps } from "@/Actions/bridgeUIHosts.types";
import { BridgeDialogHost } from "@/Actions/Dialog";
import { BridgeDrawerHost } from "@/Actions/Drawer";
import { BridgeModalHost } from "@/Actions/Modal";
import { BridgeSnackbarHost } from "@/Actions/Snackbar";

/**
 * Convenience wrapper that mounts snackbar, dialog, modal, and drawer hosts.
 * Use when the app needs `useSnackbarAction()`, `useDialogAction()`, `useModalAction()`, and/or `useDrawerAction()`.
 */
export function BridgeUIHosts({
  modal,
  dialog,
  drawer,
  children,
  snackbar,
}: BridgeUIHostsProps) {
  return (
    <BridgeModalHost {...modal}>
      <BridgeDrawerHost {...drawer}>
        <BridgeDialogHost {...dialog}>
          <BridgeSnackbarHost {...snackbar}>{children}</BridgeSnackbarHost>
        </BridgeDialogHost>
      </BridgeDrawerHost>
    </BridgeModalHost>
  );
}

// packages/vue/src/Actions/BridgeUIHosts.vue
<script setup lang="ts">
// ** Local Imports
import type { BridgeUIHostsProps } from "@/Actions/bridgeUIHosts.types";
import { BridgeDialogHost } from "@/Actions/Dialog";
import { BridgeDrawerHost } from "@/Actions/Drawer";
import { BridgeModalHost } from "@/Actions/Modal";
import { BridgeSnackbarHost } from "@/Actions/Snackbar";

withDefaults(defineProps<BridgeUIHostsProps>(), {
  modal: () => ({}),
  dialog: () => ({}),
  drawer: () => ({}),
  snackbar: () => ({}),
});
</script>

<template>
  <BridgeModalHost v-bind="modal">
    <BridgeDrawerHost v-bind="drawer">
      <BridgeDialogHost v-bind="dialog">
        <BridgeSnackbarHost v-bind="snackbar">
          <slot />
        </BridgeSnackbarHost>
      </BridgeDialogHost>
    </BridgeDrawerHost>
  </BridgeModalHost>
</template>
