// packages/vue/src/Components/Calendar/Calendar.vue
<script setup lang="ts">
// ** Local Imports
import type {
  CalendarEmits,
  CalendarOwnProps,
} from "@/Components/Calendar/calendar.types";
import { useCalendar } from "@/Components/Calendar/composables/useCalendar";
import CalendarDate from "@/Components/CalendarDate/CalendarDate.vue";
import CalendarMonth from "@/Components/CalendarMonth/CalendarMonth.vue";
import CalendarYear from "@/Components/CalendarYear/CalendarYear.vue";
import { Icon } from "@/Components/Icon";

defineOptions({ inheritAttrs: false });

const props = defineProps<CalendarOwnProps>();

const emit = defineEmits<CalendarEmits>();

const {
  view,
  value,
  merged,
  shared,
  rootBind,
  viewDate,
  viewYear,
  viewMonth,
  yearLabel,
  monthLabel,
  headerBind,
  navIconBind,
  setViewDate,
  showDateNav,
  handleChange,
  nextButtonBind,
  todayButtonBind,
  yearSelectorBind,
  handleYearSelect,
  showYearSelector,
  monthSelectorBind,
  handleMonthSelect,
  showMonthSelector,
  previousButtonBind,
} = useCalendar(
  props,
  { startOfWeek: 0, color: "primary", defaultView: "date" },
  emit,
);
</script>

<template>
  <div v-bind="rootBind">
    <div v-bind="headerBind">
      <div class="flex min-w-0 items-center gap-1">
        <button v-if="showYearSelector" v-bind="yearSelectorBind">
          <span>{{ yearLabel }}</span>
          <Icon size="xs" icon="chevronDown" v-bind="navIconBind" />
        </button>

        <button v-if="showMonthSelector" v-bind="monthSelectorBind">
          <span class="underline decoration-gray-300 underline-offset-4">
            {{ monthLabel }}
          </span>
          <Icon size="xs" icon="chevronDown" v-bind="navIconBind" />
        </button>
      </div>

      <div v-if="showDateNav" class="flex items-center gap-0.5">
        <button v-bind="previousButtonBind">
          <Icon size="sm" icon="chevronLeft" v-bind="navIconBind" />
        </button>

        <button v-bind="todayButtonBind">
          <span
            class="block h-2.5 w-2.5 rounded-full bg-gray-700 dark:bg-gray-200"
          />
        </button>

        <button v-bind="nextButtonBind">
          <Icon size="sm" icon="chevronRight" v-bind="navIconBind" />
        </button>
      </div>
    </div>

    <CalendarDate
      v-bind="shared"
      :value="value"
      :range="merged.range"
      :view-date="viewDate"
      v-if="view === 'date'"
      @change="handleChange"
      :multiple="merged.multiple"
      @view-date-change="setViewDate"
      :start-of-week="merged.startOfWeek"
      :disable-dates="merged.disableDates"
      :hide-weekdays="merged.hideWeekdays"
    />

    <CalendarMonth
      v-bind="shared"
      :year="viewYear"
      :value="viewMonth"
      @change="handleMonthSelect"
      v-else-if="view === 'month'"
    />

    <CalendarYear
      v-bind="shared"
      :value="viewYear"
      @change="handleYearSelect"
      v-else-if="view === 'year'"
    />
  </div>
</template>

// packages/react/src/Components/Calendar/Calendar.tsx
// ** Local Imports
import type { CalendarProps } from "@/Components/Calendar/calendar.types";
import { useCalendar } from "@/Components/Calendar/hooks/useCalendar";
import { CalendarDate } from "@/Components/CalendarDate";
import { CalendarMonth } from "@/Components/CalendarMonth";
import { CalendarYear } from "@/Components/CalendarYear";
import { Icon } from "@/Components/Icon";

function Calendar(props: CalendarProps) {
  const {
    view,
    value,
    merged,
    rootBind,
    viewDate,
    viewYear,
    viewMonth,
    yearLabel,
    monthLabel,
    headerBind,
    navIconBind,
    setViewDate,
    showDateNav,
    handleChange,
    nextButtonBind,
    todayButtonBind,
    yearSelectorBind,
    handleYearSelect,
    showYearSelector,
    monthSelectorBind,
    handleMonthSelect,
    showMonthSelector,
    previousButtonBind,
  } = useCalendar(props, {
    startOfWeek: 0,
    color: "primary",
    defaultView: "date",
  });

  const shared = {
    color: merged.color,
    locale: merged.locale,
    tokens: merged.tokens,
    maxDate: merged.maxDate,
    minDate: merged.minDate,
    disabled: merged.disabled,
    readOnly: merged.readOnly,
    timeZone: merged.timeZone,
    disableYears: merged.disableYears,
    disableMonths: merged.disableMonths,
  };

  return (
    <div {...rootBind}>
      <div {...headerBind}>
        <div className="flex min-w-0 items-center gap-1">
          {showYearSelector && (
            <button {...yearSelectorBind}>
              <span>{yearLabel}</span>
              <Icon size="xs" icon="chevronDown" {...navIconBind} />
            </button>
          )}

          {showMonthSelector && (
            <button {...monthSelectorBind}>
              <span className="underline decoration-gray-300 underline-offset-4">
                {monthLabel}
              </span>
              <Icon size="xs" icon="chevronDown" {...navIconBind} />
            </button>
          )}
        </div>

        {showDateNav && (
          <div className="flex items-center gap-0.5">
            <button {...previousButtonBind}>
              <Icon size="sm" icon="chevronLeft" {...navIconBind} />
            </button>

            <button {...todayButtonBind}>
              <span className="block h-2.5 w-2.5 rounded-full bg-gray-700 dark:bg-gray-200" />
            </button>

            <button {...nextButtonBind}>
              <Icon size="sm" icon="chevronRight" {...navIconBind} />
            </button>
          </div>
        )}
      </div>

      {view === "date" && (
        <CalendarDate
          {...shared}
          value={value}
          viewDate={viewDate}
          range={merged.range}
          onChange={handleChange}
          multiple={merged.multiple}
          onViewDateChange={setViewDate}
          startOfWeek={merged.startOfWeek}
          disableDates={merged.disableDates}
          hideWeekdays={merged.hideWeekdays}
        />
      )}

      {view === "month" && (
        <CalendarMonth
          {...shared}
          year={viewYear}
          value={viewMonth}
          onChange={handleMonthSelect}
        />
      )}

      {view === "year" && (
        <CalendarYear
          {...shared}
          value={viewYear}
          onChange={handleYearSelect}
        />
      )}
    </div>
  );
}

export default Calendar;
