// packages/vue/src/Components/Table/TableFooter.vue
<script setup lang="ts">
// ** Local Imports
import { useTablePart } from "@/Components/Table/composables/useTablePart";
import type {
  TableFooterOwnProps,
  TableFooterSlots,
} from "@/Components/Table/table.types";

defineSlots<TableFooterSlots>();

defineOptions({ inheritAttrs: false });

const props = defineProps<TableFooterOwnProps>();

const { rootBind } = useTablePart(props, "footer");
</script>

<template>
  <tfoot v-bind="rootBind">
    <slot />
  </tfoot>
</template>

// packages/react/src/Components/Table/TableFooter.tsx
// ** Local Imports
import { TableSectionContext } from "@/Components/Table/TableContext";
import { useTablePart } from "@/Components/Table/hooks/useTablePart";
import type { TableFooterProps } from "@/Components/Table/table.types";

function TableFooter(props: TableFooterProps) {
  const { children, rootBind } = useTablePart(props, "footer");

  return (
    <TableSectionContext.Provider value="footer">
      <tfoot {...rootBind}>{children}</tfoot>
    </TableSectionContext.Provider>
  );
}

export default TableFooter;
