// packages/vue/src/Components/Table/TableCell.vue
<script setup lang="ts">
// ** Local Imports
import { useTableCell } from "@/Components/Table/composables/useTableCell";
import type {
  TableCellOwnProps,
  TableCellSlots,
} from "@/Components/Table/table.types";

defineSlots<TableCellSlots>();

defineOptions({ inheritAttrs: false });

const props = defineProps<TableCellOwnProps>();

const { rootBind } = useTableCell(props, "cell");
</script>

<template>
  <td v-bind="rootBind">
    <slot />
  </td>
</template>

// packages/react/src/Components/Table/TableCell.tsx
// ** Local Imports
import { useTableCell } from "@/Components/Table/hooks/useTableCell";
import type { TableCellProps } from "@/Components/Table/table.types";

function TableCell(props: TableCellProps) {
  const { children, rootBind } = useTableCell(props, "cell");

  return <td {...rootBind}>{children}</td>;
}

export default TableCell;
