// packages/vue/src/Components/Table/TableCaption.vue
<script setup lang="ts">
// ** Local Imports
import { useTablePart } from "@/Components/Table/composables/useTablePart";
import type {
  TableCaptionOwnProps,
  TableCaptionSlots,
} from "@/Components/Table/table.types";

defineSlots<TableCaptionSlots>();

defineOptions({ inheritAttrs: false });

const props = defineProps<TableCaptionOwnProps>();

const { rootBind } = useTablePart(props, "caption");
</script>

<template>
  <caption v-bind="rootBind">
    <slot />
  </caption>
</template>

// packages/react/src/Components/Table/TableCaption.tsx
// ** Local Imports
import { useTablePart } from "@/Components/Table/hooks/useTablePart";
import type { TableCaptionProps } from "@/Components/Table/table.types";

function TableCaption(props: TableCaptionProps) {
  const { children, rootBind } = useTablePart(props, "caption");

  return <caption {...rootBind}>{children}</caption>;
}

export default TableCaption;
