// packages/vue/src/Components/Table/TableBody.vue
<script setup lang="ts">
// ** Local Imports
import { useTablePart } from "@/Components/Table/composables/useTablePart";
import type {
  TableBodyOwnProps,
  TableBodySlots,
} from "@/Components/Table/table.types";

defineSlots<TableBodySlots>();

defineOptions({ inheritAttrs: false });

const props = defineProps<TableBodyOwnProps>();

const { rootBind } = useTablePart(props, "body");
</script>

<template>
  <tbody v-bind="rootBind">
    <slot />
  </tbody>
</template>

// packages/react/src/Components/Table/TableBody.tsx
// ** Local Imports
import { TableSectionContext } from "@/Components/Table/TableContext";
import { useTablePart } from "@/Components/Table/hooks/useTablePart";
import type { TableBodyProps } from "@/Components/Table/table.types";

function TableBody(props: TableBodyProps) {
  const { children, rootBind } = useTablePart(props, "body");

  return (
    <TableSectionContext.Provider value="body">
      <tbody {...rootBind}>{children}</tbody>
    </TableSectionContext.Provider>
  );
}

export default TableBody;
