// packages/vue/src/Components/Switcher/Switcher.vue
<script setup lang="ts">
// ** Local Imports
import { Label } from "@/Components/Label";
import type { UseSwitcherReturn } from "@/Components/Switcher/composables/useSwitcher";
import { hasSlotOrProp, resolveSlotOrProp } from "@/Utils";

defineOptions({ inheritAttrs: false });

const props = defineProps<{
  field: UseSwitcherReturn;
}>();

const api = props.field;
</script>

<template>
  <div
    v-bind="api.rootBind"
    :data-invalid="api.invalidated.value || undefined"
    :aria-disabled="api.isDisabled.value || undefined"
    :aria-readonly="api.isReadonly.value || undefined"
  >
    <div v-bind="api.rowBind">
      <Label
        v-if="hasSlotOrProp(api.slots, 'leftLabel', api.merged.value.leftLabel)"
        v-bind="api.leftLabelProps"
      >
        <component
          :is="
            resolveSlotOrProp(
              api.slots,
              'leftLabel',
              api.merged.value.leftLabel,
            )
          "
        />
      </Label>

      <slot />

      <Label
        v-if="hasSlotOrProp(api.slots, 'label', api.merged.value.label)"
        v-bind="api.labelProps"
      >
        <component
          :is="resolveSlotOrProp(api.slots, 'label', api.merged.value.label)"
        />
      </Label>
    </div>

    <p
      v-if="
        !api.invalidated.value &&
        hasSlotOrProp(api.slots, 'description', api.merged.value.description)
      "
      v-bind="api.descriptionBind"
    >
      <component
        :is="
          resolveSlotOrProp(
            api.slots,
            'description',
            api.merged.value.description,
          )
        "
      />
    </p>

    <p
      v-if="!api.merged.value.errorless && api.reservesErrorMessageSpace.value"
      v-bind="api.errorMessageBind"
      :aria-hidden="api.showErrorMessageContent.value ? undefined : true"
    >
      <template v-if="api.showErrorMessageContent.value">
        <component
          :is="
            resolveSlotOrProp(
              api.slots,
              'errorMessage',
              api.merged.value.errorMessage,
            )
          "
        />
      </template>
    </p>
  </div>
</template>

// packages/react/src/Components/Switcher/Switcher.tsx
// ** Local Imports
import { Label } from "@/Components/Label";
import type { UseSwitcherReturn } from "@/Components/Switcher/hooks/useSwitcher";
import type { SwitcherProps } from "@/Components/Switcher/switcher.types";
import { hasSlotOrProp, resolveSlotOrProp } from "@/Utils";

type SwitcherComponentProps = Required<
  Pick<SwitcherProps, "field" | "children">
>;

function Switcher({ field, children }: SwitcherComponentProps) {
  const api: UseSwitcherReturn = field;

  return (
    <div
      {...api.rootBind}
      data-invalid={api.invalidated || undefined}
      aria-disabled={api.isDisabled || undefined}
      aria-readonly={api.isReadonly || undefined}
    >
      <div {...api.rowBind}>
        {hasSlotOrProp(api.slots, "leftLabel", api.merged.leftLabel) && (
          <Label {...api.leftLabelProps}>
            {resolveSlotOrProp({
              name: "leftLabel",
              slots: api.slots,
              fallback: api.merged.leftLabel,
            })}
          </Label>
        )}

        {children}

        {hasSlotOrProp(api.slots, "label", api.merged.label) && (
          <Label {...api.labelProps}>
            {resolveSlotOrProp({
              name: "label",
              slots: api.slots,
              fallback: api.merged.label,
            })}
          </Label>
        )}
      </div>

      {!api.invalidated &&
        hasSlotOrProp(api.slots, "description", api.merged.description) && (
          <p {...api.descriptionBind}>
            {resolveSlotOrProp({
              name: "description",
              slots: api.slots,
              fallback: api.merged.description,
            })}
          </p>
        )}

      {!api.merged.errorless && api.reservesErrorMessageSpace && (
        <p
          {...api.errorMessageBind}
          aria-hidden={api.showErrorMessageContent ? undefined : true}
        >
          {api.showErrorMessageContent &&
            resolveSlotOrProp({
              name: "errorMessage",
              slots: api.slots,
              fallback: api.merged.errorMessage,
            })}
        </p>
      )}
    </div>
  );
}

export default Switcher;
