// packages/react/src/Components/Rating/Rating.tsx
// ** Local Imports
import BaseField from "@/Components/BaseField/BaseField";
import { Icon } from "@/Components/Icon";
import { useRating } from "@/Components/Rating/hooks/useRating";
import type { RatingProps } from "@/Components/Rating/rating.types";

function Rating(props: RatingProps) {
  const api = useRating(props);

  const { icon, items, inputBind, groupBind, baseField, setItemRef } = api;

  return (
    <BaseField field={baseField}>
      <div {...groupBind}>
        {items.map((item) => (
          <button
            key={item.value}
            {...item.itemBind}
            ref={(node) => {
              setItemRef(item.value, node);
            }}
          >
            {item.fill > 0 && item.fill < 1 ? (
              <span className="relative inline-flex">
                <Icon icon={icon} {...item.emptyIconBind} />

                <span
                  style={{ width: `${item.fill * 100}%` }}
                  className="absolute inset-y-0 inset-s-0 overflow-hidden"
                >
                  <Icon icon={icon} {...item.filledIconBind} />
                </span>
              </span>
            ) : (
              <Icon icon={icon} {...item.iconBind} />
            )}
          </button>
        ))}

        <input {...inputBind} />
      </div>
    </BaseField>
  );
}

export default Rating;

// packages/vue/src/Components/Rating/Rating.vue
<script setup lang="ts">
// ** Local Imports
import { BASE_FIELD_CHROME_SLOT_NAMES } from "@/Components/BaseField";
import BaseField from "@/Components/BaseField/BaseField.vue";
import { Icon } from "@/Components/Icon";
import { useRating } from "@/Components/Rating/composables/useRating";
import type {
  RatingOwnProps,
  RatingSlots,
} from "@/Components/Rating/rating.types";
import { presentSlotNames } from "@/Utils";

defineSlots<RatingSlots>();

defineOptions({ inheritAttrs: false });

const props = defineProps<RatingOwnProps>();

const model = defineModel<null | number | undefined>();

const api = useRating(props, model);

const { icon, items, inputBind, groupBind, baseField, setItemRef } = api;
</script>

<template>
  <BaseField :field="baseField">
    <template
      #[name]="slotData"
      v-for="name in presentSlotNames(BASE_FIELD_CHROME_SLOT_NAMES, $slots)"
    >
      <slot :name="name" v-bind="slotData || {}" />
    </template>

    <div v-bind="groupBind">
      <button
        :key="item.value"
        v-for="item in items"
        v-bind="item.itemBind"
        :ref="(node) => setItemRef(item.value, node)"
      >
        <span
          class="relative inline-flex"
          v-if="item.fill > 0 && item.fill < 1"
        >
          <Icon v-bind="item.emptyIconBind" :icon="icon" />

          <span
            :style="{ width: `${item.fill * 100}%` }"
            class="absolute inset-y-0 inset-s-0 overflow-hidden"
          >
            <Icon v-bind="item.filledIconBind" :icon="icon" />
          </span>
        </span>

        <Icon v-else v-bind="item.iconBind" :icon="icon" />
      </button>

      <input v-bind="inputBind" />
    </div>
  </BaseField>
</template>
