// packages/react/src/Components/DataTable/DataTableToolbarButton.tsx
// ** Local Imports
import type { IconSource } from "@/Adapters/Icon";
import { Button } from "@/Components/Button";
import type { ButtonProps } from "@/Components/Button/button.types";
import { Tooltip } from "@/Components/Tooltip";

/**
 * Internal icon-only toolbar control. Not part of the public API.
 */
export function DataTableToolbarButton({
  icon,
  label,
  onClick,
  buttonProps,
}: {
  buttonProps?: Partial<
    Omit<Extract<ButtonProps, { as?: "button" }>, "icon" | "onClick">
  >;
  icon: IconSource;
  label: string;
  onClick?: () => void;
}) {
  return (
    <Tooltip
      content={label}
      slots={{
        trigger: (
          <Button
            size="sm"
            icon={icon}
            color="dark"
            type="button"
            density="mini"
            onClick={onClick}
            aria-label={label}
            {...buttonProps}
          />
        ),
      }}
    />
  );
}

// packages/vue/src/Components/DataTable/DataTableToolbarButton.vue
<script setup lang="ts">
// ** Local Imports
import type { IconSource } from "@/Adapters/Icon";
import { Button } from "@/Components/Button";
import type { ButtonOwnProps } from "@/Components/Button/button.types";
import { Tooltip } from "@/Components/Tooltip";

defineOptions({ inheritAttrs: false, name: "DataTableToolbarButton" });

defineProps<{
  buttonProps?: Partial<Omit<ButtonOwnProps, "icon">>;
  icon: IconSource;
  label: string;
}>();

const emit = defineEmits<{
  click: [event: MouseEvent];
}>();
</script>

<template>
  <Tooltip :content="label">
    <template #trigger>
      <Button
        size="sm"
        color="dark"
        :icon="icon"
        type="button"
        density="mini"
        :aria-label="label"
        v-bind="buttonProps"
        v-on:click="emit('click', $event)"
      />
    </template>
  </Tooltip>
</template>
