// packages/react/src/Actions/Dialog/resolveBridgeDialogFooter.tsx
// ** External Imports
import type { ReactNode } from "react";

// ** Local Imports
import type { ResolveBridgeDialogFooterOptions } from "@/Actions/Dialog/bridgeDialog.types";
import { SnackbarActionControl } from "@/Actions/Snackbar/SnackbarActionControl";

export function resolveBridgeDialogFooter({
  acceptColor,
  actions,
  dismiss,
}: ResolveBridgeDialogFooterOptions): ReactNode | undefined {
  if (!actions?.accept && !actions?.reject) {
    return undefined;
  }

  return (
    <div className="flex justify-end gap-2">
      {actions.reject?.label && (
        <SnackbarActionControl
          role="reject"
          layout="inline"
          action={actions.reject}
          snackbarColor={acceptColor}
          onRun={() => {
            actions.reject?.onClick?.();
            dismiss();
          }}
        />
      )}

      {actions.accept?.label && (
        <SnackbarActionControl
          role="accept"
          layout="inline"
          action={actions.accept}
          snackbarColor={acceptColor}
          onRun={() => {
            actions.accept?.onClick?.();
            dismiss();
          }}
        />
      )}
    </div>
  );
}

// packages/vue/src/Actions/Dialog/ResolveBridgeDialogFooter.vue
<script setup lang="ts">
// ** Local Imports
import BridgeDialogAction from "@/Actions/Dialog/BridgeDialogAction.vue";
import type { ResolveBridgeDialogFooterOptions } from "@/Actions/Dialog/bridgeDialog.types";

const props = defineProps<ResolveBridgeDialogFooterOptions>();

function dismissFromAction(onClick?: () => void) {
  onClick?.();
  props.dismiss();
}
</script>

<template>
  <div
    class="flex justify-end gap-2"
    v-if="props.actions?.accept || props.actions?.reject"
  >
    <BridgeDialogAction
      role="reject"
      :action="props.actions.reject"
      :accept-color="props.acceptColor"
      v-if="props.actions?.reject?.label"
      v-on:run="() => dismissFromAction(props.actions?.reject?.onClick)"
    />

    <BridgeDialogAction
      role="accept"
      :action="props.actions.accept"
      :accept-color="props.acceptColor"
      v-if="props.actions?.accept?.label"
      v-on:run="() => dismissFromAction(props.actions?.accept?.onClick)"
    />
  </div>
</template>
