// packages/vue/src/Components/Breadcrumb/Breadcrumb.vue
<script setup lang="ts">
// ** Local Imports
import type {
  BreadcrumbOwnProps,
  BreadcrumbSlots,
} from "@/Components/Breadcrumb/breadcrumb.types";
import { useBreadcrumb } from "@/Components/Breadcrumb/composables/useBreadcrumb";
import { BreadcrumbItem } from "@/Components/BreadcrumbItem";

defineSlots<BreadcrumbSlots>();

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<BreadcrumbOwnProps>(), {
  separator: "chevronRight",
});

const { rootBind, listBind, collapsedItems, hasDefaultSlot } = useBreadcrumb(
  props,
  {
    size: "md",
    separator: "chevronRight",
  },
);
</script>

<template>
  <nav v-bind="rootBind">
    <ol v-bind="listBind">
      <template v-if="!hasDefaultSlot && collapsedItems.length > 0">
        <template
          v-for="(entry, index) in collapsedItems"
          :key="entry.type === 'ellipsis' ? `ellipsis-${index}` : entry.index"
        >
          <BreadcrumbItem as="span" v-if="entry.type === 'ellipsis'">
            …
          </BreadcrumbItem>

          <BreadcrumbItem
            v-else
            :as="entry.item.as"
            :href="entry.item.href"
            :current="entry.item.current"
            :end-icon="entry.item.endIcon"
            :disabled="entry.item.disabled"
            :start-icon="entry.item.startIcon"
          >
            {{ entry.item.label }}
          </BreadcrumbItem>
        </template>
      </template>

      <slot />
    </ol>
  </nav>
</template>

// packages/react/src/Components/Breadcrumb/Breadcrumb.tsx
// ** Local Imports
import type { BreadcrumbProps } from "@/Components/Breadcrumb/breadcrumb.types";
import { BreadcrumbContext } from "@/Components/Breadcrumb/BreadcrumbContext";
import { useBreadcrumb } from "@/Components/Breadcrumb/hooks/useBreadcrumb";
import { BreadcrumbItem } from "@/Components/BreadcrumbItem";

const breadcrumbLibDefaults = {
  size: "md",
  separator: "chevronRight",
} as const;

function Breadcrumb(props: BreadcrumbProps) {
  const { children, rootBind, listBind, contextValue, collapsedItems } =
    useBreadcrumb(props, breadcrumbLibDefaults);

  const hasChildren = children != null && children !== false;
  const useItems = !hasChildren && collapsedItems.length > 0;

  return (
    <BreadcrumbContext.Provider value={contextValue}>
      <nav {...rootBind}>
        <ol {...listBind}>
          {useItems
            ? collapsedItems.map((entry, index) => {
                if (entry.type === "ellipsis") {
                  return (
                    <BreadcrumbItem as="span" key={`ellipsis-${index}`}>
                      …
                    </BreadcrumbItem>
                  );
                }

                const { item } = entry;

                return (
                  <BreadcrumbItem
                    as={item.as}
                    href={item.href}
                    key={entry.index}
                    current={item.current}
                    endIcon={item.endIcon}
                    disabled={item.disabled}
                    startIcon={item.startIcon}
                  >
                    {item.label}
                  </BreadcrumbItem>
                );
              })
            : null}

          {hasChildren ? children : null}
        </ol>
      </nav>
    </BreadcrumbContext.Provider>
  );
}

export default Breadcrumb;
