// packages/react/src/Components/ResizableHandle/ResizableHandle.tsx
// ** Local Imports
import { useResizableHandle } from "@/Components/ResizableHandle/hooks/useResizableHandle";
import type { ResizableHandleProps } from "@/Components/ResizableHandle/resizableHandle.types";

const resizableHandleLibDefaults = {
  disabled: false,
  withHandle: false,
} as const;

function ResizableHandle(props: ResizableHandleProps) {
  const { slots, gripBind, rootBind, showGrip, elementRef } =
    useResizableHandle(props, resizableHandleLibDefaults);

  return (
    <div {...rootBind} ref={elementRef}>
      {showGrip ? <div {...gripBind}>{slots?.grip}</div> : null}
    </div>
  );
}

export default ResizableHandle;

// packages/vue/src/Components/ResizableHandle/ResizableHandle.vue
<script setup lang="ts">
// ** Local Imports
import { useResizableHandle } from "@/Components/ResizableHandle/composables/useResizableHandle";
import type {
  ResizableHandleOwnProps,
  ResizableHandleSlots,
} from "@/Components/ResizableHandle/resizableHandle.types";

defineSlots<ResizableHandleSlots>();

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<ResizableHandleOwnProps>(), {
  disabled: undefined,
  withHandle: undefined,
});

const { gripBind, rootBind, showGrip, elementRef } = useResizableHandle(props, {
  disabled: false,
  withHandle: false,
});
</script>

<template>
  <div ref="elementRef" v-bind="rootBind">
    <div v-if="showGrip" v-bind="gripBind">
      <slot name="grip" />
    </div>
  </div>
</template>
