// packages/react/src/Components/Stepper/Stepper.tsx
// ** Local Imports
import { useStepper } from "@/Components/Stepper/hooks/useStepper";
import type { StepperProps } from "@/Components/Stepper/stepper.types";
import { StepperContext } from "@/Components/Stepper/StepperContext";

const stepperLibDefaults = {
  size: "md",
  linear: true,
  color: "primary",
  orientation: "horizontal",
} as const;

function Stepper(props: StepperProps) {
  const { children, listBind, rootBind, contextValue } = useStepper(
    props,
    stepperLibDefaults,
  );

  return (
    <StepperContext.Provider value={contextValue}>
      <nav {...rootBind}>
        <ol {...listBind}>{children}</ol>
      </nav>
    </StepperContext.Provider>
  );
}

export default Stepper;

// packages/vue/src/Components/Stepper/Stepper.vue
<script setup lang="ts">
// ** Local Imports
import { useStepper } from "@/Components/Stepper/composables/useStepper";
import type {
  StepperEmits,
  StepperOwnProps,
  StepperSlots,
} from "@/Components/Stepper/stepper.types";

defineSlots<StepperSlots>();

const emit = defineEmits<StepperEmits>();

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<StepperOwnProps>(), {
  linear: true,
});

const model = defineModel<number>({ default: 0 });

const { listBind, rootBind } = useStepper(
  props,
  {
    size: "md",
    linear: true,
    color: "primary",
    orientation: "horizontal",
  },
  model,
  emit,
);
</script>

<template>
  <nav v-bind="rootBind">
    <ol v-bind="listBind">
      <slot />
    </ol>
  </nav>
</template>
