// packages/react/src/Components/TimeRangeField/TimeRangeField.tsx
// ** Local Imports
import { useResolveMessage } from "@/Adapters/I18n";
import { FieldOverlay } from "@/Components/FieldOverlay";
import { FormField } from "@/Components/FormField";
import { Icon } from "@/Components/Icon";
import { useTimeRangeField } from "@/Components/TimeRangeField/hooks/useTimeRangeField";
import type { TimeRangeFieldProps } from "@/Components/TimeRangeField/timeRangeField.types";
import { TimeRangePicker } from "@/Components/TimeRangePicker";

function TimeRangeField(props: TimeRangeFieldProps) {
  const resolveMessage = useResolveMessage();

  const {
    open,
    overlay,
    timeOnly,
    formField,
    inputBind,
    clearBind,
    clearValue,
    modelValue,
    showFooter,
    footerSlot,
    clearIconSize,
    showClearIcon,
    pickerClassName,
    handleOpenChange,
    handlePickerChange,
    handlePickerCancel,
    overlayCustomProps,
    timeRangePickerCustomProps,
  } = useTimeRangeField(props);

  return (
    <>
      <FormField field={formField}>
        <div className="flex min-w-0 flex-1 items-center gap-1">
          <input {...inputBind} />

          {showClearIcon ? (
            <span
              {...clearBind}
              onClick={() => clearValue()}
              aria-label={resolveMessage("Clear")}
              onKeyDown={(event) => {
                if (event.key === "Enter" || event.key === " ") {
                  event.preventDefault();
                  clearValue();
                }
              }}
            >
              <Icon
                icon="clear"
                size={clearIconSize}
                {...props.customProps?.clearIcon}
              />
            </span>
          ) : null}
        </div>
      </FormField>

      <FieldOverlay
        show={open}
        overlay={overlay}
        onShowChange={handleOpenChange}
        customProps={overlayCustomProps}
      >
        <TimeRangePicker
          value={modelValue}
          ampm={timeOnly.ampm}
          showFooter={showFooter}
          readOnly={props.readonly}
          maxTime={timeOnly.maxTime}
          minTime={timeOnly.minTime}
          className={pickerClassName}
          timeZone={timeOnly.timeZone}
          interval={timeOnly.interval}
          onChange={handlePickerChange}
          onCancel={handlePickerCancel}
          error={formField.invalidated}
          color={formField.merged.color}
          disabled={formField.isDisabled}
          showSeconds={timeOnly.showSeconds}
          rounded={formField.merged.rounded}
          disableTimes={timeOnly.disableTimes}
          customProps={timeRangePickerCustomProps}
          slots={footerSlot ? { footer: footerSlot } : undefined}
        />
      </FieldOverlay>
    </>
  );
}

export default TimeRangeField;

// packages/vue/src/Components/TimeRangeField/TimeRangeField.vue
<script setup lang="ts">
// ** External Imports
import { ref } from "vue";

// ** Core Imports
import type { TimeRangeValue } from "@bridge-ui/core/Domain";

// ** Local Imports
import { useResolveMessage } from "@/Adapters/I18n";
import { FieldOverlay } from "@/Components/FieldOverlay";
import {
  FORM_FIELD_CHROME_SLOT_NAMES,
  FormField,
} from "@/Components/FormField";
import { Icon } from "@/Components/Icon";
import { useTimeRangeField } from "@/Components/TimeRangeField/composables/useTimeRangeField";
import type {
  TimeRangeFieldEmits,
  TimeRangeFieldOwnProps,
  TimeRangeFieldSlots,
} from "@/Components/TimeRangeField/timeRangeField.types";
import { TimeRangePicker } from "@/Components/TimeRangePicker";
import { presentSlotNames, useOptionalModel } from "@/Utils";

defineSlots<TimeRangeFieldSlots>();

defineOptions({ inheritAttrs: false });

const resolveMessage = useResolveMessage();

const emit = defineEmits<TimeRangeFieldEmits>();

const model = defineModel<null | TimeRangeValue>();

const props = withDefaults(defineProps<TimeRangeFieldOwnProps>(), {
  fill: undefined,
  clearable: false,
  showErrorIcon: true,
  showFooter: undefined,
});

const uncontrolledValue = ref<null | TimeRangeValue>(
  props.defaultValue ?? null,
);

const value = useOptionalModel(model, uncontrolledValue);

const {
  open,
  fill,
  overlay,
  timeOnly,
  formField,
  inputBind,
  clearBind,
  clearValue,
  modelValue,
  showFooter,
  pickerClass,
  clearIconSize,
  showClearIcon,
  handleOpenChange,
  handlePickerChange,
  handlePickerCancel,
  overlayCustomProps,
  timeRangePickerCustomProps,
} = useTimeRangeField(props, value, emit);
</script>

<template>
  <FormField :field="formField">
    <template
      #[name]="slotData"
      v-for="name in presentSlotNames(FORM_FIELD_CHROME_SLOT_NAMES, $slots)"
    >
      <slot :name="name" v-bind="slotData || {}" />
    </template>

    <div class="flex min-w-0 flex-1 items-center gap-1">
      <input v-bind="inputBind" />

      <span
        v-bind="clearBind"
        v-if="showClearIcon"
        v-on:click="clearValue"
        :aria-label="resolveMessage('Clear')"
        v-on:keydown.enter.prevent="clearValue"
        v-on:keydown.space.prevent="clearValue"
      >
        <Icon
          icon="clear"
          :size="clearIconSize"
          v-bind="props.customProps?.clearIcon"
        />
      </span>
    </div>
  </FormField>

  <FieldOverlay
    :overlay="overlay"
    :model-value="open"
    :custom-props="overlayCustomProps"
    v-on:update:model-value="handleOpenChange"
  >
    <TimeRangePicker
      :fill="fill"
      :class="pickerClass"
      :ampm="timeOnly.ampm"
      :model-value="modelValue"
      :show-footer="showFooter"
      :read-only="props.readonly"
      :max-time="timeOnly.maxTime"
      :min-time="timeOnly.minTime"
      :interval="timeOnly.interval"
      :time-zone="timeOnly.timeZone"
      v-on:change="handlePickerChange"
      v-on:cancel="handlePickerCancel"
      :show-seconds="timeOnly.showSeconds"
      :error="formField.invalidated.value"
      :color="formField.merged.value.color"
      :disabled="formField.isDisabled.value"
      :disable-times="timeOnly.disableTimes"
      :rounded="formField.merged.value.rounded"
      :custom-props="timeRangePickerCustomProps"
    >
      <template #footer="footer" v-if="$slots.footer">
        <slot name="footer" v-bind="footer" />
      </template>
    </TimeRangePicker>
  </FieldOverlay>
</template>
