// packages/react/src/Components/ChartLegend/ChartLegend.tsx
// ** Local Imports
import type { ChartLegendProps } from "@/Components/ChartLegend/chartLegend.types";
import { useChartLegend } from "@/Components/ChartLegend/hooks/useChartLegend";

function ChartLegend(props: ChartLegendProps) {
  const {
    items,
    rootBind,
    labelBind,
    interactive,
    getItemBind,
    getSwatchBind,
  } = useChartLegend(props, {
    align: "center",
    interactive: true,
    position: "bottom",
  });

  return (
    <ul {...rootBind}>
      {items.map((item) => (
        <li key={item.id}>
          {interactive ? (
            <button {...getItemBind(item)}>
              <span {...getSwatchBind(item)} />
              <span {...labelBind}>{item.name}</span>
            </button>
          ) : (
            <span {...getItemBind(item)}>
              <span {...getSwatchBind(item)} />
              <span {...labelBind}>{item.name}</span>
            </span>
          )}
        </li>
      ))}
    </ul>
  );
}

export default ChartLegend;

// packages/vue/src/Components/ChartLegend/ChartLegend.vue
<script setup lang="ts">
// ** Local Imports
import type { ChartLegendOwnProps } from "@/Components/ChartLegend/chartLegend.types";
import { useChartLegend } from "@/Components/ChartLegend/composables/useChartLegend";

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<ChartLegendOwnProps>(), {
  interactive: undefined,
});

const { items, rootBind, labelBind, interactive, getItemBind, getSwatchBind } =
  useChartLegend(props, {
    align: "center",
    interactive: true,
    position: "bottom",
  });
</script>

<template>
  <ul v-bind="rootBind">
    <li :key="item.id" v-for="item in items">
      <button v-if="interactive" v-bind="getItemBind(item)">
        <span v-bind="getSwatchBind(item)" />
        <span v-bind="labelBind">{{ item.name }}</span>
      </button>

      <span v-else v-bind="getItemBind(item)">
        <span v-bind="getSwatchBind(item)" />
        <span v-bind="labelBind">{{ item.name }}</span>
      </span>
    </li>
  </ul>
</template>
