// packages/vue/src/Components/Carousel/Carousel.vue
<script setup lang="ts">
// ** Local Imports
import type {
  CarouselOwnProps,
  CarouselSlots,
} from "@/Components/Carousel/carousel.types";
import { useCarousel } from "@/Components/Carousel/composables/useCarousel";
import { Icon } from "@/Components/Icon";

defineOptions({ inheritAttrs: false });

defineSlots<CarouselSlots>();

const props = withDefaults(defineProps<CarouselOwnProps>(), {
  indicators: true,
});

const index = defineModel<number>("index");

const {
  liveBind,
  nextBind,
  prevBind,
  rootBind,
  nextIcon,
  prevIcon,
  trackBind,
  activeIndex,
  controlsBind,
  nextIconBind,
  prevIconBind,
  showControls,
  viewportBind,
  announcement,
  indicatorsBind,
  showIndicators,
  getIndicatorBind,
  indicatorIndexes,
} = useCarousel(
  props,
  {
    gap: 0,
    size: "md",
    loop: false,
    align: "start",
    autoPlay: false,
    defaultIndex: 0,
    indicators: true,
    slidesPerView: 1,
    orientation: "horizontal",
  },
  index,
);
</script>

<template>
  <section v-bind="rootBind">
    <div v-bind="viewportBind">
      <div v-bind="trackBind">
        <slot />
      </div>

      <div v-if="showControls" v-bind="controlsBind">
        <button v-bind="prevBind">
          <slot name="prev">
            <Icon :icon="prevIcon" v-bind="prevIconBind" />
          </slot>
        </button>

        <button v-bind="nextBind">
          <slot name="next">
            <Icon :icon="nextIcon" v-bind="nextIconBind" />
          </slot>
        </button>
      </div>
    </div>

    <div v-if="showIndicators" v-bind="indicatorsBind">
      <button
        :key="slideIndex"
        v-bind="getIndicatorBind(slideIndex)"
        v-for="slideIndex in indicatorIndexes"
      >
        <slot
          name="indicator"
          :index="slideIndex"
          :selected="slideIndex === activeIndex"
        />
      </button>
    </div>

    <div v-bind="liveBind">
      {{ announcement }}
    </div>
  </section>
</template>

// packages/react/src/Components/Carousel/Carousel.tsx
// ** Local Imports
import type { CarouselProps } from "@/Components/Carousel/carousel.types";
import { CarouselContext } from "@/Components/Carousel/CarouselContext";
import { useCarousel } from "@/Components/Carousel/hooks/useCarousel";
import { Icon } from "@/Components/Icon";

const carouselLibDefaults = {
  gap: 0,
  size: "md",
  loop: false,
  align: "start",
  autoPlay: false,
  defaultIndex: 0,
  indicators: true,
  slidesPerView: 1,
  orientation: "horizontal",
} as const;

function Carousel(props: CarouselProps) {
  const {
    slots,
    children,
    liveBind,
    nextBind,
    prevBind,
    rootBind,
    prevIcon,
    nextIcon,
    trackBind,
    activeIndex,
    controlsBind,
    nextIconBind,
    prevIconBind,
    showControls,
    viewportBind,
    contextValue,
    announcement,
    indicatorsBind,
    showIndicators,
    getIndicatorBind,
  } = useCarousel(props, carouselLibDefaults);

  return (
    <CarouselContext.Provider value={contextValue}>
      <section {...rootBind}>
        <div {...viewportBind}>
          <div {...trackBind}>{children}</div>
          {showControls ? (
            <div {...controlsBind}>
              <button {...prevBind}>
                {slots?.prev ?? <Icon icon={prevIcon} {...prevIconBind} />}
              </button>
              <button {...nextBind}>
                {slots?.next ?? <Icon icon={nextIcon} {...nextIconBind} />}
              </button>
            </div>
          ) : null}
        </div>
        {showIndicators ? (
          <div {...indicatorsBind}>
            {Array.from({ length: contextValue.slideCount }, (_, index) => (
              <button key={index} {...getIndicatorBind(index)}>
                {slots?.indicator?.({
                  index,
                  selected: index === activeIndex,
                })}
              </button>
            ))}
          </div>
        ) : null}
        <div {...liveBind}>{announcement}</div>
      </section>
    </CarouselContext.Provider>
  );
}

export default Carousel;
