// packages/react/src/Components/MiniBadge/MiniBadge.tsx
// ** Local Imports
import type { MiniBadgeProps } from "@/Components/MiniBadge";
import { useMiniBadge } from "@/Components/MiniBadge";

function MiniBadge(props: MiniBadgeProps) {
  const { children, rootClass, rootHtmlProps } = useMiniBadge(props, {
    size: "xs",
    rounded: "full",
    variant: "flat",
    color: "primary",
  });

  return (
    <span {...rootHtmlProps} className={rootClass}>
      {children}
    </span>
  );
}

export default MiniBadge;

// packages/vue/src/Components/MiniBadge/MiniBadge.vue
<script setup lang="ts">
// ** Local Imports
import { useMiniBadge } from "@/Components/MiniBadge/composables/useMiniBadge";
import type { MiniBadgeOwnProps } from "@/Components/MiniBadge/miniBadge.types";

defineOptions({ inheritAttrs: false });

const props = defineProps<MiniBadgeOwnProps>();

const { rootBind, rootClass } = useMiniBadge(props, {
  size: "xs",
  rounded: "full",
  variant: "flat",
  color: "primary",
});
</script>

<template>
  <span :class="rootClass" v-bind="rootBind">
    <slot />
  </span>
</template>
