// packages/react/src/Components/Label/Label.tsx
// ** Local Imports
import { useLabel } from "@/Components/Label/hooks/useLabel";
import type { LabelProps } from "@/Components/Label/label.types";

function Label(props: LabelProps) {
  const { merged, children, rootBind, requiredBind } = useLabel(props, {
    size: "md",
  });

  return (
    <label {...rootBind}>
      {children}

      {merged.required && <span {...requiredBind}>*</span>}
    </label>
  );
}

export default Label;

// packages/vue/src/Components/Label/Label.vue
<script setup lang="ts">
// ** Local Imports
import { useLabel } from "@/Components/Label/composables/useLabel";
import type { LabelOwnProps } from "@/Components/Label/label.types";

defineOptions({ inheritAttrs: false });

const props = defineProps<LabelOwnProps>();

const { merged, rootBind, requiredBind } = useLabel(props, {
  size: "md",
});
</script>

<template>
  <label v-bind="rootBind">
    <slot />

    <span v-if="merged.required" v-bind="requiredBind">*</span>
  </label>
</template>
