// packages/vue/src/Components/Snackbar/Snackbar.vue
<script setup lang="ts">
// ** External Imports
import { X } from "lucide-vue-next";
import { computed, useSlots } from "vue";

// ** Core Imports
import { cn } from "@bridge-ui/core";

// ** Local Imports
import { Icon } from "@/Components/Icon";
import { useSnackbar } from "@/Components/Snackbar/composables/useSnackbar";
import type {
  SnackbarEmits,
  SnackbarOwnProps,
  SnackbarSlots,
} from "@/Components/Snackbar/snackbar.types";

defineSlots<SnackbarSlots>();

const slots = useSlots();

const emit = defineEmits<SnackbarEmits>();

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<SnackbarOwnProps>(), {
  closeButton: true,
  progressbar: true,
  position: "bottom-center",
  teleportTo: "body",
});

const model = defineModel<boolean>({ default: false });

const {
  merged,
  rendered,
  isPortaled,
  portalBind,
  panelBind,
  iconBind,
  titleBind,
  progressBind,
  resolvedIcon,
  descriptionBind,
  requestClose,
} = useSnackbar(
  props,
  {
    color: "primary",
    duration: 5000,
    position: "bottom-center",
    transition: "slide",
    closeButton: true,
    progressbar: true,
    teleportTo: "body",
  },
  {
    show: model,
    stackId: props.stackId,
    onClose: () => emit("close"),
    onShowChange: (show) => props.onShowChange?.(show),
  },
);

const hasIcon = computed(() => {
  return Boolean(slots.icon || resolvedIcon.value || merged.value.img);
});

const hasTitle = computed(() => {
  return Boolean(slots.title || merged.value.title);
});

const hasDescription = computed(() => {
  return Boolean(slots.description || merged.value.description);
});

const hasRight = computed(() => {
  return Boolean(slots.right);
});

const teleportDisabled = computed(() => merged.value.teleportTo === false);

const teleportTarget = computed(() => {
  if (merged.value.teleportTo === false) {
    return "body";
  }

  return merged.value.teleportTo;
});
</script>

<template>
  <Teleport :to="teleportTarget" :disabled="teleportDisabled">
    <div v-if="rendered && isPortaled" v-bind="portalBind">
      <div class="w-full max-w-sm pointer-events-auto">
        <div
          v-bind="panelBind"
          :class="cn(panelBind.class, { flex: hasRight })"
        >
          <div
            v-if="
              model && merged.duration !== false && merged.progressbar !== false
            "
            v-bind="progressBind"
          />

          <div
            :class="{
              'pl-4': merged.dense,
              'p-4': !hasRight,
              'w-0 flex-1 flex items-center p-4': hasRight,
            }"
          >
            <div
              :class="{
                'flex items-start': !hasRight,
                'w-full flex': hasRight,
              }"
            >
              <div
                v-if="hasIcon"
                class="shrink-0"
                :class="{
                  'w-6': Boolean(resolvedIcon || slots.icon),
                  'pt-0.5': Boolean(merged.img),
                }"
              >
                <slot name="icon" />

                <img
                  v-if="!slots.icon && merged.img"
                  :src="merged.img"
                  alt=""
                  class="w-10 h-10 rounded-full"
                />

                <Icon
                  v-if="!slots.icon && !merged.img && resolvedIcon"
                  :icon="resolvedIcon"
                  v-bind="iconBind"
                />
              </div>

              <div class="w-0 flex-1 pt-0.5" :class="{ 'ml-3': hasIcon }">
                <p v-if="hasTitle" v-bind="titleBind">
                  <slot name="title">{{ merged.title }}</slot>
                </p>

                <p v-if="hasDescription" v-bind="descriptionBind">
                  <slot name="description">{{ merged.description }}</slot>
                </p>

                <slot />

                <div
                  v-if="slots.actions"
                  class="flex mt-3 gap-x-3"
                  :class="merged.classes?.actions"
                >
                  <slot name="actions" />
                </div>
              </div>

              <div class="flex ml-4 shrink-0">
                <slot name="trailing" />

                <button
                  v-if="merged.closeButton !== false"
                  type="button"
                  aria-label="Close"
                  class="cursor-pointer inline-flex rounded-md text-dark-400 hover:text-dark-500 focus:outline-hidden"
                  v-on:click="requestClose"
                >
                  <X class="w-5 h-5" />
                </button>
              </div>
            </div>
          </div>

          <slot name="right" />
        </div>
      </div>
    </div>

    <div
      v-else-if="rendered"
      v-bind="panelBind"
      :class="cn(panelBind.class, { flex: hasRight })"
    >
      <div
        v-if="
          model && merged.duration !== false && merged.progressbar !== false
        "
        v-bind="progressBind"
      />

      <div
        :class="{
          'pl-4': merged.dense,
          'p-4': !hasRight,
          'w-0 flex-1 flex items-center p-4': hasRight,
        }"
      >
        <div
          :class="{
            'flex items-start': !hasRight,
            'w-full flex': hasRight,
          }"
        >
          <div
            v-if="hasIcon"
            class="shrink-0"
            :class="{
              'w-6': Boolean(resolvedIcon || slots.icon),
              'pt-0.5': Boolean(merged.img),
            }"
          >
            <slot name="icon" />

            <img
              v-if="!slots.icon && merged.img"
              :src="merged.img"
              alt=""
              class="w-10 h-10 rounded-full"
            />

            <Icon
              v-if="!slots.icon && !merged.img && resolvedIcon"
              :icon="resolvedIcon"
              v-bind="iconBind"
            />
          </div>

          <div class="w-0 flex-1 pt-0.5" :class="{ 'ml-3': hasIcon }">
            <p v-if="hasTitle" v-bind="titleBind">
              <slot name="title">{{ merged.title }}</slot>
            </p>

            <p v-if="hasDescription" v-bind="descriptionBind">
              <slot name="description">{{ merged.description }}</slot>
            </p>

            <slot />

            <div
              v-if="slots.actions"
              class="flex mt-3 gap-x-3"
              :class="merged.classes?.actions"
            >
              <slot name="actions" />
            </div>
          </div>

          <div class="flex ml-4 shrink-0">
            <slot name="trailing" />

            <button
              v-if="merged.closeButton !== false"
              type="button"
              aria-label="Close"
              class="cursor-pointer inline-flex rounded-md text-dark-400 hover:text-dark-500 focus:outline-hidden"
              v-on:click="requestClose"
            >
              <X class="w-5 h-5" />
            </button>
          </div>
        </div>
      </div>

      <slot name="right" />
    </div>
  </Teleport>
</template>

// packages/react/src/Components/Snackbar/Snackbar.tsx
// ** External Imports
import { X } from "lucide-react";
import { createPortal } from "react-dom";

// ** Core Imports
import { cn, resolveModalPortalElement } from "@bridge-ui/core";

// ** Local Imports
import { Icon } from "@/Components/Icon";
import { useSnackbar } from "@/Components/Snackbar/hooks/useSnackbar";
import type { SnackbarProps } from "@/Components/Snackbar/snackbar.types";
import { hasSlotOrProp, resolveSlotOrProp } from "@/Utils";

const snackbarLibDefaults = {
  color: "primary",
  duration: 5000,
  position: "bottom-center",
  transition: "slide",
  closeButton: true,
  progressbar: true,
  teleportTo: "body",
} as const;

function SnackbarPanel({
  show,
  merged,
  slots,
  children,
  panelBind,
  iconBind,
  titleBind,
  progressBind,
  resolvedIcon,
  descriptionBind,
  requestClose,
}: ReturnType<typeof useSnackbar> & { show: boolean }) {
  const hasIcon = Boolean(slots?.icon || resolvedIcon || merged.img);
  const hasTitle = hasSlotOrProp(slots, "title", merged.title);
  const hasDescription = hasSlotOrProp(
    slots,
    "description",
    merged.description,
  );
  const hasRight = Boolean(slots?.right);

  return (
    <div
      {...panelBind}
      className={cn(panelBind.className, {
        flex: hasRight,
      })}
    >
      {show && merged.duration !== false && merged.progressbar !== false && (
        <div {...progressBind} />
      )}

      <div
        className={cn({
          "pl-4": merged.dense,
          "p-4": !hasRight,
          "w-0 flex-1 flex items-center p-4": hasRight,
        })}
      >
        <div
          className={cn({
            "flex items-start": !hasRight,
            "w-full flex": hasRight,
          })}
        >
          {hasIcon && (
            <div
              className={cn("shrink-0", {
                "w-6": Boolean(resolvedIcon || slots?.icon),
                "pt-0.5": Boolean(merged.img),
              })}
            >
              {slots?.icon}

              {!slots?.icon && merged.img && (
                <img
                  alt=""
                  src={merged.img}
                  className="w-10 h-10 rounded-full"
                />
              )}

              {!slots?.icon && !merged.img && resolvedIcon != null && (
                <Icon icon={resolvedIcon} {...iconBind} />
              )}
            </div>
          )}

          <div
            className={cn("w-0 flex-1 pt-0.5", {
              "ml-3": hasIcon,
            })}
          >
            {hasTitle && (
              <p {...titleBind}>
                {resolveSlotOrProp({
                  slots,
                  name: "title",
                  fallback: merged.title,
                })}
              </p>
            )}

            {hasDescription && (
              <p {...descriptionBind}>
                {resolveSlotOrProp({
                  slots,
                  name: "description",
                  fallback: merged.description,
                })}
              </p>
            )}

            {children}

            {slots?.actions && (
              <div className={cn("flex mt-3 gap-x-3", merged.classes?.actions)}>
                {slots.actions}
              </div>
            )}
          </div>

          <div className="flex ml-4 shrink-0">
            {slots?.trailing}

            {merged.closeButton !== false && (
              <button
                type="button"
                aria-label="Close"
                className="cursor-pointer inline-flex rounded-md text-dark-400 hover:text-dark-500 focus:outline-hidden"
                onClick={requestClose}
              >
                <X className="w-5 h-5" />
              </button>
            )}
          </div>
        </div>
      </div>

      {slots?.right}
    </div>
  );
}

function Snackbar({
  show = false,
  onClose,
  onShowChange,
  stackId,
  ...ownProps
}: SnackbarProps) {
  const snackbarState = useSnackbar(
    { ...ownProps, show, onClose, onShowChange, stackId },
    snackbarLibDefaults,
    { show, onClose, stackId, onShowChange },
  );

  if (!snackbarState.rendered) {
    return null;
  }

  const panel = <SnackbarPanel {...snackbarState} show={show} />;

  if (!snackbarState.isPortaled) {
    return panel;
  }

  const shell = (
    <div {...snackbarState.portalBind}>
      <div className="w-full max-w-sm pointer-events-auto">{panel}</div>
    </div>
  );

  const { teleportTo } = snackbarState.merged;

  if (typeof document === "undefined") {
    return null;
  }

  const portalElement = resolveModalPortalElement(teleportTo);

  if (portalElement === null) {
    return shell;
  }

  return createPortal(shell, portalElement);
}

export default Snackbar;
