// packages/vue/src/Components/ChartTooltip/ChartTooltip.vue
<script setup lang="ts">
// ** External Imports
import { useTemplateRef } from "vue";

// ** Local Imports
import type {
  ChartTooltipOwnProps,
  ChartTooltipSlots,
} from "@/Components/ChartTooltip/chartTooltip.types";
import { useChartTooltip } from "@/Components/ChartTooltip/composables/useChartTooltip";

defineSlots<ChartTooltipSlots>();

defineOptions({ inheritAttrs: false });

const props = defineProps<ChartTooltipOwnProps>();

const tooltipRef = useTemplateRef<HTMLDivElement>("tooltip");

const {
  isOpen,
  context,
  itemBind,
  noteBind,
  rootBind,
  labelBind,
  titleBind,
  valueBind,
  percentBind,
  formatValue,
  formatPercent,
  getSwatchBind,
} = useChartTooltip(props, tooltipRef);
</script>

<template>
  <div ref="tooltip" v-bind="rootBind" v-if="isOpen && context">
    <slot name="content" v-bind="context">
      <div v-bind="titleBind" v-if="context.title">
        <span v-if="context.color" v-bind="getSwatchBind(context.color)" />
        {{ context.title }}
      </div>

      <div :key="item.id" v-bind="itemBind" v-for="item in context.items">
        <span v-if="item.color" v-bind="getSwatchBind(item.color)" />
        <span v-bind="labelBind">{{ item.name }}</span>
        <span v-bind="valueBind">{{ formatValue(item) }}</span>
        <span v-if="item.note" v-bind="noteBind">{{ item.note }}</span>
        <span v-bind="percentBind" v-if="formatPercent(item) !== null">
          {{ formatPercent(item) }}
        </span>
      </div>
    </slot>
  </div>
</template>

// packages/react/src/Components/ChartTooltip/ChartTooltip.tsx
// ** External Imports
import { isNil } from "es-toolkit/compat";

// ** Local Imports
import type { ChartTooltipProps } from "@/Components/ChartTooltip/chartTooltip.types";
import { useChartTooltip } from "@/Components/ChartTooltip/hooks/useChartTooltip";

function ChartTooltip(props: ChartTooltipProps) {
  const {
    slots,
    isOpen,
    context,
    itemBind,
    noteBind,
    rootBind,
    labelBind,
    titleBind,
    valueBind,
    percentBind,
    formatValue,
    formatPercent,
    getSwatchBind,
  } = useChartTooltip(props);

  if (!isOpen || isNil(context)) {
    return null;
  }

  return (
    <div {...rootBind}>
      {slots?.content ? (
        slots.content(context)
      ) : (
        <>
          {context.title.length > 0 ? (
            <div {...titleBind}>
              {context.color ? (
                <span {...getSwatchBind(context.color)} />
              ) : null}
              {context.title}
            </div>
          ) : null}

          {context.items.map((item) => {
            const percent = formatPercent(item);

            return (
              <div key={item.id} {...itemBind}>
                {item.color ? <span {...getSwatchBind(item.color)} /> : null}
                <span {...labelBind}>{item.name}</span>
                <span {...valueBind}>{formatValue(item)}</span>
                {item.note ? <span {...noteBind}>{item.note}</span> : null}
                {isNil(percent) ? null : (
                  <span {...percentBind}>{percent}</span>
                )}
              </div>
            );
          })}
        </>
      )}
    </div>
  );
}

export default ChartTooltip;
