// packages/react/src/Components/Slider/Slider.tsx
// ** External Imports
import { useRef } from "react";

// ** Local Imports
import BaseField from "@/Components/BaseField/BaseField";
import { useSlider } from "@/Components/Slider/hooks/useSlider";
import type { SliderProps } from "@/Components/Slider/slider.types";
import { Tooltip } from "@/Components/Tooltip";
import { resolveSlotOrProp } from "@/Utils";

const sliderLibDefaults = {
  min: 0,
  step: 1,
  max: 100,
  size: "md",
  rounded: "full",
  color: "primary",
  showStops: false,
  showTooltip: true,
} as const;

function Slider(props: SliderProps) {
  const thumb0Ref = useRef<null | HTMLButtonElement>(null);
  const thumb1Ref = useRef<null | HTMLButtonElement>(null);

  const api = useSlider(props, sliderLibDefaults);

  const {
    barBind,
    baseField,
    trackBind,
    controlBind,
    showTooltip,
    getStopBind,
    thumbIndexes,
    tooltipProps,
    getThumbBind,
    resolvedStops,
    isTooltipOpen,
    hasStopLabels,
    readThumbValue,
    stopLabelsBind,
    getStopLabelBind,
    getThumbKnobBind,
  } = api;

  const { slots } = baseField;

  const thumbRefs = [thumb0Ref, thumb1Ref] as const;

  return (
    <BaseField field={baseField}>
      <div {...controlBind}>
        <div {...trackBind}>
          <div {...barBind} />

          {resolvedStops.map((stop) => (
            <div key={`stop-${stop.value}`} {...getStopBind(stop)} />
          ))}

          {thumbIndexes.map((thumbIndex) => {
            const thumbBind = getThumbBind(thumbIndex);
            const knobBind = getThumbKnobBind(thumbIndex);

            return (
              <button
                key={thumbIndex}
                {...thumbBind}
                ref={thumbRefs[thumbIndex]}
              >
                {resolveSlotOrProp({
                  slots,
                  name: "thumb",
                  fallback: <span {...knobBind} />,
                })}
              </button>
            );
          })}
        </div>

        {showTooltip &&
          thumbIndexes.map((thumbIndex) => (
            <Tooltip
              arrow
              size="sm"
              openDelay={0}
              closeDelay={0}
              placement="top"
              key={thumbIndex}
              show={isTooltipOpen(thumbIndex)}
              anchorEl={thumbRefs[thumbIndex]}
              content={String(readThumbValue(thumbIndex))}
              {...tooltipProps}
            />
          ))}

        {hasStopLabels && (
          <div {...stopLabelsBind}>
            {resolvedStops.map((stop) =>
              stop.label ? (
                <div key={`label-${stop.value}`} {...getStopLabelBind(stop)}>
                  {stop.label}
                </div>
              ) : null,
            )}
          </div>
        )}
      </div>
    </BaseField>
  );
}

export default Slider;

// packages/vue/src/Components/Slider/Slider.vue
<script setup lang="ts">
// ** External Imports
import { ref, type ComponentPublicInstance } from "vue";

// ** Core Imports
import {
  resolveSliderBounds,
  resolveSliderDefaultValue,
  type SliderRangeValue,
} from "@bridge-ui/core/Domain";

// ** Local Imports
import { BASE_FIELD_CHROME_SLOT_NAMES } from "@/Components/BaseField";
import BaseField from "@/Components/BaseField/BaseField.vue";
import { useSlider } from "@/Components/Slider/composables/useSlider";
import type {
  SliderEmits,
  SliderOwnProps,
  SliderSlots,
} from "@/Components/Slider/slider.types";
import { Tooltip } from "@/Components/Tooltip";
import { presentSlotNames, useOptionalModel } from "@/Utils";

defineSlots<SliderSlots>();

defineOptions({ inheritAttrs: false });

const emit = defineEmits<SliderEmits>();

const props = withDefaults(defineProps<SliderOwnProps>(), {
  showTooltip: true,
});

const model = defineModel<number | undefined | SliderRangeValue>({
  default: undefined,
});

const sliderLibDefaults = {
  min: 0,
  step: 1,
  max: 100,
  size: "md",
  rounded: "full",
  color: "primary",
  showStops: false,
  showTooltip: true,
} as const;

const initialBounds = resolveSliderBounds({
  min: props.min ?? sliderLibDefaults.min,
  max: props.max ?? sliderLibDefaults.max,
  step: props.step ?? sliderLibDefaults.step,
});

const uncontrolledValue = ref<number | SliderRangeValue>(
  resolveSliderDefaultValue({
    min: initialBounds.min,
    max: initialBounds.max,
    step: initialBounds.step,
    range: Boolean(props.range),
    defaultValue: props.defaultValue,
  }),
);

const value = useOptionalModel(model, uncontrolledValue);

const thumbRefs = ref<[null | HTMLButtonElement, null | HTMLButtonElement]>([
  null,
  null,
]);

const api = useSlider(() => props, sliderLibDefaults, value, {
  onChange: (next) => {
    emit("change", next);
  },
});

const {
  barBind,
  trackRef,
  baseField,
  trackBind,
  controlBind,
  getStopBind,
  thumbIndexes,
  tooltipProps,
  getThumbBind,
  resolvedStops,
  isTooltipOpen,
  hasStopLabels,
  readThumbValue,
  stopLabelsBind,
  getStopLabelBind,
  getThumbKnobBind,
  showTooltip: tooltipEnabled,
} = api;

function setTrackRef(el: null | Element | ComponentPublicInstance) {
  trackRef.value =
    el instanceof HTMLDivElement
      ? el
      : ((el as null | { $el?: HTMLDivElement })?.$el ?? null);
}

function setThumbRef(
  thumbIndex: 0 | 1,
  el: null | Element | ComponentPublicInstance,
) {
  const button =
    el instanceof HTMLButtonElement
      ? el
      : ((el as null | { $el?: HTMLButtonElement })?.$el ?? null);

  thumbRefs.value[thumbIndex] = button;
}
</script>

<template>
  <BaseField :field="baseField">
    <template
      #[name]="slotData"
      v-for="name in presentSlotNames(BASE_FIELD_CHROME_SLOT_NAMES, $slots)"
    >
      <slot :name="name" v-bind="slotData || {}" />
    </template>

    <div v-bind="controlBind">
      <div :ref="setTrackRef" v-bind="trackBind">
        <div v-bind="barBind" />

        <div
          :key="`stop-${stop.value}`"
          v-bind="getStopBind(stop)"
          v-for="stop in resolvedStops"
        />

        <button
          :key="thumbIndex"
          v-for="thumbIndex in thumbIndexes"
          v-bind="getThumbBind(thumbIndex)"
          :ref="(el) => setThumbRef(thumbIndex, el)"
        >
          <slot name="thumb">
            <span v-bind="getThumbKnobBind(thumbIndex)" />
          </slot>
        </button>
      </div>

      <template v-if="tooltipEnabled">
        <Tooltip
          arrow
          size="sm"
          :open-delay="0"
          placement="top"
          :close-delay="0"
          :key="`tooltip-${thumbIndex}`"
          v-for="thumbIndex in thumbIndexes"
          :anchor-el="thumbRefs[thumbIndex]"
          :model-value="isTooltipOpen(thumbIndex)"
          :content="String(readThumbValue(thumbIndex))"
          v-bind="tooltipProps"
        />
      </template>

      <div v-if="hasStopLabels" v-bind="stopLabelsBind">
        <template :key="`label-${stop.value}`" v-for="stop in resolvedStops">
          <div v-if="stop.label" v-bind="getStopLabelBind(stop)">
            {{ stop.label }}
          </div>
        </template>
      </div>
    </div>
  </BaseField>
</template>
