// packages/react/src/Components/DatePicker/DatePicker.tsx
// ** Local Imports
import { Button } from "@/Components/Button";
import { Calendar } from "@/Components/Calendar";
import type { DatePickerProps } from "@/Components/DatePicker/datePicker.types";
import { useDatePicker } from "@/Components/DatePicker/hooks/useDatePicker";

function DatePicker(props: DatePickerProps) {
  const {
    merged,
    rootBind,
    footerBind,
    showFooter,
    applyLabel,
    handleApply,
    cancelLabel,
    displayValue,
    handleCancel,
    calendarTokens,
    applyButtonProps,
    cancelButtonProps,
    handleCalendarChange,
  } = useDatePicker(props, {
    startOfWeek: 0,
    color: "primary",
    showFooter: false,
  });

  return (
    <div {...rootBind}>
      <Calendar
        color={merged.color}
        range={merged.range}
        value={displayValue}
        locale={merged.locale}
        tokens={calendarTokens}
        maxDate={merged.maxDate}
        minDate={merged.minDate}
        disabled={merged.disabled}
        multiple={merged.multiple}
        readOnly={merged.readOnly}
        timeZone={merged.timeZone}
        hideYears={merged.hideYears}
        hideMonths={merged.hideMonths}
        onChange={handleCalendarChange}
        defaultView={merged.defaultView}
        startOfWeek={merged.startOfWeek}
        disableDates={merged.disableDates}
        hideWeekdays={merged.hideWeekdays}
        disableYears={merged.disableYears}
        disableMonths={merged.disableMonths}
      />

      {showFooter && (
        <div {...footerBind}>
          <Button
            variant="flat"
            color="secondary"
            onClick={handleCancel}
            {...cancelButtonProps}
          >
            {cancelLabel}
          </Button>

          <Button color="primary" onClick={handleApply} {...applyButtonProps}>
            {applyLabel}
          </Button>
        </div>
      )}
    </div>
  );
}

export default DatePicker;

// packages/vue/src/Components/DatePicker/DatePicker.vue
<script setup lang="ts">
// ** Local Imports
import { Button } from "@/Components/Button";
import Calendar from "@/Components/Calendar/Calendar.vue";
import { useDatePicker } from "@/Components/DatePicker/composables/useDatePicker";
import type {
  DatePickerEmits,
  DatePickerOwnProps,
} from "@/Components/DatePicker/datePicker.types";

defineOptions({ inheritAttrs: false });

const props = defineProps<DatePickerOwnProps>();

const emit = defineEmits<DatePickerEmits>();

const {
  merged,
  rootBind,
  footerBind,
  showFooter,
  applyLabel,
  handleApply,
  cancelLabel,
  displayValue,
  handleCancel,
  calendarTokens,
  applyButtonProps,
  cancelButtonProps,
  handleCalendarChange,
} = useDatePicker(
  props,
  { startOfWeek: 0, color: "primary", showFooter: false },
  emit,
);
</script>

<template>
  <div v-bind="rootBind">
    <Calendar
      :color="merged.color"
      :range="merged.range"
      :value="displayValue"
      :locale="merged.locale"
      :tokens="calendarTokens"
      :max-date="merged.maxDate"
      :min-date="merged.minDate"
      :disabled="merged.disabled"
      :multiple="merged.multiple"
      :read-only="merged.readOnly"
      :time-zone="merged.timeZone"
      :hide-years="merged.hideYears"
      @change="handleCalendarChange"
      :hide-months="merged.hideMonths"
      :default-view="merged.defaultView"
      :start-of-week="merged.startOfWeek"
      :disable-dates="merged.disableDates"
      :hide-weekdays="merged.hideWeekdays"
      :disable-years="merged.disableYears"
      :disable-months="merged.disableMonths"
    />

    <div v-if="showFooter" v-bind="footerBind">
      <Button
        variant="flat"
        color="secondary"
        v-bind="cancelButtonProps"
        @click="handleCancel"
      >
        {{ cancelLabel }}
      </Button>

      <Button color="primary" v-bind="applyButtonProps" @click="handleApply">
        {{ applyLabel }}
      </Button>
    </div>
  </div>
</template>
