// packages/react/src/Components/Radio/Radio.tsx
// ** Local Imports
import { useRadio } from "@/Components/Radio/hooks/useRadio";
import type { RadioProps } from "@/Components/Radio/radio.types";
import { Switcher } from "@/Components/Switcher";

function Radio(props: RadioProps) {
  const { dotBind, switcher, fieldBind, inputBind, controlBind } = useRadio(
    props,
    {
      size: "sm",
      rounded: "full",
      color: "primary",
    },
  );

  return (
    <Switcher field={switcher}>
      <label htmlFor={switcher.controlId} {...fieldBind}>
        <input {...inputBind} />

        <span {...controlBind}>
          <span {...dotBind} />
        </span>
      </label>
    </Switcher>
  );
}

export default Radio;

// packages/vue/src/Components/Radio/Radio.vue
<script setup lang="ts">
// ** External Imports
import { computed, useAttrs } from "vue";

// ** Local Imports
import { useRadio } from "@/Components/Radio/composables/useRadio";
import type { RadioOwnProps, RadioSlots } from "@/Components/Radio/radio.types";
import { Switcher } from "@/Components/Switcher";

const attrs = useAttrs();

defineSlots<RadioSlots>();

defineOptions({ inheritAttrs: false });

const props = defineProps<RadioOwnProps>();

const model = defineModel<string | number>();

const modelRef = computed(() => {
  return model.value;
});

const {
  merged,
  dotBind,
  switcher,
  fieldBind,
  inputBind,
  isChecked,
  controlBind,
} = useRadio(
  () => ({ ...attrs, ...props }),
  {
    size: "md",
    rounded: "full",
    color: "primary",
  },
  modelRef,
);

function onChange() {
  if (merged.value.value !== undefined) {
    model.value = merged.value.value;
  }
}
</script>

<template>
  <Switcher :field="switcher">
    <label v-bind="fieldBind" :for="switcher.controlId.value">
      <input v-bind="inputBind" :checked="isChecked" v-on:change="onChange" />

      <span v-bind="controlBind">
        <span v-bind="dotBind" />
      </span>
    </label>
  </Switcher>
</template>
