// packages/react/src/Components/ColorField/ColorField.tsx
// ** Local Imports
import { useResolveMessage } from "@/Adapters/I18n";
import type { ColorFieldProps } from "@/Components/ColorField/colorField.types";
import { useColorField } from "@/Components/ColorField/hooks/useColorField";
import { ColorPicker } from "@/Components/ColorPicker";
import { FieldOverlay } from "@/Components/FieldOverlay";
import { FormField } from "@/Components/FormField";
import { Icon } from "@/Components/Icon";

function ColorField(props: ColorFieldProps) {
  const resolveMessage = useResolveMessage();

  const {
    open,
    fill,
    format,
    overlay,
    colorOnly,
    formField,
    inputBind,
    clearBind,
    swatchBind,
    footerSlot,
    clearValue,
    modelValue,
    showFooter,
    showSwatch,
    clearIconSize,
    showClearIcon,
    swatchFillBind,
    pickerClassName,
    handleOpenChange,
    handlePickerChange,
    handlePickerCancel,
    overlayCustomProps,
    colorPickerCustomProps,
  } = useColorField(props);

  return (
    <>
      <FormField field={formField}>
        <div className="flex min-w-0 flex-1 items-center gap-2">
          {showSwatch ? (
            <span {...swatchBind}>
              <span {...swatchFillBind} />
            </span>
          ) : null}

          <input {...inputBind} />

          {showClearIcon ? (
            <span
              {...clearBind}
              onClick={() => clearValue()}
              aria-label={resolveMessage("Clear")}
              onKeyDown={(event) => {
                if (event.key === "Enter" || event.key === " ") {
                  event.preventDefault();
                  clearValue();
                }
              }}
            >
              <Icon
                icon="clear"
                size={clearIconSize}
                {...props.customProps?.clearIcon}
              />
            </span>
          ) : null}
        </div>
      </FormField>

      <FieldOverlay
        show={open}
        overlay={overlay}
        onShowChange={handleOpenChange}
        customProps={overlayCustomProps}
      >
        <ColorPicker
          fill={fill}
          format={format}
          value={modelValue}
          alpha={colorOnly.alpha}
          showFooter={showFooter}
          readOnly={props.readonly}
          className={pickerClassName}
          swatches={colorOnly.swatches}
          onChange={handlePickerChange}
          onCancel={handlePickerCancel}
          color={formField.merged.color}
          disabled={formField.isDisabled}
          rounded={formField.merged.rounded}
          customProps={colorPickerCustomProps}
          slots={footerSlot ? { footer: footerSlot } : undefined}
        />
      </FieldOverlay>
    </>
  );
}

export default ColorField;

// packages/vue/src/Components/ColorField/ColorField.vue
<script setup lang="ts">
// ** External Imports
import { ref } from "vue";

// ** Local Imports
import { useResolveMessage } from "@/Adapters/I18n";
import type {
  ColorFieldEmits,
  ColorFieldOwnProps,
  ColorFieldSlots,
} from "@/Components/ColorField/colorField.types";
import { useColorField } from "@/Components/ColorField/composables/useColorField";
import { ColorPicker } from "@/Components/ColorPicker";
import { FieldOverlay } from "@/Components/FieldOverlay";
import {
  FORM_FIELD_CHROME_SLOT_NAMES,
  FormField,
} from "@/Components/FormField";
import { Icon } from "@/Components/Icon";
import { presentSlotNames, useOptionalModel } from "@/Utils";

defineSlots<ColorFieldSlots>();

defineOptions({ inheritAttrs: false });

const model = defineModel<null | string>();

const resolveMessage = useResolveMessage();

const emit = defineEmits<ColorFieldEmits>();

const props = withDefaults(defineProps<ColorFieldOwnProps>(), {
  fill: undefined,
  clearable: false,
  showSwatch: true,
  showErrorIcon: true,
  showFooter: undefined,
});

const uncontrolledValue = ref<null | string>(props.defaultValue ?? null);

const value = useOptionalModel(model, uncontrolledValue);

const {
  open,
  fill,
  format,
  overlay,
  colorOnly,
  formField,
  inputBind,
  clearBind,
  swatchBind,
  clearValue,
  modelValue,
  showFooter,
  showSwatch,
  pickerClass,
  clearIconSize,
  showClearIcon,
  swatchFillBind,
  handleOpenChange,
  handlePickerChange,
  handlePickerCancel,
  overlayCustomProps,
  colorPickerCustomProps,
} = useColorField(props, value, emit);
</script>

<template>
  <FormField :field="formField">
    <template
      #[name]="slotData"
      v-for="name in presentSlotNames(FORM_FIELD_CHROME_SLOT_NAMES, $slots)"
    >
      <slot :name="name" v-bind="slotData || {}" />
    </template>

    <div class="flex min-w-0 flex-1 items-center gap-2">
      <span v-if="showSwatch" v-bind="swatchBind">
        <span v-bind="swatchFillBind" />
      </span>

      <input v-bind="inputBind" />

      <span
        v-bind="clearBind"
        v-if="showClearIcon"
        v-on:click="clearValue"
        :aria-label="resolveMessage('Clear')"
        v-on:keydown.enter.prevent="clearValue"
        v-on:keydown.space.prevent="clearValue"
      >
        <Icon
          icon="clear"
          :size="clearIconSize"
          v-bind="props.customProps?.clearIcon"
        />
      </span>
    </div>
  </FormField>

  <FieldOverlay
    :overlay="overlay"
    :model-value="open"
    :custom-props="overlayCustomProps"
    v-on:update:model-value="handleOpenChange"
  >
    <ColorPicker
      :fill="fill"
      :format="format"
      :class="pickerClass"
      :alpha="colorOnly.alpha"
      :model-value="modelValue"
      :show-footer="showFooter"
      :read-only="props.readonly"
      :swatches="colorOnly.swatches"
      v-on:change="handlePickerChange"
      v-on:cancel="handlePickerCancel"
      :color="formField.merged.value.color"
      :custom-props="colorPickerCustomProps"
      :disabled="formField.isDisabled.value"
      :rounded="formField.merged.value.rounded"
    >
      <template #footer="footer" v-if="$slots.footer">
        <slot name="footer" v-bind="footer" />
      </template>
    </ColorPicker>
  </FieldOverlay>
</template>
