// packages/vue/src/Components/Tabs/Tabs.vue
<script setup lang="ts">
// ** External Imports
import { computed, useSlots } from "vue";

// ** Local Imports
import Tab from "@/Components/Tab/Tab.vue";
import TabList from "@/Components/TabList/TabList.vue";
import TabPanel from "@/Components/TabPanel/TabPanel.vue";
import { useTabs } from "@/Components/Tabs/composables/useTabs";
import type {
  TabsEmits,
  TabsOwnProps,
  TabsSlots,
} from "@/Components/Tabs/tabs.types";
import { resolveNamedSlot } from "@/Utils";

defineSlots<TabsSlots>();

const slots = useSlots();

const emit = defineEmits<TabsEmits>();

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<TabsOwnProps>(), {
  keepMounted: true,
});

const model = defineModel<string>({ default: "" });

const { rootBind, tabItems } = useTabs(
  props,
  {
    size: "md",
    variant: "line",
    color: "primary",
    keepMounted: true,
    activation: "automatic",
    orientation: "horizontal",
  },
  model,
  emit,
);

const hasTabItems = computed(() => {
  return tabItems.value.length > 0;
});
</script>

<template>
  <div v-bind="rootBind">
    <template v-if="hasTabItems">
      <TabList v-bind="props.customProps?.tabList">
        <Tab
          :key="item.value"
          :value="item.value"
          v-for="item in tabItems"
          :end-icon="item.endIcon"
          :disabled="item.disabled"
          :start-icon="item.startIcon"
          v-bind="props.customProps?.tab"
        >
          <template #start v-if="item.slots?.start">
            <component :is="item.slots.start" />
          </template>

          <template v-if="typeof item.label === 'string'">
            {{ item.label }}
          </template>

          <component v-else :is="item.label" />

          <template #end v-if="item.slots?.end">
            <component :is="item.slots.end" />
          </template>
        </Tab>
      </TabList>

      <TabPanel
        :key="item.value"
        :value="item.value"
        v-for="item in tabItems"
        :keep-mounted="item.keepMounted"
        v-bind="props.customProps?.tabPanel"
      >
        <component :is="item.panel" />
      </TabPanel>
    </template>

    <component :is="resolveNamedSlot(slots, 'default')" />
  </div>
</template>

// packages/react/src/Components/Tabs/Tabs.tsx
// ** Local Imports
import { Tab } from "@/Components/Tab";
import { TabList } from "@/Components/TabList";
import { TabPanel } from "@/Components/TabPanel";
import { TabsContext } from "@/Components/Tabs/TabsContext";
import { useTabs } from "@/Components/Tabs/hooks/useTabs";
import type { TabsProps } from "@/Components/Tabs/tabs.types";
import { mergeNestedComponentProps } from "@/Utils";

const tabsLibDefaults = {
  size: "md",
  variant: "line",
  color: "primary",
  keepMounted: true,
  activation: "automatic",
  orientation: "horizontal",
} as const;

function Tabs(props: TabsProps) {
  const { children, rootBind, tabItems, contextValue } = useTabs(
    props,
    tabsLibDefaults,
  );

  return (
    <TabsContext.Provider value={contextValue}>
      <div {...rootBind}>
        {tabItems.length > 0 ? (
          <>
            <TabList {...props.customProps?.tabList}>
              {tabItems.map((item) => (
                <Tab
                  key={item.value}
                  value={item.value}
                  endIcon={item.endIcon}
                  disabled={item.disabled}
                  startIcon={item.startIcon}
                  {...mergeNestedComponentProps(props.customProps?.tab, {
                    slots: item.slots,
                  })}
                >
                  {item.label}
                </Tab>
              ))}
            </TabList>

            {tabItems.map((item) => (
              <TabPanel
                key={item.value}
                value={item.value}
                keepMounted={item.keepMounted}
                {...props.customProps?.tabPanel}
              >
                {item.panel}
              </TabPanel>
            ))}
          </>
        ) : null}

        {children}
      </div>
    </TabsContext.Provider>
  );
}

export default Tabs;
