// packages/vue/src/Components/Modal/Modal.vue
<script setup lang="ts">
// ** External Imports
import { computed, useSlots } from "vue";

// ** Local Imports
import { useModal } from "@/Components/Modal/composables/useModal";
import type {
  ModalEmits,
  ModalOwnProps,
  ModalSlots,
} from "@/Components/Modal/modal.types";
import { resolveNamedSlot } from "@/Utils";

defineSlots<ModalSlots>();

const slots = useSlots();

const emit = defineEmits<ModalEmits>();

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<ModalOwnProps>(), {
  persistent: false,
  teleportTo: "body",
  closeOnEscape: true,
  closeOnOverlay: true,
});

const model = defineModel<boolean>({ default: false });

const {
  merged,
  rendered,
  rootBind,
  panelBind,
  overlayBind,
  wrapperBind,
  modalStackId,
} = useModal(
  props,
  {
    size: "md",
    blur: "none",
    teleportTo: "body",
    transition: "fade",
    closeOnEscape: true,
    closeOnOverlay: true,
    align: "middle-center",
  },
  {
    show: model,
    stackId: props.stackId,
    onClose: () => emit("close"),
    onShowChange: (show) => props.onShowChange?.(show),
  },
);

defineExpose({
  stackId: computed(() => props.stackId ?? modalStackId.value),
});

const teleportDisabled = computed(() => {
  return merged.value.teleportTo === false;
});

const teleportTarget = computed(() => {
  if (merged.value.teleportTo === false) {
    return "body";
  }

  return merged.value.teleportTo;
});
</script>

<template>
  <Teleport :to="teleportTarget" :disabled="teleportDisabled">
    <div v-if="rendered" v-bind="rootBind">
      <div aria-hidden="true" v-bind="overlayBind" />

      <div v-bind="wrapperBind">
        <div v-bind="panelBind">
          <component :is="resolveNamedSlot(slots, 'default')" />
        </div>
      </div>
    </div>
  </Teleport>
</template>

// packages/react/src/Components/Modal/Modal.tsx
// ** External Imports
import { createPortal } from "react-dom";

// ** Core Imports
import { resolveModalPortalElement } from "@bridge-ui/core/Utils";

// ** Local Imports
import { useModal } from "@/Components/Modal/hooks/useModal";
import type { ModalProps } from "@/Components/Modal/modal.types";

const modalLibDefaults = {
  size: "md",
  blur: "none",
  teleportTo: "body",
  transition: "fade",
  closeOnEscape: true,
  closeOnOverlay: true,
  align: "middle-center",
} as const;

function ModalShell({
  children,
  rootBind,
  panelBind,
  overlayBind,
  wrapperBind,
  handleOverlayClick,
  handleWrapperClick,
}: ReturnType<typeof useModal> & { children: ModalProps["children"] }) {
  return (
    <div {...rootBind}>
      <div {...overlayBind} aria-hidden="true" onClick={handleOverlayClick} />

      <div {...wrapperBind} onClick={handleWrapperClick}>
        <div {...panelBind}>{children}</div>
      </div>
    </div>
  );
}

function Modal({
  onClose,
  stackId,
  children,
  onShowChange,
  show = false,
  persistent = false,
  teleportTo = "body",
  closeOnEscape = true,
  closeOnOverlay = true,
  ...ownProps
}: ModalProps) {
  const modalState = useModal(
    {
      ...ownProps,
      stackId,
      children,
      persistent,
      teleportTo,
      closeOnEscape,
      closeOnOverlay,
    },
    modalLibDefaults,
    {
      show,
      onClose,
      stackId,
      onShowChange,
    },
  );

  if (!modalState.rendered) {
    return null;
  }

  const shell = <ModalShell {...modalState}>{children}</ModalShell>;

  const portalElement = resolveModalPortalElement(modalState.merged.teleportTo);

  if (portalElement === null) {
    return shell;
  }

  if (typeof document === "undefined") {
    return null;
  }

  return createPortal(shell, portalElement);
}

export default Modal;
