// packages/react/src/Components/DateTimeField/DateTimeField.tsx
// ** Local Imports
import { useResolveMessage } from "@/Adapters/I18n";
import type { DateTimeFieldProps } from "@/Components/DateTimeField/dateTimeField.types";
import { useDateTimeField } from "@/Components/DateTimeField/hooks/useDateTimeField";
import { DateTimePicker } from "@/Components/DateTimePicker";
import { FieldOverlay } from "@/Components/FieldOverlay";
import { FormField } from "@/Components/FormField";
import { Icon } from "@/Components/Icon";

function DateTimeField(props: DateTimeFieldProps) {
  const resolveMessage = useResolveMessage();

  const {
    open,
    daySlot,
    overlay,
    formField,
    inputBind,
    clearBind,
    footerSlot,
    clearValue,
    modelValue,
    showFooter,
    dateTimeOnly,
    clearIconSize,
    showClearIcon,
    pickerClassName,
    handleOpenChange,
    handlePickerChange,
    handlePickerCancel,
    overlayCustomProps,
    dateTimePickerCustomProps,
  } = useDateTimeField(props);

  return (
    <>
      <FormField field={formField}>
        <div className="flex min-w-0 flex-1 items-center gap-1">
          <input {...inputBind} />

          {showClearIcon ? (
            <span
              {...clearBind}
              onClick={() => clearValue()}
              aria-label={resolveMessage("Clear")}
              onKeyDown={(event) => {
                if (event.key === "Enter" || event.key === " ") {
                  event.preventDefault();
                  clearValue();
                }
              }}
            >
              <Icon
                icon="clear"
                size={clearIconSize}
                {...props.customProps?.clearIcon}
              />
            </span>
          ) : null}
        </div>
      </FormField>

      <FieldOverlay
        show={open}
        overlay={overlay}
        onShowChange={handleOpenChange}
        customProps={overlayCustomProps}
      >
        <DateTimePicker
          value={modelValue}
          showFooter={showFooter}
          ampm={dateTimeOnly.ampm}
          readOnly={props.readonly}
          className={pickerClassName}
          onChange={handlePickerChange}
          onCancel={handlePickerCancel}
          error={formField.invalidated}
          maxDate={dateTimeOnly.maxDate}
          maxTime={dateTimeOnly.maxTime}
          minDate={dateTimeOnly.minDate}
          minTime={dateTimeOnly.minTime}
          color={formField.merged.color}
          disabled={formField.isDisabled}
          timeZone={dateTimeOnly.timeZone}
          interval={dateTimeOnly.interval}
          hideYears={dateTimeOnly.hideYears}
          rounded={formField.merged.rounded}
          hideMonths={dateTimeOnly.hideMonths}
          showSeconds={dateTimeOnly.showSeconds}
          defaultView={dateTimeOnly.defaultView}
          startOfWeek={dateTimeOnly.startOfWeek}
          customProps={dateTimePickerCustomProps}
          disableDates={dateTimeOnly.disableDates}
          hideWeekdays={dateTimeOnly.hideWeekdays}
          disableTimes={dateTimeOnly.disableTimes}
          disableYears={dateTimeOnly.disableYears}
          disableMonths={dateTimeOnly.disableMonths}
          hideOutsideDays={dateTimeOnly.hideOutsideDays}
          slots={
            daySlot || footerSlot
              ? { day: daySlot, footer: footerSlot }
              : undefined
          }
        />
      </FieldOverlay>
    </>
  );
}

export default DateTimeField;

// packages/vue/src/Components/DateTimeField/DateTimeField.vue
<script setup lang="ts">
// ** External Imports
import { ref } from "vue";

// ** Local Imports
import { useResolveMessage } from "@/Adapters/I18n";
import { useDateTimeField } from "@/Components/DateTimeField/composables/useDateTimeField";
import type {
  DateTimeFieldEmits,
  DateTimeFieldOwnProps,
  DateTimeFieldSlots,
} from "@/Components/DateTimeField/dateTimeField.types";
import { DateTimePicker } from "@/Components/DateTimePicker";
import { FieldOverlay } from "@/Components/FieldOverlay";
import {
  FORM_FIELD_CHROME_SLOT_NAMES,
  FormField,
} from "@/Components/FormField";
import { Icon } from "@/Components/Icon";
import { presentSlotNames, useOptionalModel } from "@/Utils";

defineSlots<DateTimeFieldSlots>();

defineOptions({ inheritAttrs: false });

const model = defineModel<Date | null>();

const resolveMessage = useResolveMessage();

const emit = defineEmits<DateTimeFieldEmits>();

const props = withDefaults(defineProps<DateTimeFieldOwnProps>(), {
  fill: undefined,
  clearable: false,
  showErrorIcon: true,
  showFooter: undefined,
});

const uncontrolledValue = ref<Date | null>(props.defaultValue ?? null);

const value = useOptionalModel(model, uncontrolledValue);

const {
  open,
  fill,
  overlay,
  formField,
  inputBind,
  clearBind,
  clearValue,
  showFooter,
  modelValue,
  pickerClass,
  dateTimeOnly,
  clearIconSize,
  showClearIcon,
  handleOpenChange,
  handlePickerChange,
  handlePickerCancel,
  overlayCustomProps,
  dateTimePickerCustomProps,
} = useDateTimeField(props, value, emit);
</script>

<template>
  <FormField :field="formField">
    <template
      #[name]="slotData"
      v-for="name in presentSlotNames(FORM_FIELD_CHROME_SLOT_NAMES, $slots)"
    >
      <slot :name="name" v-bind="slotData || {}" />
    </template>

    <div class="flex min-w-0 flex-1 items-center gap-1">
      <input v-bind="inputBind" />

      <span
        v-bind="clearBind"
        v-if="showClearIcon"
        v-on:click="clearValue"
        :aria-label="resolveMessage('Clear')"
        v-on:keydown.enter.prevent="clearValue"
        v-on:keydown.space.prevent="clearValue"
      >
        <Icon
          icon="clear"
          :size="clearIconSize"
          v-bind="props.customProps?.clearIcon"
        />
      </span>
    </div>
  </FormField>

  <FieldOverlay
    :overlay="overlay"
    :model-value="open"
    :custom-props="overlayCustomProps"
    v-on:update:model-value="handleOpenChange"
  >
    <DateTimePicker
      :fill="fill"
      :value="modelValue"
      :class="pickerClass"
      :ampm="dateTimeOnly.ampm"
      :show-footer="showFooter"
      :read-only="props.readonly"
      :max-date="dateTimeOnly.maxDate"
      :min-date="dateTimeOnly.minDate"
      :max-time="dateTimeOnly.maxTime"
      :min-time="dateTimeOnly.minTime"
      v-on:change="handlePickerChange"
      v-on:cancel="handlePickerCancel"
      :interval="dateTimeOnly.interval"
      :time-zone="dateTimeOnly.timeZone"
      :hide-years="dateTimeOnly.hideYears"
      :error="formField.invalidated.value"
      :color="formField.merged.value.color"
      :hide-months="dateTimeOnly.hideMonths"
      :disabled="formField.isDisabled.value"
      :show-seconds="dateTimeOnly.showSeconds"
      :default-view="dateTimeOnly.defaultView"
      :start-of-week="dateTimeOnly.startOfWeek"
      :custom-props="dateTimePickerCustomProps"
      :rounded="formField.merged.value.rounded"
      :disable-dates="dateTimeOnly.disableDates"
      :hide-weekdays="dateTimeOnly.hideWeekdays"
      :disable-times="dateTimeOnly.disableTimes"
      :disable-years="dateTimeOnly.disableYears"
      :disable-months="dateTimeOnly.disableMonths"
      :hide-outside-days="dateTimeOnly.hideOutsideDays"
    >
      <template #day="cell">
        <slot name="day" v-bind="cell">{{ cell.label }}</slot>
      </template>

      <template #footer="footer" v-if="$slots.footer">
        <slot name="footer" v-bind="footer" />
      </template>
    </DateTimePicker>
  </FieldOverlay>
</template>
