// packages/vue/src/Components/Badge/Badge.vue
<script setup lang="ts">
// ** Local Imports
import type { BadgeOwnProps } from "@/Components/Badge/badge.types";
import { useBadge } from "@/Components/Badge/composables/useBadge";

defineOptions({ inheritAttrs: false });

const props = defineProps<BadgeOwnProps>();

const { rootBind } = useBadge(props, {
  size: "sm",
  rounded: "md",
  variant: "flat",
  color: "primary",
  density: "default",
});
</script>

<template>
  <span v-bind="rootBind">
    <slot />
  </span>
</template>

// packages/react/src/Components/Badge/Badge.tsx
// ** Local Imports
import type { BadgeProps } from "@/Components/Badge";
import { useBadge } from "@/Components/Badge";

function Badge(props: BadgeProps) {
  const { children, rootBind } = useBadge(props, {
    size: "sm",
    rounded: "md",
    variant: "flat",
    color: "primary",
    density: "default",
  });

  return <span {...rootBind}>{children}</span>;
}

export default Badge;
