// packages/react/src/Components/Menu/Menu.tsx
// ** External Imports
import { Fragment } from "react";
import { createPortal } from "react-dom";

// ** Core Imports
import { hasDocument, resolveModalPortalElement } from "@bridge-ui/core/Utils";

// ** Local Imports
import { useMenu } from "@/Components/Menu/hooks/useMenu";
import type { MenuProps } from "@/Components/Menu/menu.types";

const menuLibDefaults = {
  offset: 4,
  shadow: "md",
  rounded: "md",
  strategy: "fixed",
  teleportTo: "body",
  closeOnEscape: true,
  closeOnClickAway: true,
  disableScrollLock: true,
  placement: "bottom-start",
} as const;

type MenuShellProps = ReturnType<typeof useMenu>;

function MenuShell({
  slots,
  merged,
  mounted,
  children,
  rootBind,
  hasTrigger,
  isPortaled,
  triggerBind,
  contentBind,
}: MenuShellProps) {
  const panel = mounted ? <div {...contentBind}>{children}</div> : null;

  let content = panel;

  if (panel && isPortaled) {
    if (!hasDocument()) {
      content = null;
    } else {
      const portalElement = resolveModalPortalElement(merged.teleportTo);

      content =
        portalElement === null ? panel : createPortal(panel, portalElement);
    }
  }

  if (!hasTrigger) {
    return <Fragment>{content}</Fragment>;
  }

  return (
    <div {...rootBind}>
      <div {...triggerBind}>{slots?.trigger}</div>

      {content}
    </div>
  );
}

function Menu({
  onClose,
  children,
  onShowChange,
  show = false,
  ...ownProps
}: MenuProps) {
  const menuState = useMenu(
    {
      ...ownProps,
      children,
    },
    menuLibDefaults,
    {
      show,
      onClose,
      onShowChange,
    },
  );

  return <MenuShell {...menuState} />;
}

export default Menu;

// packages/vue/src/Components/Menu/Menu.vue
<script setup lang="ts">
// ** External Imports
import { computed, useSlots } from "vue";

// ** Local Imports
import { useMenu } from "@/Components/Menu/composables/useMenu";
import type {
  MenuEmits,
  MenuOwnProps,
  MenuSlots,
} from "@/Components/Menu/menu.types";
import { hasNamedSlot, resolveNamedSlot } from "@/Utils";

defineSlots<MenuSlots>();

const slots = useSlots();

const emit = defineEmits<MenuEmits>();

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<MenuOwnProps>(), {
  offset: 4,
  shadow: "md",
  rounded: "md",
  anchorEl: null,
  strategy: "fixed",
  persistent: false,
  teleportTo: "body",
  keepMounted: false,
  closeOnEscape: true,
  closeOnClickAway: true,
  disableAutoFocus: false,
  disableScrollLock: true,
  placement: "bottom-start",
});

const model = defineModel<boolean>({ default: false });

const {
  merged,
  mounted,
  rootBind,
  triggerBind,
  contentBind,
  setTriggerRef,
  setContentRef,
} = useMenu(
  props,
  {
    offset: 4,
    shadow: "md",
    rounded: "md",
    strategy: "fixed",
    teleportTo: "body",
    closeOnEscape: true,
    closeOnClickAway: true,
    disableScrollLock: true,
    placement: "bottom-start",
  },
  {
    show: model,
    onClose: () => emit("close"),
    onShowChange: (show) => props.onShowChange?.(show),
  },
);

const hasTrigger = computed(() => {
  return hasNamedSlot(slots, "trigger");
});

const teleportDisabled = computed(() => {
  return merged.value.teleportTo === false;
});

const teleportTarget = computed(() => {
  if (merged.value.teleportTo === false) {
    return "body";
  }

  return merged.value.teleportTo;
});
</script>

<template>
  <div v-if="hasTrigger" v-bind="rootBind">
    <div :ref="setTriggerRef" v-bind="triggerBind">
      <component :is="resolveNamedSlot(slots, 'trigger')" />
    </div>
  </div>

  <Teleport :to="teleportTarget" :disabled="teleportDisabled">
    <div v-if="mounted" :ref="setContentRef" v-bind="contentBind">
      <component :is="resolveNamedSlot(slots, 'default')" />
    </div>
  </Teleport>
</template>
