// packages/vue/src/Components/CalendarYear/CalendarYear.vue
<script setup lang="ts">
// ** Local Imports
import type {
  CalendarYearEmits,
  CalendarYearOwnProps,
} from "@/Components/CalendarYear/calendarYear.types";
import { useCalendarYear } from "@/Components/CalendarYear/composables/useCalendarYear";

defineOptions({ inheritAttrs: false });

const emit = defineEmits<CalendarYearEmits>();

const props = defineProps<CalendarYearOwnProps>();

const { years, rootBind, gridBind, getYearBind } = useCalendarYear(
  props,
  { pageSize: 15, rounded: "md", color: "primary" },
  emit,
);
</script>

<template>
  <div v-bind="rootBind">
    <div v-bind="gridBind">
      <button :key="cell.year" v-for="cell in years" v-bind="getYearBind(cell)">
        {{ cell.label }}
      </button>
    </div>
  </div>
</template>

// packages/react/src/Components/CalendarYear/CalendarYear.tsx
// ** Local Imports
import type { CalendarYearProps } from "@/Components/CalendarYear/calendarYear.types";
import { useCalendarYear } from "@/Components/CalendarYear/hooks/useCalendarYear";

function CalendarYear(props: CalendarYearProps) {
  const { years, rootBind, gridBind, getYearBind } = useCalendarYear(props, {
    pageSize: 15,
    rounded: "md",
    color: "primary",
  });

  return (
    <div {...rootBind}>
      <div {...gridBind}>
        {years.map((cell) => (
          <button key={cell.year} {...getYearBind(cell)}>
            {cell.label}
          </button>
        ))}
      </div>
    </div>
  );
}

export default CalendarYear;
