// packages/react/src/Components/FormField/FilledFormField.tsx
import type { ReactNode } from "react";

// ** Local Imports
import type { UseFormFieldReturn } from "@/Components/FormField/hooks/useFormField";
import { Icon } from "@/Components/Icon";
import {
  hasNamedSlot,
  hasSlotOrProp,
  isPropPresent,
  resolveSlotOrProp,
} from "@/Utils";

type FilledFormFieldProps = {
  api: UseFormFieldReturn;
  children?: ReactNode;
};

function FilledFormField({ api, children }: FilledFormFieldProps) {
  return (
    <div
      {...api.rootBind}
      data-invalid={api.invalidated || undefined}
      aria-disabled={api.isDisabled || undefined}
      aria-readonly={api.isReadonly || undefined}
    >
      {(hasSlotOrProp(api.slots, "label", api.merged.label) ||
        hasSlotOrProp(api.slots, "corner", api.merged.corner)) && (
        <div {...api.headerBind}>
          {hasSlotOrProp(api.slots, "label", api.merged.label) && (
            <label htmlFor={api.controlId} {...api.labelBind}>
              {resolveSlotOrProp({
                name: "label",
                slots: api.slots,
                fallback: api.merged.label,
              })}

              {api.merged.required && <span {...api.requiredBind}>*</span>}
            </label>
          )}

          {hasSlotOrProp(api.slots, "corner", api.merged.corner) && (
            <span {...api.cornerBind}>
              {resolveSlotOrProp({
                name: "corner",
                slots: api.slots,
                fallback: api.merged.corner,
              })}
            </span>
          )}
        </div>
      )}

      <div {...api.containerBind}>
        {hasNamedSlot(api.slots, "start") ? (
          <div {...api.startSlotBind}>{api.slots?.start}</div>
        ) : isPropPresent(api.merged.start) ? (
          <div {...api.startBind}>{api.merged.start}</div>
        ) : (
          api.merged.startIcon && (
            <div {...api.startBind}>
              <Icon
                {...api.startIconBind}
                size={api.merged.size}
                icon={api.merged.startIcon}
              />
            </div>
          )
        )}

        {children}

        {hasNamedSlot(api.slots, "end") ? (
          <div {...api.endSlotBind}>{api.slots?.end}</div>
        ) : isPropPresent(api.merged.end) ? (
          <div {...api.endBind}>{api.merged.end}</div>
        ) : api.invalidated && api.merged.withErrorIcon !== false ? (
          <div {...api.endBind}>
            <Icon
              {...api.endIconBind}
              icon={api.errorIcon}
              size={api.merged.size}
            />
          </div>
        ) : (
          api.merged.endIcon && (
            <div {...api.endBind}>
              <Icon
                {...api.endIconBind}
                size={api.merged.size}
                icon={api.merged.endIcon}
              />
            </div>
          )
        )}

        {api.showLoading && <div {...api.loadingBind} />}
      </div>

      {!api.invalidated &&
        hasSlotOrProp(api.slots, "description", api.merged.description) && (
          <p {...api.descriptionBind} id={`${api.controlId}-description`}>
            {resolveSlotOrProp({
              slots: api.slots,
              name: "description",
              fallback: api.merged.description,
            })}
          </p>
        )}

      {!api.merged.withoutErrorMessage && (
        <p
          {...api.errorBind}
          id={`${api.controlId}-error`}
          aria-hidden={api.showErrorMessageContent ? undefined : true}
        >
          {api.showErrorMessageContent &&
            resolveSlotOrProp({
              slots: api.slots,
              name: "errorMessage",
              fallback: api.merged.errorMessage,
            })}
        </p>
      )}
    </div>
  );
}

export default FilledFormField;

// packages/vue/src/Components/FormField/FilledFormField.vue
<script setup lang="ts">
// ** Local Imports
import { type UseFormFieldReturn } from "@/Components/FormField/composables/useFormField";
import { Icon } from "@/Components/Icon";
import {
  hasNamedSlot,
  hasSlotOrProp,
  isPropPresent,
  resolveNamedSlot,
  resolveSlotOrProp,
} from "@/Utils";

defineProps<{
  api: UseFormFieldReturn;
}>();
</script>

<template>
  <div
    v-bind="api.rootBind.value"
    :data-invalid="api.invalidated.value || undefined"
    :aria-disabled="api.isDisabled.value || undefined"
    :aria-readonly="api.isReadonly.value || undefined"
  >
    <div
      v-bind="api.headerBind.value"
      v-if="
        hasSlotOrProp(api.slots, 'label', api.merged.value.label) ||
        hasSlotOrProp(api.slots, 'corner', api.merged.value.corner)
      "
    >
      <label
        :for="api.controlId.value"
        v-bind="api.labelBind.value"
        v-if="hasSlotOrProp(api.slots, 'label', api.merged.value.label)"
      >
        <component
          :is="resolveSlotOrProp(api.slots, 'label', api.merged.value.label)"
        />

        <span v-bind="api.requiredBind.value" v-if="api.merged.value.required">
          *
        </span>
      </label>

      <span
        v-bind="api.cornerBind.value"
        v-if="hasSlotOrProp(api.slots, 'corner', api.merged.value.corner)"
      >
        <component
          :is="resolveSlotOrProp(api.slots, 'corner', api.merged.value.corner)"
        />
      </span>
    </div>

    <div v-bind="api.containerBind.value">
      <div
        v-bind="api.startSlotBind.value"
        v-if="hasNamedSlot(api.slots, 'start')"
      >
        <component :is="resolveNamedSlot(api.slots, 'start')" />
      </div>

      <div
        v-bind="api.startBind.value"
        v-else-if="isPropPresent(api.merged.value.start)"
      >
        {{ api.merged.value.start }}
      </div>

      <div v-bind="api.startBind.value" v-else-if="api.merged.value.startIcon">
        <Icon
          :size="api.merged.value.size"
          v-bind="api.startIconBind.value"
          :icon="api.merged.value.startIcon"
        />
      </div>

      <slot />

      <div v-bind="api.endSlotBind.value" v-if="hasNamedSlot(api.slots, 'end')">
        <component :is="resolveNamedSlot(api.slots, 'end')" />
      </div>

      <div
        v-bind="api.endBind.value"
        v-else-if="isPropPresent(api.merged.value.end)"
      >
        {{ api.merged.value.end }}
      </div>

      <div
        v-bind="api.endBind.value"
        v-else-if="
          api.invalidated.value && api.merged.value.withErrorIcon !== false
        "
      >
        <Icon
          :icon="api.errorIcon.value"
          :size="api.merged.value.size"
          v-bind="api.endIconBind.value"
        />
      </div>

      <div v-bind="api.endBind.value" v-else-if="api.merged.value.endIcon">
        <Icon
          :size="api.merged.value.size"
          v-bind="api.endIconBind.value"
          :icon="api.merged.value.endIcon"
        />
      </div>

      <div v-if="api.showLoading.value" v-bind="api.loadingBind.value" />
    </div>

    <p
      v-bind="api.descriptionBind.value"
      :id="`${api.controlId.value}-description`"
      v-if="
        !api.invalidated.value &&
        hasSlotOrProp(api.slots, 'description', api.merged.value.description)
      "
    >
      <component
        :is="
          resolveSlotOrProp(
            api.slots,
            'description',
            api.merged.value.description,
          )
        "
      />
    </p>

    <p
      v-bind="api.errorBind.value"
      :id="`${api.controlId.value}-error`"
      v-if="!api.merged.value.withoutErrorMessage"
      :aria-hidden="api.showErrorMessageContent.value ? undefined : true"
    >
      <component
        v-if="api.showErrorMessageContent.value"
        :is="
          resolveSlotOrProp(
            api.slots,
            'errorMessage',
            api.merged.value.errorMessage,
          )
        "
      />
    </p>
  </div>
</template>
