// packages/react/src/Components/FormField/FormField.tsx
// ** Local Imports
import type { FormFieldProps } from "@/Components/FormField/formField.types";
import { useFormField } from "@/Components/FormField/hooks/useFormField";
import { hasSlotOrProp, resolveSlotOrProp } from "@/Utils";

function FormField(props: FormFieldProps) {
  const { field, ...rest } = props;

  const local = useFormField(rest, {
    size: "md",
  });

  const {
    slots,
    merged,
    children,
    rootBind,
    controlId,
    errorBind,
    labelBind,
    cornerBind,
    headerBind,
    isDisabled,
    isReadonly,
    invalidated,
    requiredBind,
    descriptionBind,
  } = field ?? local;

  return (
    <div
      {...rootBind}
      data-invalid={invalidated || undefined}
      aria-disabled={isDisabled || undefined}
      aria-readonly={isReadonly || undefined}
    >
      {(hasSlotOrProp(slots, "label", merged.label) ||
        hasSlotOrProp(slots, "corner", merged.corner)) && (
        <div {...headerBind}>
          {hasSlotOrProp(slots, "label", merged.label) && (
            <label {...labelBind} htmlFor={controlId}>
              {resolveSlotOrProp({
                slots,
                name: "label",
                fallback: merged.label,
              })}

              {merged.required && <span {...requiredBind}>*</span>}
            </label>
          )}

          {hasSlotOrProp(slots, "corner", merged.corner) && (
            <span {...cornerBind}>
              {resolveSlotOrProp({
                slots,
                name: "corner",
                fallback: merged.corner,
              })}
            </span>
          )}
        </div>
      )}

      {children}

      {!invalidated &&
        hasSlotOrProp(slots, "description", merged.description) && (
          <p {...descriptionBind} id={`${controlId}-description`}>
            {resolveSlotOrProp({
              slots,
              name: "description",
              fallback: merged.description,
            })}
          </p>
        )}

      {hasSlotOrProp(slots, "errorMessage", merged.errorMessage) && (
        <p {...errorBind} id={`${controlId}-error`}>
          {resolveSlotOrProp({
            slots,
            name: "errorMessage",
            fallback: merged.errorMessage,
          })}
        </p>
      )}
    </div>
  );
}

export default FormField;

// packages/vue/src/Components/FormField/FormField.vue
<script setup lang="ts">
// ** External Imports
import { computed } from "vue";

// ** Local Imports
import { useFormField } from "@/Components/FormField/composables/useFormField";
import type {
  FormFieldOwnProps,
  FormFieldSlots,
} from "@/Components/FormField/formField.types";
import { hasSlotOrProp, resolveSlotOrProp } from "@/Utils";

defineSlots<FormFieldSlots>();

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<FormFieldOwnProps>(), {});

const formFieldProps = computed(() => {
  const { field: _field, ...rest } = props;

  return rest;
});

const local = useFormField(formFieldProps, {
  size: "md",
});

const {
  slots,
  merged,
  rootBind,
  controlId,
  errorBind,
  labelBind,
  cornerBind,
  headerBind,
  isDisabled,
  isReadonly,
  invalidated,
  requiredBind,
  descriptionBind,
} = props.field ?? local;
</script>

<template>
  <div
    v-bind="rootBind"
    :data-invalid="invalidated || undefined"
    :aria-disabled="isDisabled || undefined"
    :aria-readonly="isReadonly || undefined"
  >
    <div
      v-bind="headerBind"
      v-if="
        hasSlotOrProp(slots, 'label', merged.label) ||
        hasSlotOrProp(slots, 'corner', merged.corner)
      "
    >
      <label
        :for="controlId"
        v-bind="labelBind"
        v-if="hasSlotOrProp(slots, 'label', merged.label)"
      >
        <component :is="resolveSlotOrProp(slots, 'label', merged.label)" />

        <span v-if="merged.required" v-bind="requiredBind">*</span>
      </label>

      <span
        v-bind="cornerBind"
        v-if="hasSlotOrProp(slots, 'corner', merged.corner)"
      >
        <component :is="resolveSlotOrProp(slots, 'corner', merged.corner)" />
      </span>
    </div>

    <slot />

    <p
      v-bind="descriptionBind"
      :id="`${controlId}-description`"
      v-if="
        !invalidated && hasSlotOrProp(slots, 'description', merged.description)
      "
    >
      <component
        :is="resolveSlotOrProp(slots, 'description', merged.description)"
      />
    </p>

    <p
      v-bind="errorBind"
      :id="`${controlId}-error`"
      v-if="hasSlotOrProp(slots, 'errorMessage', merged.errorMessage)"
    >
      <component
        :is="resolveSlotOrProp(slots, 'errorMessage', merged.errorMessage)"
      />
    </p>
  </div>
</template>
