// packages/react/src/Components/FormField/NotchedFormField.tsx
import type { ReactNode } from "react";

// ** Local Imports
import FormFieldLabel from "@/Components/FormField/FormFieldLabel";
import type { UseFormFieldReturn } from "@/Components/FormField/hooks/useFormField";
import { Icon } from "@/Components/Icon";
import { hasNamedSlot, hasSlotOrProp, isPropPresent } from "@/Utils";

type NotchedFormFieldProps = {
  api: UseFormFieldReturn;
  children?: ReactNode;
};

function NotchedFormField({ api, children }: NotchedFormFieldProps) {
  return (
    <div
      {...api.rootBind}
      data-invalid={api.invalidated || undefined}
      aria-disabled={api.isDisabled || undefined}
      aria-readonly={api.isReadonly || undefined}
    >
      <div {...api.containerBind}>
        {api.hasInsetLabelRow && (
          <div {...api.insetLabelRowBind}>
            <FormFieldLabel api={api} />

            {hasSlotOrProp(api.slots, "corner", api.merged.corner) && (
              <span {...api.cornerBind}>
                {hasNamedSlot(api.slots, "corner")
                  ? api.slots?.corner
                  : api.merged.corner}
              </span>
            )}
          </div>
        )}

        <div className="flex min-h-0 w-full flex-1 items-stretch gap-x-2">
          {hasNamedSlot(api.slots, "start") ? (
            <div {...api.startSlotBind}>{api.slots?.start}</div>
          ) : isPropPresent(api.merged.start) ? (
            <div {...api.startBind}>{api.merged.start}</div>
          ) : (
            api.merged.startIcon && (
              <div {...api.startBind}>
                <Icon
                  {...api.startIconBind}
                  size={api.merged.size}
                  icon={api.merged.startIcon}
                />
              </div>
            )
          )}

          {children}

          {hasNamedSlot(api.slots, "end") ? (
            <div {...api.endSlotBind}>{api.slots?.end}</div>
          ) : isPropPresent(api.merged.end) ? (
            <div {...api.endBind}>{api.merged.end}</div>
          ) : api.invalidated && api.merged.showErrorIcon !== false ? (
            <div {...api.endBind}>
              <Icon
                {...api.endIconBind}
                icon={api.errorIcon}
                size={api.merged.size}
              />
            </div>
          ) : (
            api.merged.endIcon && (
              <div {...api.endBind}>
                <Icon
                  {...api.endIconBind}
                  size={api.merged.size}
                  icon={api.merged.endIcon}
                />
              </div>
            )
          )}
        </div>
      </div>

      {!api.invalidated &&
        hasSlotOrProp(api.slots, "description", api.merged.description) && (
          <p {...api.descriptionBind} id={`${api.controlId}-description`}>
            {hasNamedSlot(api.slots, "description")
              ? api.slots?.description
              : api.merged.description}
          </p>
        )}

      {!api.merged.hideErrorMessage && (
        <p
          {...api.errorBind}
          id={`${api.controlId}-error`}
          aria-hidden={api.showErrorMessageContent ? undefined : true}
        >
          {api.showErrorMessageContent &&
            (hasNamedSlot(api.slots, "errorMessage")
              ? api.slots?.errorMessage
              : isPropPresent(api.merged.errorMessage)
                ? api.merged.errorMessage
                : null)}
        </p>
      )}
    </div>
  );
}

export default NotchedFormField;

// packages/vue/src/Components/FormField/NotchedFormField.vue
<script setup lang="ts">
// ** Local Imports
import FormFieldLabel from "@/Components/FormField/FormFieldLabel.vue";
import { type UseFormFieldReturn } from "@/Components/FormField/composables/useFormField";
import { Icon } from "@/Components/Icon";
import {
  hasNamedSlot,
  hasSlotOrProp,
  isPropPresent,
  resolveNamedSlot,
  resolveSlotOrProp,
} from "@/Utils";

defineProps<{
  api: UseFormFieldReturn;
}>();
</script>

<template>
  <div
    v-bind="api.rootBind.value"
    :data-invalid="api.invalidated.value || undefined"
    :aria-disabled="api.isDisabled.value || undefined"
    :aria-readonly="api.isReadonly.value || undefined"
  >
    <div v-bind="api.containerBind.value">
      <div
        v-if="api.hasInsetLabelRow.value"
        v-bind="api.insetLabelRowBind.value"
      >
        <FormFieldLabel :api="api" />

        <span
          v-bind="api.cornerBind.value"
          v-if="hasSlotOrProp(api.slots, 'corner', api.merged.value.corner)"
        >
          <component
            :is="
              resolveSlotOrProp(api.slots, 'corner', api.merged.value.corner)
            "
          />
        </span>
      </div>

      <div class="flex min-h-0 w-full flex-1 items-stretch gap-x-2">
        <div
          v-bind="api.startSlotBind.value"
          v-if="hasNamedSlot(api.slots, 'start')"
        >
          <component :is="resolveNamedSlot(api.slots, 'start')" />
        </div>

        <div
          v-bind="api.startBind.value"
          v-else-if="isPropPresent(api.merged.value.start)"
        >
          {{ api.merged.value.start }}
        </div>

        <div
          v-bind="api.startBind.value"
          v-else-if="api.merged.value.startIcon"
        >
          <Icon
            :size="api.merged.value.size"
            v-bind="api.startIconBind.value"
            :icon="api.merged.value.startIcon"
          />
        </div>

        <slot />

        <div
          v-bind="api.endSlotBind.value"
          v-if="hasNamedSlot(api.slots, 'end')"
        >
          <component :is="resolveNamedSlot(api.slots, 'end')" />
        </div>

        <div
          v-bind="api.endBind.value"
          v-else-if="isPropPresent(api.merged.value.end)"
        >
          {{ api.merged.value.end }}
        </div>

        <div
          v-bind="api.endBind.value"
          v-else-if="
            api.invalidated.value && api.merged.value.showErrorIcon !== false
          "
        >
          <Icon
            :icon="api.errorIcon.value"
            :size="api.merged.value.size"
            v-bind="api.endIconBind.value"
          />
        </div>

        <div v-bind="api.endBind.value" v-else-if="api.merged.value.endIcon">
          <Icon
            :size="api.merged.value.size"
            v-bind="api.endIconBind.value"
            :icon="api.merged.value.endIcon"
          />
        </div>
      </div>
    </div>

    <p
      v-bind="api.descriptionBind.value"
      :id="`${api.controlId.value}-description`"
      v-if="
        !api.invalidated.value &&
        hasSlotOrProp(api.slots, 'description', api.merged.value.description)
      "
    >
      <component
        :is="
          resolveSlotOrProp(
            api.slots,
            'description',
            api.merged.value.description,
          )
        "
      />
    </p>

    <p
      v-bind="api.errorBind.value"
      :id="`${api.controlId.value}-error`"
      v-if="!api.merged.value.hideErrorMessage"
      :aria-hidden="api.showErrorMessageContent.value ? undefined : true"
    >
      <component
        v-if="api.showErrorMessageContent.value"
        :is="
          resolveSlotOrProp(
            api.slots,
            'errorMessage',
            api.merged.value.errorMessage,
          )
        "
      />
    </p>
  </div>
</template>
