// packages/react/src/Components/FormField/UnderlinedFormField.tsx
import type { ReactNode } from "react";

// ** Local Imports
import FormFieldLabel from "@/Components/FormField/FormFieldLabel";
import type { UseFormFieldReturn } from "@/Components/FormField/hooks/useFormField";
import { Icon } from "@/Components/Icon";
import {
  hasNamedSlot,
  hasSlotOrProp,
  isPropPresent,
  resolveSlotOrProp,
} from "@/Utils";

type UnderlinedFormFieldProps = {
  api: UseFormFieldReturn;
  children?: ReactNode;
};

function UnderlinedFormField({ api, children }: UnderlinedFormFieldProps) {
  return (
    <div
      {...api.rootBind}
      data-invalid={api.invalidated || undefined}
      aria-disabled={api.isDisabled || undefined}
      aria-readonly={api.isReadonly || undefined}
    >
      {(hasSlotOrProp(api.slots, "label", api.merged.label) ||
        hasSlotOrProp(api.slots, "corner", api.merged.corner)) && (
        <div {...api.headerBind}>
          <FormFieldLabel api={api} />

          {hasSlotOrProp(api.slots, "corner", api.merged.corner) && (
            <span {...api.cornerBind}>
              {resolveSlotOrProp({
                name: "corner",
                slots: api.slots,
                fallback: api.merged.corner,
              })}
            </span>
          )}
        </div>
      )}

      <div {...api.containerBind}>
        {hasNamedSlot(api.slots, "start") ? (
          <div {...api.startSlotBind}>{api.slots?.start}</div>
        ) : isPropPresent(api.merged.start) ? (
          <div {...api.startBind}>{api.merged.start}</div>
        ) : (
          api.merged.startIcon && (
            <div {...api.startBind}>
              <Icon
                {...api.startIconBind}
                size={api.merged.size}
                icon={api.merged.startIcon}
              />
            </div>
          )
        )}

        {children}

        {hasNamedSlot(api.slots, "end") ? (
          <div {...api.endSlotBind}>{api.slots?.end}</div>
        ) : isPropPresent(api.merged.end) ? (
          <div {...api.endBind}>{api.merged.end}</div>
        ) : api.invalidated && api.merged.showErrorIcon !== false ? (
          <div {...api.endBind}>
            <Icon
              {...api.endIconBind}
              icon={api.errorIcon}
              size={api.merged.size}
            />
          </div>
        ) : (
          api.merged.endIcon && (
            <div {...api.endBind}>
              <Icon
                {...api.endIconBind}
                size={api.merged.size}
                icon={api.merged.endIcon}
              />
            </div>
          )
        )}
      </div>

      {!api.invalidated &&
        hasSlotOrProp(api.slots, "description", api.merged.description) && (
          <p {...api.descriptionBind} id={`${api.controlId}-description`}>
            {resolveSlotOrProp({
              slots: api.slots,
              name: "description",
              fallback: api.merged.description,
            })}
          </p>
        )}

      {!api.merged.hideErrorMessage && (
        <p
          {...api.errorBind}
          id={`${api.controlId}-error`}
          aria-hidden={api.showErrorMessageContent ? undefined : true}
        >
          {api.showErrorMessageContent &&
            resolveSlotOrProp({
              slots: api.slots,
              name: "errorMessage",
              fallback: api.merged.errorMessage,
            })}
        </p>
      )}
    </div>
  );
}

export default UnderlinedFormField;

// packages/vue/src/Components/FormField/UnderlinedFormField.vue
<script setup lang="ts">
// ** Local Imports
import FormFieldLabel from "@/Components/FormField/FormFieldLabel.vue";
import { type UseFormFieldReturn } from "@/Components/FormField/composables/useFormField";
import { Icon } from "@/Components/Icon";
import {
  hasNamedSlot,
  hasSlotOrProp,
  isPropPresent,
  SlotOrProp,
} from "@/Utils";

defineProps<{
  api: UseFormFieldReturn;
}>();
</script>

<template>
  <div
    v-bind="api.rootBind.value"
    :data-invalid="api.invalidated.value || undefined"
    :aria-disabled="api.isDisabled.value || undefined"
    :aria-readonly="api.isReadonly.value || undefined"
  >
    <div
      v-bind="api.headerBind.value"
      v-if="
        hasSlotOrProp(api.slots, 'label', api.merged.value.label) ||
        hasSlotOrProp(api.slots, 'corner', api.merged.value.corner)
      "
    >
      <FormFieldLabel :api="api" />

      <span
        v-bind="api.cornerBind.value"
        v-if="hasSlotOrProp(api.slots, 'corner', api.merged.value.corner)"
      >
        <SlotOrProp
          name="corner"
          :slots="api.slots"
          :fallback="api.merged.value.corner"
        />
      </span>
    </div>

    <div v-bind="api.containerBind.value">
      <div
        v-bind="api.startSlotBind.value"
        v-if="hasNamedSlot(api.slots, 'start')"
      >
        <SlotOrProp name="start" :slots="api.slots" />
      </div>

      <div
        v-bind="api.startBind.value"
        v-else-if="isPropPresent(api.merged.value.start)"
      >
        {{ api.merged.value.start }}
      </div>

      <div v-bind="api.startBind.value" v-else-if="api.merged.value.startIcon">
        <Icon
          :size="api.merged.value.size"
          v-bind="api.startIconBind.value"
          :icon="api.merged.value.startIcon"
        />
      </div>

      <slot />

      <div v-bind="api.endSlotBind.value" v-if="hasNamedSlot(api.slots, 'end')">
        <SlotOrProp name="end" :slots="api.slots" />
      </div>

      <div
        v-bind="api.endBind.value"
        v-else-if="isPropPresent(api.merged.value.end)"
      >
        {{ api.merged.value.end }}
      </div>

      <div
        v-bind="api.endBind.value"
        v-else-if="
          api.invalidated.value && api.merged.value.showErrorIcon !== false
        "
      >
        <Icon
          :icon="api.errorIcon.value"
          :size="api.merged.value.size"
          v-bind="api.endIconBind.value"
        />
      </div>

      <div v-bind="api.endBind.value" v-else-if="api.merged.value.endIcon">
        <Icon
          :size="api.merged.value.size"
          v-bind="api.endIconBind.value"
          :icon="api.merged.value.endIcon"
        />
      </div>
    </div>

    <p
      v-bind="api.descriptionBind.value"
      :id="`${api.controlId.value}-description`"
      v-if="
        !api.invalidated.value &&
        hasSlotOrProp(api.slots, 'description', api.merged.value.description)
      "
    >
      <SlotOrProp
        name="description"
        :slots="api.slots"
        :fallback="api.merged.value.description"
      />
    </p>

    <p
      v-bind="api.errorBind.value"
      :id="`${api.controlId.value}-error`"
      v-if="!api.merged.value.hideErrorMessage"
      :aria-hidden="api.showErrorMessageContent.value ? undefined : true"
    >
      <SlotOrProp
        :slots="api.slots"
        name="errorMessage"
        v-if="api.showErrorMessageContent.value"
        :fallback="api.merged.value.errorMessage"
      />
    </p>
  </div>
</template>
