// packages/react/src/Components/OtpField/OtpField.tsx
// ** Local Imports
import { useOtpField } from "@/Components/OtpField/hooks/useOtpField";
import type { OtpFieldProps } from "@/Components/OtpField/otpField.types";
import OtpFieldLabel from "@/Components/OtpField/OtpFieldLabel";
import { hasSlotOrProp, resolveSlotOrProp } from "@/Utils";

function OtpField(props: OtpFieldProps) {
  const api = useOtpField(props);

  const {
    slots,
    merged,
    digits,
    length,
    pinBind,
    rootBind,
    errorBind,
    groupBind,
    inputBind,
    setPinRef,
    controlId,
    headerBind,
    cornerBind,
    invalidated,
    handlePinInput,
    handlePinFocus,
    handlePinPaste,
    descriptionBind,
    handlePinKeyDown,
    showErrorMessageContent,
  } = api;

  const showHeader =
    hasSlotOrProp(slots, "label", merged.label) ||
    hasSlotOrProp(slots, "corner", merged.corner);

  return (
    <div
      {...rootBind}
      data-invalid={invalidated || undefined}
      aria-disabled={merged.disabled || undefined}
      aria-readonly={merged.readonly || undefined}
    >
      {showHeader && (
        <div {...headerBind}>
          <OtpFieldLabel api={api} />

          {hasSlotOrProp(slots, "corner", merged.corner) && (
            <span {...cornerBind}>
              {resolveSlotOrProp({
                slots,
                name: "corner",
                fallback: merged.corner,
              })}
            </span>
          )}
        </div>
      )}

      <div {...groupBind}>
        {Array.from({ length }, (_, index) => (
          <div key={index} {...pinBind(index)}>
            <input
              ref={(element) => setPinRef(index, element)}
              {...inputBind(index)}
              value={digits[index] ?? ""}
              onFocus={() => handlePinFocus(index)}
              onPaste={(event) => handlePinPaste(index, event)}
              onInput={(event) => handlePinInput(index, event)}
              onKeyDown={(event) => handlePinKeyDown(index, event)}
            />
          </div>
        ))}
      </div>

      {!invalidated &&
        hasSlotOrProp(slots, "description", merged.description) && (
          <p {...descriptionBind} id={`${controlId}-description`}>
            {resolveSlotOrProp({
              slots,
              name: "description",
              fallback: merged.description,
            })}
          </p>
        )}

      {!merged.hideErrorMessage && (
        <p
          {...errorBind}
          id={`${controlId}-error`}
          aria-hidden={showErrorMessageContent ? undefined : true}
        >
          {showErrorMessageContent &&
            resolveSlotOrProp({
              slots,
              name: "errorMessage",
              fallback: merged.errorMessage,
            })}
        </p>
      )}
    </div>
  );
}

export default OtpField;

// packages/vue/src/Components/OtpField/OtpField.vue
<script setup lang="ts">
// ** External Imports
import { computed } from "vue";

// ** Local Imports
import { useOtpField } from "@/Components/OtpField/composables/useOtpField";
import type {
  OtpFieldEmits,
  OtpFieldOwnProps,
  OtpFieldSlots,
} from "@/Components/OtpField/otpField.types";
import OtpFieldLabel from "@/Components/OtpField/OtpFieldLabel.vue";
import { hasSlotOrProp, resolveSlotOrProp } from "@/Utils";

defineSlots<OtpFieldSlots>();

defineOptions({ inheritAttrs: false });

const emit = defineEmits<OtpFieldEmits>();

const model = defineModel<null | string | undefined>();

const props = withDefaults(defineProps<OtpFieldOwnProps>(), {
  length: 6,
  size: "md",
  rounded: "md",
  type: "numeric",
  color: "primary",
  variant: "outline",
});

const api = useOtpField(props, model, {
  onChange: (value) => emit("change", value),
  onComplete: (value) => emit("complete", value),
});

const {
  slots,
  merged,
  digits,
  pinBind,
  rootBind,
  errorBind,
  groupBind,
  inputBind,
  setPinRef,
  controlId,
  headerBind,
  cornerBind,
  invalidated,
  handlePinInput,
  handlePinFocus,
  handlePinPaste,
  descriptionBind,
  handlePinKeyDown,
  showErrorMessageContent,
} = api;

const showHeader = computed(() => {
  return (
    hasSlotOrProp(slots, "label", merged.value.label) ||
    hasSlotOrProp(slots, "corner", merged.value.corner)
  );
});
</script>

<template>
  <div
    v-bind="rootBind"
    :data-invalid="invalidated || undefined"
    :aria-disabled="merged.disabled || undefined"
    :aria-readonly="merged.readonly || undefined"
  >
    <div v-if="showHeader" v-bind="headerBind">
      <OtpFieldLabel :api="api" />

      <span
        v-bind="cornerBind"
        v-if="hasSlotOrProp(slots, 'corner', merged.corner)"
      >
        <component :is="resolveSlotOrProp(slots, 'corner', merged.corner)" />
      </span>
    </div>

    <div v-bind="groupBind">
      <div
        :key="index"
        v-bind="pinBind(index)"
        v-for="(digit, index) in digits"
      >
        <input
          v-bind="inputBind(index)"
          :value="digit"
          v-on:focus="handlePinFocus(index)"
          v-on:paste="handlePinPaste(index, $event)"
          v-on:input="handlePinInput(index, $event)"
          v-on:keydown="handlePinKeyDown(index, $event)"
          :ref="(el) => setPinRef(index, el as HTMLInputElement | null)"
        />
      </div>
    </div>

    <p
      v-bind="descriptionBind"
      :id="`${controlId}-description`"
      v-if="
        !invalidated && hasSlotOrProp(slots, 'description', merged.description)
      "
    >
      <component
        :is="resolveSlotOrProp(slots, 'description', merged.description)"
      />
    </p>

    <p
      v-bind="errorBind"
      :id="`${controlId}-error`"
      v-if="!merged.hideErrorMessage"
      :aria-hidden="showErrorMessageContent ? undefined : true"
    >
      <component
        v-if="showErrorMessageContent"
        :is="resolveSlotOrProp(slots, 'errorMessage', merged.errorMessage)"
      />
    </p>
  </div>
</template>
