// packages/react/src/Components/ToggleGroup/ToggleGroup.tsx
// ** Local Imports
import { ToggleGroupContext } from "@/Components/ToggleGroup/ToggleGroupContext";
import { useToggleGroup } from "@/Components/ToggleGroup/hooks/useToggleGroup";
import type { ToggleGroupProps } from "@/Components/ToggleGroup/toggleGroup.types";

const toggleGroupLibDefaults = {
  size: "md",
  full: false,
  rounded: "md",
  disabled: false,
  variant: "solid",
  color: "primary",
  orientation: "horizontal",
} as const;

function ToggleGroup(props: ToggleGroupProps) {
  const { children, rootBind, contextValue } = useToggleGroup(
    props,
    toggleGroupLibDefaults,
  );

  return (
    <ToggleGroupContext.Provider value={contextValue}>
      <div {...rootBind}>{children}</div>
    </ToggleGroupContext.Provider>
  );
}

export default ToggleGroup;

// packages/vue/src/Components/ToggleGroup/ToggleGroup.vue
<script setup lang="ts">
// ** Local Imports
import { useToggleGroup } from "@/Components/ToggleGroup/composables/useToggleGroup";
import type {
  ToggleGroupEmits,
  ToggleGroupOwnProps,
  ToggleGroupSlots,
} from "@/Components/ToggleGroup/toggleGroup.types";

defineSlots<ToggleGroupSlots>();

const emit = defineEmits<ToggleGroupEmits>();

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<ToggleGroupOwnProps>(), {
  full: false,
  disabled: false,
});

const model = defineModel<string>({ default: "" });

const { rootBind } = useToggleGroup(
  props,
  {
    size: "md",
    full: false,
    rounded: "md",
    disabled: false,
    variant: "solid",
    color: "primary",
    orientation: "horizontal",
  },
  model,
  emit,
);
</script>

<template>
  <div v-bind="rootBind">
    <slot />
  </div>
</template>
