// packages/react/src/Components/TabPanel/TabPanel.tsx
// ** Local Imports
import { useTabPanel } from "@/Components/TabPanel/hooks/useTabPanel";
import type { TabPanelProps } from "@/Components/TabPanel/tabPanel.types";

function TabPanel(props: TabPanelProps) {
  const { children, rootBind, selected, keepMounted } = useTabPanel(props);

  if (!selected && !keepMounted) {
    return null;
  }

  return <div {...rootBind}>{children}</div>;
}

export default TabPanel;

// packages/vue/src/Components/TabPanel/TabPanel.vue
<script setup lang="ts">
// ** Local Imports
import { useTabPanel } from "@/Components/TabPanel/composables/useTabPanel";
import type {
  TabPanelOwnProps,
  TabPanelSlots,
} from "@/Components/TabPanel/tabPanel.types";

defineSlots<TabPanelSlots>();

defineOptions({ inheritAttrs: false });

const props = defineProps<TabPanelOwnProps>();

const { rootBind, selected, keepMounted } = useTabPanel(props);
</script>

<template>
  <div v-bind="rootBind" v-if="selected || keepMounted">
    <slot />
  </div>
</template>
