// packages/vue/src/Components/ButtonGroup/ButtonGroup.vue
<script setup lang="ts">
// ** Local Imports
import type {
  ButtonGroupOwnProps,
  ButtonGroupSlots,
} from "@/Components/ButtonGroup/buttonGroup.types";
import { useButtonGroup } from "@/Components/ButtonGroup/composables/useButtonGroup";

defineSlots<ButtonGroupSlots>();

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<ButtonGroupOwnProps>(), {
  full: false,
});

const { rootBind } = useButtonGroup(props, {
  full: false,
  color: "dark",
  orientation: "horizontal",
});
</script>

<template>
  <div v-bind="rootBind">
    <slot />
  </div>
</template>

// packages/react/src/Components/ButtonGroup/ButtonGroup.tsx
// ** Local Imports
import type { ButtonGroupProps } from "@/Components/ButtonGroup/buttonGroup.types";
import { useButtonGroup } from "@/Components/ButtonGroup/hooks/useButtonGroup";

const buttonGroupLibDefaults = {
  full: false,
  color: "dark",
  orientation: "horizontal",
} as const;

function ButtonGroup(props: ButtonGroupProps) {
  const { children, rootBind } = useButtonGroup(props, buttonGroupLibDefaults);

  return <div {...rootBind}>{children}</div>;
}

export default ButtonGroup;
