// packages/vue/src/Components/FormField/FormFieldLabel.vue
<script setup lang="ts">
// ** Local Imports
import { type UseFormFieldReturn } from "@/Components/FormField/composables/useFormField";
import { Label } from "@/Components/Label";
import {
  hasNamedSlot,
  hasSlotOrProp,
  isPropPresent,
  SlotOrProp,
} from "@/Utils";

defineProps<{
  api: UseFormFieldReturn;
}>();
</script>

<template>
  <Label
    v-bind="api.fieldLabelProps.value"
    v-if="hasSlotOrProp(api.slots, 'label', api.merged.value.label)"
  >
    <SlotOrProp
      name="label"
      :slots="api.slots"
      v-if="hasNamedSlot(api.slots, 'label')"
    />

    <template v-else-if="isPropPresent(api.merged.value.label)">
      {{ api.merged.value.label }}
    </template>
  </Label>
</template>

// packages/react/src/Components/FormField/FormFieldLabel.tsx
// ** Local Imports
import type { UseFormFieldReturn } from "@/Components/FormField/hooks/useFormField";
import { Label } from "@/Components/Label";
import {
  hasNamedSlot,
  hasSlotOrProp,
  isPropPresent,
  resolveSlotOrProp,
} from "@/Utils";

type FormFieldLabelProps = {
  api: UseFormFieldReturn;
};

/**
 * Renders the FormField label via `Label` for the string prop and named slots.
 */
function FormFieldLabel({ api }: FormFieldLabelProps) {
  if (!hasSlotOrProp(api.slots, "label", api.merged.label)) {
    return null;
  }

  const content = hasNamedSlot(api.slots, "label")
    ? resolveSlotOrProp({
        name: "label",
        slots: api.slots,
        fallback: api.merged.label,
      })
    : isPropPresent(api.merged.label)
      ? api.merged.label
      : null;

  if (content === null) {
    return null;
  }

  return <Label {...api.fieldLabelProps}>{content}</Label>;
}

export default FormFieldLabel;
