// packages/vue/src/Components/FormField/FormFieldCorner.vue
<script setup lang="ts">
// ** External Imports
import { useSlots } from "vue";

// ** Local Imports
import { type UseFormFieldReturn } from "@/Components/FormField/composables/useFormField";
import { Label } from "@/Components/Label";
import { hasNamedSlot, hasSlotOrProp } from "@/Utils";

defineProps<{
  api: UseFormFieldReturn;
}>();

const slots = useSlots();
</script>

<template>
  <Label
    v-bind="api.fieldCornerProps.value"
    v-if="hasSlotOrProp(slots, 'corner', api.merged.value.corner)"
  >
    <slot name="corner" v-if="hasNamedSlot(slots, 'corner')" />

    <template v-else>{{ api.merged.value.corner }}</template>
  </Label>
</template>

// packages/react/src/Components/FormField/FormFieldCorner.tsx
// ** Local Imports
import type { UseFormFieldReturn } from "@/Components/FormField/hooks/useFormField";
import { Label } from "@/Components/Label";
import { hasNamedSlot, hasSlotOrProp } from "@/Utils";

type FormFieldCornerProps = {
  api: UseFormFieldReturn;
};

/**
 * Renders the FormField corner via `Label` for the string prop and named slots.
 */
function FormFieldCorner({ api }: FormFieldCornerProps) {
  if (!hasSlotOrProp(api.slots, "corner", api.merged.corner)) {
    return null;
  }

  const content = hasNamedSlot(api.slots, "corner")
    ? api.slots?.corner
    : api.merged.corner;

  return <Label {...api.fieldCornerProps}>{content}</Label>;
}

export default FormFieldCorner;
