// packages/react/src/Components/Table/TableRow.tsx
// ** Local Imports
import { useTableRow } from "@/Components/Table/hooks/useTableRow";
import type { TableRowProps } from "@/Components/Table/table.types";

function TableRow(props: TableRowProps) {
  const { children, rootBind } = useTableRow(props);

  return <tr {...rootBind}>{children}</tr>;
}

export default TableRow;

// packages/vue/src/Components/Table/TableRow.vue
<script setup lang="ts">
// ** Local Imports
import { useTableRow } from "@/Components/Table/composables/useTableRow";
import type {
  TableRowOwnProps,
  TableRowSlots,
} from "@/Components/Table/table.types";

defineSlots<TableRowSlots>();

defineOptions({ inheritAttrs: false });

const props = defineProps<TableRowOwnProps>();

const { rootBind } = useTableRow(props);
</script>

<template>
  <tr v-bind="rootBind">
    <slot />
  </tr>
</template>
