// packages/react/src/Components/Table/TableHeader.tsx
// ** Local Imports
import { TableSectionContext } from "@/Components/Table/TableContext";
import { useTablePart } from "@/Components/Table/hooks/useTablePart";
import type { TableHeaderProps } from "@/Components/Table/table.types";

function TableHeader(props: TableHeaderProps) {
  const { children, rootBind } = useTablePart(props, "header");

  return (
    <TableSectionContext.Provider value="header">
      <thead {...rootBind}>{children}</thead>
    </TableSectionContext.Provider>
  );
}

export default TableHeader;

// packages/vue/src/Components/Table/TableHeader.vue
<script setup lang="ts">
// ** Local Imports
import { useTablePart } from "@/Components/Table/composables/useTablePart";
import type {
  TableHeaderOwnProps,
  TableHeaderSlots,
} from "@/Components/Table/table.types";

defineSlots<TableHeaderSlots>();

defineOptions({ inheritAttrs: false });

const props = defineProps<TableHeaderOwnProps>();

const { rootBind } = useTablePart(props, "header");
</script>

<template>
  <thead v-bind="rootBind">
    <slot />
  </thead>
</template>
