// packages/react/src/Components/Table/TableHead.tsx
// ** Local Imports
import { useTableCell } from "@/Components/Table/hooks/useTableCell";
import type { TableHeadProps } from "@/Components/Table/table.types";

function TableHead(props: TableHeadProps) {
  const { children, rootBind } = useTableCell(props, "head");

  return <th {...rootBind}>{children}</th>;
}

export default TableHead;

// packages/vue/src/Components/Table/TableHead.vue
<script setup lang="ts">
// ** Local Imports
import { useTableCell } from "@/Components/Table/composables/useTableCell";
import type {
  TableHeadOwnProps,
  TableHeadSlots,
} from "@/Components/Table/table.types";

defineSlots<TableHeadSlots>();

defineOptions({ inheritAttrs: false });

const props = defineProps<TableHeadOwnProps>();

const { rootBind } = useTableCell(props, "head");
</script>

<template>
  <th v-bind="rootBind">
    <slot />
  </th>
</template>
