// packages/react/src/Components/Table/Table.tsx
// ** Local Imports
import { TableContext } from "@/Components/Table/TableContext";
import { useTable } from "@/Components/Table/hooks/useTable";
import type { TableProps } from "@/Components/Table/table.types";

const tableLibDefaults = {
  size: "md",
  full: true,
  rounded: "lg",
  striped: false,
  variant: "plain",
  hoverable: false,
  stickyHeader: false,
} as const;

function Table(props: TableProps) {
  const { children, wrapBind, rootBind, tableBind, contextValue } = useTable(
    props,
    tableLibDefaults,
  );

  return (
    <TableContext.Provider value={contextValue}>
      <div {...wrapBind}>
        <div {...rootBind}>
          <table {...tableBind}>{children}</table>
        </div>
      </div>
    </TableContext.Provider>
  );
}

export default Table;

// packages/vue/src/Components/Table/Table.vue
<script setup lang="ts">
// ** Local Imports
import { useTable } from "@/Components/Table/composables/useTable";
import type { TableOwnProps, TableSlots } from "@/Components/Table/table.types";

defineSlots<TableSlots>();

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<TableOwnProps>(), {
  full: true,
  striped: false,
  hoverable: false,
  stickyHeader: false,
});

const { wrapBind, rootBind, tableBind } = useTable(props, {
  size: "md",
  full: true,
  rounded: "lg",
  striped: false,
  variant: "plain",
  hoverable: false,
  stickyHeader: false,
});
</script>

<template>
  <div v-bind="wrapBind">
    <div v-bind="rootBind">
      <table v-bind="tableBind">
        <slot />
      </table>
    </div>
  </div>
</template>
