// packages/react/src/Components/Skeleton/Skeleton.tsx
// ** Local Imports
import type { SkeletonProps } from "@/Components/Skeleton";
import { useSkeleton } from "@/Components/Skeleton";

function Skeleton(props: SkeletonProps) {
  const { rootBind } = useSkeleton(props, {
    rounded: "md",
  });

  return <div {...rootBind} />;
}

export default Skeleton;

// packages/vue/src/Components/Skeleton/Skeleton.vue
<script setup lang="ts">
// ** Local Imports
import { useSkeleton } from "@/Components/Skeleton/composables/useSkeleton";
import type { SkeletonOwnProps } from "@/Components/Skeleton/skeleton.types";

defineOptions({ inheritAttrs: false });

const props = defineProps<SkeletonOwnProps>();

const { rootBind } = useSkeleton(props, {
  rounded: "md",
});
</script>

<template>
  <div v-bind="rootBind" />
</template>
