// packages/react/src/Actions/Snackbar/BridgeSnackbarHost.tsx
// ** External Imports
import {
  completeLayerHide,
  invokeLayerDismiss,
  mergeLayerShellProps,
} from "@bridge-ui/core";
import { get } from "es-toolkit/compat";
import { useContext, useEffect, useMemo, type ReactNode } from "react";
import { createPortal } from "react-dom";

// ** Core Imports
import {
  cn,
  mergeBridgeUILayeredClasses,
  resolveModalPortalElement,
  snackbarPositionProps,
} from "@bridge-ui/core";

// ** Local Imports
import { BridgeSnackbarContext } from "@/Actions/Snackbar/BridgeSnackbarContext";
import type { BridgeSnackbarShellProps } from "@/Actions/Snackbar/bridgeSnackbar.types";
import { useBridgeSnackbarController } from "@/Actions/Snackbar/createBridgeSnackbarController";
import { resolveBridgeSnackbarSlots } from "@/Actions/Snackbar/resolveBridgeSnackbarSlots";
import { Snackbar } from "@/Components/Snackbar";
import { useBridgeUI } from "@/Provider/useBridgeUI";

export type BridgeSnackbarHostProps = {
  children?: ReactNode;
  /**
   * Stack position on the viewport.
   *
   * @default "bottom-center"
   */
  position?: keyof typeof snackbarPositionProps;
  /**
   * Portal target. `false` renders inline.
   *
   * @default "body"
   */
  teleportTo?: string | false;
  /**
   * Default shell options merged into every snackbar opened via `useBridgeSnackbar()`.
   * Per-call `open()` options override these.
   */
  snackbar?: BridgeSnackbarShellProps;
};

const NESTED_HOST_WARNING =
  "[Bridge UI] Nested <BridgeSnackbarHost /> detected. useBridgeSnackbar() will target the nearest host only. Remove the extra host.";

export function BridgeSnackbarHost({
  children,
  position,
  teleportTo = "body",
  snackbar: hostSnackbar,
}: BridgeSnackbarHostProps) {
  const parentApi = useContext(BridgeSnackbarContext);
  const api = useBridgeSnackbarController();
  const bridge = useBridgeUI();

  useEffect(() => {
    if (parentApi && process.env.NODE_ENV !== "production") {
      console.warn(NESTED_HOST_WARNING);
    }
  }, [parentApi]);

  const snackbarEntry = bridge?.components?.Snackbar;

  const resolvedPosition =
    position ?? snackbarEntry?.defaultProps?.position ?? "bottom-center";

  const positionClass = useMemo(() => {
    const classes = mergeBridgeUILayeredClasses(
      snackbarPositionProps,
      snackbarEntry?.customProps?.position,
    );

    return get(classes, resolvedPosition);
  }, [resolvedPosition, snackbarEntry?.customProps?.position]);

  const stack = (
    <div
      data-snackbar-host
      className={cn(
        "fixed inset-0 z-40 flex pointer-events-none px-4 py-6 sm:p-5 sm:pt-4",
        positionClass,
      )}
    >
      <div className="flex flex-col-reverse w-full max-w-sm gap-y-2 pointer-events-auto">
        {api.entries.map((entry) => {
          const { actions, rightButtons, ...entrySnackbar } = entry.props;

          const snackbarProps = mergeLayerShellProps(
            hostSnackbar,
            entrySnackbar,
          );

          const dismiss = () => invokeLayerDismiss(api.entries, entry.id);

          return (
            <Snackbar
              key={entry.id}
              show={entry.show}
              stackId={entry.id}
              teleportTo={false}
              {...snackbarProps}
              slots={resolveBridgeSnackbarSlots(
                {
                  actions,
                  rightButtons,
                  dense: snackbarProps.dense,
                  color: snackbarProps.color,
                },
                dismiss,
              )}
              onClose={dismiss}
              onShowChange={(show) => {
                api.syncShow(entry.id, show);
                completeLayerHide(api.entries, entry.id, show, api.removeEntry);
              }}
            />
          );
        })}
      </div>
    </div>
  );

  const portalElement =
    teleportTo === false || typeof document === "undefined"
      ? null
      : resolveModalPortalElement(teleportTo);

  return (
    <BridgeSnackbarContext.Provider value={api}>
      {children}
      {portalElement ? createPortal(stack, portalElement) : stack}
    </BridgeSnackbarContext.Provider>
  );
}

// packages/vue/src/Actions/Snackbar/BridgeSnackbarHost.vue
<script setup lang="ts">
// ** External Imports
import { get } from "es-toolkit/compat";
import { computed, inject, provide } from "vue";

// ** Core Imports
import {
  cn,
  mergeBridgeUILayeredClasses,
  snackbarPositionProps,
} from "@bridge-ui/core";

// ** Local Imports
import type { BridgeSnackbarShellProps } from "@/Actions/Snackbar/bridgeSnackbar.types";
import { BRIDGE_SNACKBAR_INJECTION_KEY } from "@/Actions/Snackbar/bridgeSnackbarInjectionKey";
import BridgeSnackbarItem from "@/Actions/Snackbar/BridgeSnackbarItem.vue";
import { createBridgeSnackbarApi } from "@/Actions/Snackbar/createBridgeSnackbarApi";
import { useBridgeUI } from "@/Provider/useBridgeUI";

const NESTED_HOST_WARNING =
  "[Bridge UI] Nested <BridgeSnackbarHost /> detected. useBridgeSnackbar() will target the nearest host only. Remove the extra host.";

const props = withDefaults(
  defineProps<{
    position?: keyof typeof snackbarPositionProps;
    teleportTo?: string | false;
    /**
     * Default shell options merged into every snackbar opened via `useBridgeSnackbar()`.
     * Per-call `open()` options override these.
     */
    snackbar?: BridgeSnackbarShellProps;
  }>(),
  {
    teleportTo: "body",
  },
);

const parentApi = inject(BRIDGE_SNACKBAR_INJECTION_KEY, null);

if (parentApi && process.env.NODE_ENV !== "production") {
  console.warn(NESTED_HOST_WARNING);
}

const api = createBridgeSnackbarApi();
const bridge = useBridgeUI();

provide(BRIDGE_SNACKBAR_INJECTION_KEY, api);

const snackbarEntries = computed(() => api.entries.value);

const snackbarEntry = computed(() => bridge?.components.value.Snackbar);

const resolvedPosition = computed(() => {
  return (
    props.position ??
    snackbarEntry.value?.defaultProps?.position ??
    "bottom-center"
  );
});

const positionClass = computed(() => {
  const classes = mergeBridgeUILayeredClasses(
    snackbarPositionProps,
    snackbarEntry.value?.customProps?.position,
  );

  return get(classes, resolvedPosition.value);
});

const teleportDisabled = computed(() => props.teleportTo === false);

const teleportTarget = computed(() => {
  if (props.teleportTo === false) {
    return "body";
  }

  return props.teleportTo;
});
</script>

<template>
  <slot />

  <Teleport :to="teleportTarget" :disabled="teleportDisabled">
    <div
      data-snackbar-host
      :class="
        cn(
          'fixed inset-0 z-40 flex pointer-events-none px-4 py-6 sm:p-5 sm:pt-4',
          positionClass,
        )
      "
    >
      <div
        class="flex flex-col-reverse w-full max-w-sm gap-y-2 pointer-events-auto"
      >
        <BridgeSnackbarItem
          :key="entry.id"
          v-for="entry in snackbarEntries"
          :api="api"
          :entry="entry"
          :host-snackbar="props.snackbar"
        />
      </div>
    </div>
  </Teleport>
</template>
