// packages/react/src/Components/ButtonGroup/ButtonGroupText.tsx
// ** External Imports
import { createElement } from "react";

// ** Local Imports
import type { ButtonGroupTextProps } from "@/Components/ButtonGroup/buttonGroup.types";
import { useButtonGroupText } from "@/Components/ButtonGroup/hooks/useButtonGroupText";

function ButtonGroupText(props: ButtonGroupTextProps) {
  const { tag, children, rootBind } = useButtonGroupText(props, {
    as: "span",
  });

  return createElement(tag, rootBind, children);
}

export default ButtonGroupText;

// packages/vue/src/Components/ButtonGroup/ButtonGroupText.vue
<script setup lang="ts">
// ** Local Imports
import type {
  ButtonGroupTextOwnProps,
  ButtonGroupTextSlots,
} from "@/Components/ButtonGroup/buttonGroup.types";
import { useButtonGroupText } from "@/Components/ButtonGroup/composables/useButtonGroupText";

defineSlots<ButtonGroupTextSlots>();

defineOptions({ inheritAttrs: false });

const props = defineProps<ButtonGroupTextOwnProps>();

const { tag, rootBind } = useButtonGroupText(props, {
  as: "span",
});
</script>

<template>
  <component :is="tag" v-bind="rootBind">
    <slot />
  </component>
</template>
