// packages/vue/src/Components/DateField/DateField.vue
<script setup lang="ts">
// ** External Imports
import { ref } from "vue";

// ** Core Imports
import type { DatePickerModel } from "@bridge-ui/core/Domain";

// ** Local Imports
import { useResolveMessage } from "@/Adapters/I18n";
import { useDateField } from "@/Components/DateField/composables/useDateField";
import type {
  DateFieldEmits,
  DateFieldOwnProps,
  DateFieldSlots,
} from "@/Components/DateField/dateField.types";
import { DatePicker } from "@/Components/DatePicker";
import { FieldOverlay } from "@/Components/FieldOverlay";
import {
  FORM_FIELD_CHROME_SLOT_NAMES,
  FormField,
} from "@/Components/FormField";
import { Icon } from "@/Components/Icon";
import { presentSlotNames, useOptionalModel } from "@/Utils";

defineSlots<DateFieldSlots>();

defineOptions({ inheritAttrs: false });

const emit = defineEmits<DateFieldEmits>();

const resolveMessage = useResolveMessage();

const model = defineModel<DatePickerModel>();

const props = withDefaults(defineProps<DateFieldOwnProps>(), {
  fill: undefined,
  clearable: false,
  showErrorIcon: true,
  showFooter: undefined,
});

const uncontrolledValue = ref<DatePickerModel>(props.defaultValue ?? null);

const value = useOptionalModel(model, uncontrolledValue);

const {
  open,
  fill,
  overlay,
  dateOnly,
  formField,
  inputBind,
  clearBind,
  clearValue,
  modelValue,
  showFooter,
  pickerClass,
  clearIconSize,
  showClearIcon,
  handleOpenChange,
  handlePickerChange,
  handlePickerCancel,
  overlayCustomProps,
  datePickerCustomProps,
} = useDateField(props, value, emit);
</script>

<template>
  <FormField :field="formField">
    <template
      #[name]="slotData"
      v-for="name in presentSlotNames(FORM_FIELD_CHROME_SLOT_NAMES, $slots)"
    >
      <slot :name="name" v-bind="slotData || {}" />
    </template>

    <div class="flex min-w-0 flex-1 items-center gap-1">
      <input v-bind="inputBind" />

      <span
        v-bind="clearBind"
        v-if="showClearIcon"
        v-on:click="clearValue"
        :aria-label="resolveMessage('Clear')"
        v-on:keydown.enter.prevent="clearValue"
        v-on:keydown.space.prevent="clearValue"
      >
        <Icon
          icon="clear"
          :size="clearIconSize"
          v-bind="props.customProps?.clearIcon"
        />
      </span>
    </div>
  </FormField>

  <FieldOverlay
    :overlay="overlay"
    :model-value="open"
    :custom-props="overlayCustomProps"
    v-on:update:model-value="handleOpenChange"
  >
    <DatePicker
      :fill="fill"
      :value="modelValue"
      :class="pickerClass"
      :range="dateOnly.range"
      :show-footer="showFooter"
      :read-only="props.readonly"
      :max-date="dateOnly.maxDate"
      :min-date="dateOnly.minDate"
      :multiple="dateOnly.multiple"
      :time-zone="dateOnly.timeZone"
      :hide-years="dateOnly.hideYears"
      v-on:change="handlePickerChange"
      v-on:cancel="handlePickerCancel"
      :hide-months="dateOnly.hideMonths"
      :default-view="dateOnly.defaultView"
      :error="formField.invalidated.value"
      :color="formField.merged.value.color"
      :start-of-week="dateOnly.startOfWeek"
      :custom-props="datePickerCustomProps"
      :disabled="formField.isDisabled.value"
      :disable-dates="dateOnly.disableDates"
      :hide-weekdays="dateOnly.hideWeekdays"
      :disable-years="dateOnly.disableYears"
      :disable-months="dateOnly.disableMonths"
      :rounded="formField.merged.value.rounded"
      :hide-outside-days="dateOnly.hideOutsideDays"
    >
      <template #day="cell">
        <slot name="day" v-bind="cell">{{ cell.label }}</slot>
      </template>

      <template #footer="footer" v-if="$slots.footer">
        <slot name="footer" v-bind="footer" />
      </template>
    </DatePicker>
  </FieldOverlay>
</template>

// packages/react/src/Components/DateField/DateField.tsx
// ** Local Imports
import { useResolveMessage } from "@/Adapters/I18n";
import type { DateFieldProps } from "@/Components/DateField/dateField.types";
import { useDateField } from "@/Components/DateField/hooks/useDateField";
import { DatePicker } from "@/Components/DatePicker";
import { FieldOverlay } from "@/Components/FieldOverlay";
import { FormField } from "@/Components/FormField";
import { Icon } from "@/Components/Icon";

function DateField(props: DateFieldProps) {
  const resolveMessage = useResolveMessage();

  const {
    open,
    fill,
    daySlot,
    overlay,
    dateOnly,
    formField,
    inputBind,
    clearBind,
    footerSlot,
    clearValue,
    modelValue,
    showFooter,
    clearIconSize,
    showClearIcon,
    pickerClassName,
    handleOpenChange,
    handlePickerChange,
    handlePickerCancel,
    overlayCustomProps,
    datePickerCustomProps,
  } = useDateField(props);

  return (
    <>
      <FormField field={formField}>
        <div className="flex min-w-0 flex-1 items-center gap-1">
          <input {...inputBind} />

          {showClearIcon ? (
            <span
              {...clearBind}
              onClick={() => clearValue()}
              aria-label={resolveMessage("Clear")}
              onKeyDown={(event) => {
                if (event.key === "Enter" || event.key === " ") {
                  event.preventDefault();
                  clearValue();
                }
              }}
            >
              <Icon
                icon="clear"
                size={clearIconSize}
                {...props.customProps?.clearIcon}
              />
            </span>
          ) : null}
        </div>
      </FormField>

      <FieldOverlay
        show={open}
        overlay={overlay}
        onShowChange={handleOpenChange}
        customProps={overlayCustomProps}
      >
        <DatePicker
          fill={fill}
          value={modelValue}
          range={dateOnly.range}
          showFooter={showFooter}
          readOnly={props.readonly}
          maxDate={dateOnly.maxDate}
          minDate={dateOnly.minDate}
          className={pickerClassName}
          multiple={dateOnly.multiple}
          timeZone={dateOnly.timeZone}
          onChange={handlePickerChange}
          onCancel={handlePickerCancel}
          error={formField.invalidated}
          hideYears={dateOnly.hideYears}
          color={formField.merged.color}
          disabled={formField.isDisabled}
          hideMonths={dateOnly.hideMonths}
          defaultView={dateOnly.defaultView}
          startOfWeek={dateOnly.startOfWeek}
          rounded={formField.merged.rounded}
          customProps={datePickerCustomProps}
          disableDates={dateOnly.disableDates}
          hideWeekdays={dateOnly.hideWeekdays}
          disableYears={dateOnly.disableYears}
          disableMonths={dateOnly.disableMonths}
          hideOutsideDays={dateOnly.hideOutsideDays}
          slots={
            daySlot || footerSlot
              ? { day: daySlot, footer: footerSlot }
              : undefined
          }
        />
      </FieldOverlay>
    </>
  );
}

export default DateField;
