// packages/vue/src/Components/TabList/TabList.vue
<script setup lang="ts">
// ** Local Imports
import { useTabList } from "@/Components/TabList/composables/useTabList";
import type {
  TabListOwnProps,
  TabListSlots,
} from "@/Components/TabList/tabList.types";

defineSlots<TabListSlots>();

defineOptions({ inheritAttrs: false });

const props = defineProps<TabListOwnProps>();

const { rootBind } = useTabList(props);
</script>

<template>
  <div v-bind="rootBind">
    <slot />
  </div>
</template>

// packages/react/src/Components/TabList/TabList.tsx
// ** Local Imports
import { useTabList } from "@/Components/TabList/hooks/useTabList";
import type { TabListProps } from "@/Components/TabList/tabList.types";

function TabList(props: TabListProps) {
  const { children, rootBind } = useTabList(props);

  return <div {...rootBind}>{children}</div>;
}

export default TabList;
