// packages/react/src/Components/Divider/Divider.tsx
// ** Local Imports
import type { DividerProps } from "@/Components/Divider";
import { useDivider } from "@/Components/Divider";

function Divider(props: DividerProps) {
  const { rootBind } = useDivider(props, {
    color: "dark",
    orientation: "horizontal",
  });

  return <hr {...rootBind} />;
}

export default Divider;

// packages/vue/src/Components/Divider/Divider.vue
<script setup lang="ts">
// ** Local Imports
import { useDivider } from "@/Components/Divider/composables/useDivider";
import type { DividerOwnProps } from "@/Components/Divider/divider.types";

defineOptions({ inheritAttrs: false });

const props = defineProps<DividerOwnProps>();

const { rootBind } = useDivider(props, {
  color: "dark",
  orientation: "horizontal",
});
</script>

<template>
  <hr v-bind="rootBind" />
</template>
