// packages/react/src/Components/FieldOverlay/FieldOverlay.tsx
// ** External Imports
import { useMemo } from "react";

// ** Local Imports
import { Drawer } from "@/Components/Drawer";
import type { FieldOverlayProps } from "@/Components/FieldOverlay/fieldOverlay.types";
import {
  FieldOverlayContext,
  type FieldOverlayFooterContextValue,
} from "@/Components/FieldOverlay/FieldOverlayContext";
import { useFieldOverlay } from "@/Components/FieldOverlay/hooks/useFieldOverlay";
import { Menu } from "@/Components/Menu";
import { Modal } from "@/Components/Modal";

function FieldOverlay(props: FieldOverlayProps) {
  const { onShowChange } = props;
  const {
    children,
    menuProps,
    modalProps,
    drawerProps,
    resolvedOverlay,
    drawerScrollerBind,
  } = useFieldOverlay(props);

  const footer = useMemo((): FieldOverlayFooterContextValue => {
    return {
      apply: () => {
        onShowChange?.(false);
      },
      cancel: () => {
        onShowChange?.(false);
      },
    };
  }, [onShowChange]);

  const content =
    resolvedOverlay === "modal" ? (
      <Modal {...modalProps}>{children}</Modal>
    ) : resolvedOverlay === "drawer" ? (
      <Drawer {...drawerProps}>
        <div {...drawerScrollerBind}>{children}</div>
      </Drawer>
    ) : (
      <Menu {...menuProps}>{children}</Menu>
    );

  return (
    <FieldOverlayContext.Provider value={footer}>
      {content}
    </FieldOverlayContext.Provider>
  );
}

export default FieldOverlay;

// packages/vue/src/Components/FieldOverlay/FieldOverlay.vue
<script setup lang="ts">
// ** External Imports
import { provide } from "vue";

// ** Local Imports
import { Drawer } from "@/Components/Drawer";
import { useFieldOverlay } from "@/Components/FieldOverlay/composables/useFieldOverlay";
import type {
  FieldOverlayEmits,
  FieldOverlayOwnProps,
  FieldOverlaySlots,
} from "@/Components/FieldOverlay/fieldOverlay.types";
import { FIELD_OVERLAY_INJECTION_KEY } from "@/Components/FieldOverlay/fieldOverlayInjectionKey";
import { Menu } from "@/Components/Menu";
import { Modal } from "@/Components/Modal";

defineSlots<FieldOverlaySlots>();

defineOptions({ inheritAttrs: false });

const emit = defineEmits<FieldOverlayEmits>();

const props = withDefaults(defineProps<FieldOverlayOwnProps>(), {
  overlay: "auto",
});

const model = defineModel<boolean>({ default: false });

const { menuBind, modalBind, drawerBind, resolvedOverlay, drawerScrollerBind } =
  useFieldOverlay(props);

provide(FIELD_OVERLAY_INJECTION_KEY, {
  apply: () => {
    model.value = false;
  },
  cancel: () => {
    model.value = false;
  },
});

function handleShowChange(show: boolean) {
  emit("show-change", show);
}

function handleClose() {
  emit("close");
}
</script>

<template>
  <Menu
    v-model="model"
    v-bind="menuBind"
    v-on:close="handleClose"
    v-if="resolvedOverlay === 'menu'"
    v-on:update:model-value="handleShowChange"
  >
    <slot />
  </Menu>

  <Modal
    v-model="model"
    v-bind="modalBind"
    v-on:close="handleClose"
    v-on:show-change="handleShowChange"
    v-else-if="resolvedOverlay === 'modal'"
  >
    <slot />
  </Modal>

  <Drawer
    v-else
    v-model="model"
    v-bind="drawerBind"
    v-on:close="handleClose"
    v-on:show-change="handleShowChange"
  >
    <div v-bind="drawerScrollerBind">
      <slot />
    </div>
  </Drawer>
</template>
