// packages/vue/src/Components/FormControl/FormControlLabel.vue
<script setup lang="ts">
// ** Local Imports
import type { UseFormControlReturn } from "@/Components/FormControl/composables/useFormControl";
import { Label } from "@/Components/Label";
import {
  hasNamedSlot,
  hasSlotOrProp,
  isPropPresent,
  SlotOrProp,
} from "@/Utils";

defineProps<{
  api: UseFormControlReturn;
  name: "endLabel" | "startLabel";
}>();
</script>

<template>
  <Label
    v-bind="api.fieldLabelProps.value[name]"
    v-if="hasSlotOrProp(api.slots, name, api.merged.value[name])"
  >
    <SlotOrProp
      :name="name"
      :slots="api.slots"
      v-if="hasNamedSlot(api.slots, name)"
    />

    <template v-else-if="isPropPresent(api.merged.value[name])">
      {{ api.merged.value[name] }}
    </template>
  </Label>
</template>

// packages/react/src/Components/FormControl/FormControlLabel.tsx
// ** Local Imports
import type { UseFormControlReturn } from "@/Components/FormControl/hooks/useFormControl";
import { Label } from "@/Components/Label";
import { hasNamedSlot, hasSlotOrProp } from "@/Utils";

type FormControlLabelPart = "endLabel" | "startLabel";

type FormControlLabelProps = {
  api: UseFormControlReturn;
  name: FormControlLabelPart;
};

/**
 * Renders a FormControl label via `Label` for string props and named slots.
 */
function FormControlLabel({ api, name }: FormControlLabelProps) {
  const value = api.merged[name];

  if (!hasSlotOrProp(api.slots, name, value)) {
    return null;
  }

  const content = hasNamedSlot(api.slots, name) ? api.slots?.[name] : value;

  return <Label {...api.fieldLabelProps[name]}>{content}</Label>;
}

export default FormControlLabel;
