// packages/vue/src/Components/Sidebar/SidebarProvider.vue
<script setup lang="ts">
// ** Local Imports
import { useSidebarProvider } from "@/Components/Sidebar/composables/useSidebarProvider";
import type {
  SidebarProviderEmits,
  SidebarProviderOwnProps,
  SidebarProviderSlots,
} from "@/Components/Sidebar/sidebar.types";

defineSlots<SidebarProviderSlots>();

const emit = defineEmits<SidebarProviderEmits>();

defineOptions({ inheritAttrs: false, name: "SidebarProvider" });

const props = withDefaults(defineProps<SidebarProviderOwnProps>(), {
  defaultOpen: true,
});

const open = defineModel<boolean | undefined>({ default: undefined });

const { rootBind } = useSidebarProvider(
  props,
  {
    defaultOpen: true,
  },
  open,
  emit,
);
</script>

<template>
  <div v-bind="rootBind">
    <slot />
  </div>
</template>

// packages/react/src/Components/Sidebar/SidebarProvider.tsx
// ** Local Imports
import { useSidebarProvider } from "@/Components/Sidebar/hooks/useSidebarProvider";
import type { SidebarProviderProps } from "@/Components/Sidebar/sidebar.types";
import { SidebarContext } from "@/Components/Sidebar/SidebarContext";

const sidebarProviderLibDefaults = {
  defaultOpen: true,
} as const;

function SidebarProvider(props: SidebarProviderProps) {
  const { children, rootBind, contextValue } = useSidebarProvider(
    props,
    sidebarProviderLibDefaults,
  );

  return (
    <SidebarContext.Provider value={contextValue}>
      <div {...rootBind}>{children}</div>
    </SidebarContext.Provider>
  );
}

export default SidebarProvider;
