// packages/vue/src/Components/Sidebar/SidebarInset.vue
<script setup lang="ts">
// ** Local Imports
import { useSidebarInset } from "@/Components/Sidebar/composables/useSidebarInset";
import type {
  SidebarInsetOwnProps,
  SidebarInsetSlots,
} from "@/Components/Sidebar/sidebar.types";

defineSlots<SidebarInsetSlots>();

defineOptions({ inheritAttrs: false, name: "SidebarInset" });

const props = defineProps<SidebarInsetOwnProps>();

const { rootBind } = useSidebarInset(props);
</script>

<template>
  <main v-bind="rootBind">
    <slot />
  </main>
</template>

// packages/react/src/Components/Sidebar/SidebarInset.tsx
// ** Local Imports
import { useSidebarInset } from "@/Components/Sidebar/hooks/useSidebarInset";
import type { SidebarInsetProps } from "@/Components/Sidebar/sidebar.types";

function SidebarInset(props: SidebarInsetProps) {
  const { children, rootBind } = useSidebarInset(props);

  return <main {...rootBind}>{children}</main>;
}

export default SidebarInset;
