// packages/vue/src/Components/Sidebar/Sidebar.vue
<script setup lang="ts">
// ** Local Imports
import { Drawer } from "@/Components/Drawer";
import { useSidebarShell } from "@/Components/Sidebar/composables/useSidebarShell";
import type {
  SidebarOwnProps,
  SidebarSlots,
} from "@/Components/Sidebar/sidebar.types";
import { hasNamedSlot } from "@/Utils";

defineSlots<SidebarSlots>();

defineOptions({ name: "Sidebar", inheritAttrs: false });

const props = withDefaults(defineProps<SidebarOwnProps>(), {
  side: "left",
  variant: "sidebar",
  ariaLabel: "Sidebar",
  collapsible: "offcanvas",
});

const {
  slots,
  merged,
  panelId,
  gapBind,
  rootBind,
  isMobile,
  asideBind,
  panelBind,
  headerBind,
  footerBind,
  openMobile,
  contentBind,
  showAsDrawer,
  setOpenMobile,
} = useSidebarShell(props, {
  side: "left",
  variant: "sidebar",
  ariaLabel: "Sidebar",
  collapsible: "offcanvas",
});
</script>

<template>
  <div v-bind="rootBind">
    <div v-bind="gapBind" />

    <aside v-bind="asideBind">
      <div v-bind="panelBind">
        <template v-if="!showAsDrawer">
          <div v-bind="headerBind" v-if="hasNamedSlot(slots, 'header')">
            <slot name="header" />
          </div>

          <div v-bind="contentBind">
            <slot />
          </div>

          <div v-bind="footerBind" v-if="hasNamedSlot(slots, 'footer')">
            <slot name="footer" />
          </div>
        </template>
      </div>
    </aside>
  </div>

  <Drawer
    v-if="isMobile"
    :placement="merged.side"
    :model-value="openMobile"
    @show-change="setOpenMobile"
    :aria-label="merged.ariaLabel"
    @update:model-value="setOpenMobile"
    :custom-props="{
      panel: {
        id: showAsDrawer ? panelId : undefined,
        class: 'p-0',
        style: { width: 'var(--bridge-sidebar-width-mobile)' },
      },
    }"
  >
    <div v-bind="panelBind" v-if="showAsDrawer">
      <div v-bind="headerBind" v-if="hasNamedSlot(slots, 'header')">
        <slot name="header" />
      </div>

      <div v-bind="contentBind">
        <slot />
      </div>

      <div v-bind="footerBind" v-if="hasNamedSlot(slots, 'footer')">
        <slot name="footer" />
      </div>
    </div>
  </Drawer>
</template>

// packages/react/src/Components/Sidebar/Sidebar.tsx
// ** Local Imports
import { Drawer } from "@/Components/Drawer";
import { useSidebarShell } from "@/Components/Sidebar/hooks/useSidebarShell";
import type { SidebarProps } from "@/Components/Sidebar/sidebar.types";
import { hasNamedSlot } from "@/Utils";

const sidebarLibDefaults = {
  side: "left",
  variant: "sidebar",
  ariaLabel: "Sidebar",
  collapsible: "offcanvas",
} as const;

function SidebarPanelBody({
  slots,
  children,
  headerBind,
  footerBind,
  contentBind,
}: Pick<
  ReturnType<typeof useSidebarShell>,
  "slots" | "children" | "footerBind" | "headerBind" | "contentBind"
>) {
  return (
    <>
      {hasNamedSlot(slots, "header") ? (
        <div {...headerBind}>{slots?.header}</div>
      ) : null}

      <div {...contentBind}>{children}</div>

      {hasNamedSlot(slots, "footer") ? (
        <div {...footerBind}>{slots?.footer}</div>
      ) : null}
    </>
  );
}

function Sidebar(props: SidebarProps) {
  const {
    slots,
    merged,
    panelId,
    gapBind,
    children,
    rootBind,
    isMobile,
    asideBind,
    panelBind,
    headerBind,
    footerBind,
    openMobile,
    contentBind,
    showAsDrawer,
    setOpenMobile,
  } = useSidebarShell(props, sidebarLibDefaults);

  const body = (
    <SidebarPanelBody
      slots={slots}
      children={children}
      headerBind={headerBind}
      footerBind={footerBind}
      contentBind={contentBind}
    />
  );

  return (
    <>
      <div {...rootBind}>
        <div {...gapBind} />

        <aside {...asideBind}>
          <div {...panelBind}>{showAsDrawer ? null : body}</div>
        </aside>
      </div>

      {isMobile ? (
        <Drawer
          show={openMobile}
          placement={merged.side}
          ariaLabel={merged.ariaLabel}
          onShowChange={setOpenMobile}
          customProps={{
            panel: {
              className: "p-0",
              id: showAsDrawer ? panelId : undefined,
              style: {
                width: "var(--bridge-sidebar-width-mobile)",
              },
            },
          }}
        >
          <div {...panelBind}>{showAsDrawer ? body : null}</div>
        </Drawer>
      ) : null}
    </>
  );
}

export default Sidebar;
